<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="ArcForges.Build.Policy" Version="1.0.0-ci.21.1" />
    <PackageVersion Include="ArcForges.Contracts.PublicApi" Version="1.0.0-ci.74.1" />
    <PackageVersion Include="Grpc.AspNetCore" Version="2.84.0" />
    <PackageVersion Include="Grpc.AspNetCore.Web" Version="2.84.0" />
    <PackageVersion Include="Grpc.Net.Client" Version="2.84.0" />
    <PackageVersion Include="xunit.v3.mtp-v2" Version="4.0.1" />
  </ItemGroup>
</Project>
