// SPDX-License-Identifier: AGPL-3.0-only
// <auto-generated />
// Generated by eng/verification/storage-plans.ts from the reviewed plan files; do not edit.
#nullable enable
namespace ArcForges.Cloud.Storage;

/// <summary>Typed definitions of the reviewed named plans and their single manifest identity.</summary>
internal static class PlanManifest
{
    public const string Hash = "e5011e9e7e0fd1136500863021a2fc079e4c894af13f1a850eb1ade5111f5cf0";

    public static readonly PlanDefinition AccountLoad = new(
        "foundation.account-load",
        1,
        PlanAccess.Read,
        1,
        [
            new([new(PlanKind.Scope), new(PlanKind.Text)], [new(PlanKind.Int64), new(PlanKind.Int64)])
        ]);

    public static readonly PlanDefinition AccountSeed = new(
        "foundation.account-seed",
        1,
        PlanAccess.Write,
        0,
        [
            new([new(PlanKind.Scope), new(PlanKind.Text), new(PlanKind.Int64)], null)
        ]);

    public static readonly PlanDefinition ExactLoad = new(
        "foundation.exact-load",
        1,
        PlanAccess.Read,
        1,
        [
            new([new(PlanKind.Scope), new(PlanKind.Text)], [new(PlanKind.Int64), new(PlanKind.Uint64), new(PlanKind.Decimal), new(PlanKind.Bytes, true), new(PlanKind.Int64)])
        ]);

    public static readonly PlanDefinition ExactStore = new(
        "foundation.exact-store",
        1,
        PlanAccess.Write,
        0,
        [
            new([new(PlanKind.Text), new(PlanKind.Scope), new(PlanKind.Text), new(PlanKind.Int64)], null),
            new([new(PlanKind.Scope), new(PlanKind.Text), new(PlanKind.Int64), new(PlanKind.Uint64), new(PlanKind.Decimal), new(PlanKind.Bytes, true), new(PlanKind.Int64)], null),
            new([new(PlanKind.Scope), new(PlanKind.Text), new(PlanKind.Text), new(PlanKind.Text)], null),
            new([new(PlanKind.Text)], null)
        ]);

    public static readonly PlanDefinition InboxSeen = new(
        "foundation.inbox-seen",
        1,
        PlanAccess.Read,
        1,
        [
            new([new(PlanKind.Scope), new(PlanKind.Text), new(PlanKind.Int64)], [new(PlanKind.Int64)])
        ]);

    public static readonly PlanDefinition JobClaim = new(
        "foundation.job-claim",
        1,
        PlanAccess.Write,
        0,
        [
            new([new(PlanKind.Text), new(PlanKind.Scope), new(PlanKind.Text), new(PlanKind.Int64), new(PlanKind.Text)], null),
            new([new(PlanKind.Text), new(PlanKind.Int64), new(PlanKind.Scope), new(PlanKind.Text)], null),
            new([new(PlanKind.Text)], null)
        ]);

    public static readonly PlanDefinition JobCommit = new(
        "foundation.job-commit",
        1,
        PlanAccess.Write,
        0,
        [
            new([new(PlanKind.Text), new(PlanKind.Scope), new(PlanKind.Text), new(PlanKind.Int64), new(PlanKind.Text), new(PlanKind.Int64), new(PlanKind.Int64)], null),
            new([new(PlanKind.Scope), new(PlanKind.Text), new(PlanKind.Text)], null),
            new([new(PlanKind.Int64), new(PlanKind.Uint64), new(PlanKind.Int64), new(PlanKind.Scope), new(PlanKind.Text), new(PlanKind.Int64)], null),
            new([new(PlanKind.Scope), new(PlanKind.Text), new(PlanKind.Int64)], null),
            new([new(PlanKind.Scope), new(PlanKind.Text), new(PlanKind.Text), new(PlanKind.Text)], null),
            new([new(PlanKind.Text)], null)
        ]);

    public static readonly PlanDefinition JobItems = new(
        "foundation.job-items",
        1,
        PlanAccess.Read,
        1,
        [
            new([new(PlanKind.Scope), new(PlanKind.Text)], [new(PlanKind.Int64), new(PlanKind.Int64)])
        ]);

    public static readonly PlanDefinition JobLoad = new(
        "foundation.job-load",
        1,
        PlanAccess.Read,
        1,
        [
            new([new(PlanKind.Scope), new(PlanKind.Text)], [new(PlanKind.Int64), new(PlanKind.Int64), new(PlanKind.Int64), new(PlanKind.Text, true), new(PlanKind.Int64, true), new(PlanKind.Text), new(PlanKind.Uint64), new(PlanKind.Int64)])
        ]);

    public static readonly PlanDefinition JobStart = new(
        "foundation.job-start",
        1,
        PlanAccess.Write,
        0,
        [
            new([new(PlanKind.Scope), new(PlanKind.Text), new(PlanKind.Int64)], null),
            new([new(PlanKind.Scope), new(PlanKind.Text), new(PlanKind.Text), new(PlanKind.Text)], null)
        ]);

    public static readonly PlanDefinition OutboxState = new(
        "foundation.outbox-state",
        1,
        PlanAccess.Read,
        1,
        [
            new([new(PlanKind.Scope)], [new(PlanKind.Int64), new(PlanKind.Int64)])
        ]);

    public static readonly PlanDefinition Readiness = new(
        "foundation.readiness",
        1,
        PlanAccess.Read,
        1,
        [
            new([], [new(PlanKind.Int64)])
        ]);

    public static readonly PlanDefinition ReceiptLoad = new(
        "foundation.receipt-load",
        1,
        PlanAccess.Read,
        1,
        [
            new([new(PlanKind.Scope), new(PlanKind.Text)], [new(PlanKind.Text), new(PlanKind.Text)])
        ]);

    public static readonly PlanDefinition SessionCreate = new(
        "foundation.session-create",
        1,
        PlanAccess.Write,
        0,
        [
            new([new(PlanKind.Scope), new(PlanKind.Text), new(PlanKind.Bytes), new(PlanKind.Text), new(PlanKind.Text), new(PlanKind.Text), new(PlanKind.Int64), new(PlanKind.Int64), new(PlanKind.Int64), new(PlanKind.Int64), new(PlanKind.Int64), new(PlanKind.Int64)], null),
            new([new(PlanKind.Scope), new(PlanKind.Text), new(PlanKind.Text), new(PlanKind.Text)], null)
        ]);

    public static readonly PlanDefinition SessionLoad = new(
        "foundation.session-load",
        1,
        PlanAccess.Read,
        1,
        [
            new([new(PlanKind.Scope), new(PlanKind.Bytes)], [new(PlanKind.Text), new(PlanKind.Text), new(PlanKind.Text), new(PlanKind.Text), new(PlanKind.Int64), new(PlanKind.Int64), new(PlanKind.Int64), new(PlanKind.Int64), new(PlanKind.Int64), new(PlanKind.Int64), new(PlanKind.Int64, true), new(PlanKind.Text, true)])
        ]);

    public static readonly PlanDefinition SessionLoadById = new(
        "foundation.session-load-by-id",
        1,
        PlanAccess.Read,
        1,
        [
            new([new(PlanKind.Scope), new(PlanKind.Text)], [new(PlanKind.Text), new(PlanKind.Text), new(PlanKind.Text), new(PlanKind.Text), new(PlanKind.Int64), new(PlanKind.Int64), new(PlanKind.Int64), new(PlanKind.Int64), new(PlanKind.Int64), new(PlanKind.Int64), new(PlanKind.Int64, true), new(PlanKind.Text, true)])
        ]);

    public static readonly PlanDefinition SessionRevoke = new(
        "foundation.session-revoke",
        1,
        PlanAccess.Write,
        0,
        [
            new([new(PlanKind.Text), new(PlanKind.Scope), new(PlanKind.Text)], null),
            new([new(PlanKind.Int64), new(PlanKind.Text), new(PlanKind.Scope), new(PlanKind.Text)], null),
            new([new(PlanKind.Scope), new(PlanKind.Text), new(PlanKind.Text), new(PlanKind.Text)], null),
            new([new(PlanKind.Text)], null)
        ]);

    public static readonly PlanDefinition SessionTouch = new(
        "foundation.session-touch",
        1,
        PlanAccess.Write,
        0,
        [
            new([new(PlanKind.Int64), new(PlanKind.Int64), new(PlanKind.Scope), new(PlanKind.Bytes), new(PlanKind.Int64), new(PlanKind.Int64)], null)
        ]);

    public static readonly PlanDefinition Transfer = new(
        "foundation.transfer",
        1,
        PlanAccess.Write,
        0,
        [
            new([new(PlanKind.Text), new(PlanKind.Scope), new(PlanKind.Text), new(PlanKind.Int64), new(PlanKind.Int64), new(PlanKind.Scope), new(PlanKind.Text), new(PlanKind.Int64)], null),
            new([new(PlanKind.Int64), new(PlanKind.Scope), new(PlanKind.Text), new(PlanKind.Int64)], null),
            new([new(PlanKind.Int64), new(PlanKind.Scope), new(PlanKind.Text), new(PlanKind.Int64)], null),
            new([new(PlanKind.Scope), new(PlanKind.Text), new(PlanKind.Text), new(PlanKind.Text)], null),
            new([new(PlanKind.Scope), new(PlanKind.Text), new(PlanKind.Text), new(PlanKind.Text)], null),
            new([new(PlanKind.Text)], null)
        ]);

    public static readonly IReadOnlyList<PlanDefinition> All = [AccountLoad, AccountSeed, ExactLoad, ExactStore, InboxSeen, JobClaim, JobCommit, JobItems, JobLoad, JobStart, OutboxState, Readiness, ReceiptLoad, SessionCreate, SessionLoad, SessionLoadById, SessionRevoke, SessionTouch, Transfer];
}
