// SPDX-License-Identifier: AGPL-3.0-only
// The generator of the Worker's transport tables and of the committed Contracts identity (CLOUD.84 D3, S33(3)(a), S34, S35(2)).
// Usage, from the repository root: `generate` writes the outputs; `check` fails when a committed output differs from the generated bytes.
using System.Text;

namespace ArcForges.Cloud.Tools.Generation;

public static class Program
{
    public const string TablesPath = "worker/tables/cloud-tables.generated.ts";
    public const string IdentityPath = "eng/generated/contracts-identity.json";

    public static int Main(string[] args)
    {
        if (args.Length != 1 || args[0] is not ("generate" or "check"))
        {
            Console.Error.WriteLine("usage: ArcForges.Cloud.Generation generate | check");
            return 2;
        }

        var generate = args[0] == "generate";
        var root = FindRoot(Directory.GetCurrentDirectory());
        var assembly = typeof(ArcForges.Cloud.HelloEndpoint).Assembly;
        var outputs = new (string Path, byte[] Bytes)[]
        {
            (TablesPath, Encoding.UTF8.GetBytes(TypeScriptTables.Render(HostReader.Read()))),
            (IdentityPath, ContractsIdentity.Read(assembly)),
        };

        var stale = new List<string>();
        foreach (var (path, bytes) in outputs)
        {
            var full = Path.Combine(root, path);
            if (generate)
            {
                Directory.CreateDirectory(Path.GetDirectoryName(full)!);
                File.WriteAllBytes(full, bytes);
            }
            else if (!File.Exists(full) || !File.ReadAllBytes(full).AsSpan().SequenceEqual(bytes))
            {
                stale.Add(path);
            }
        }

        if (stale.Count > 0)
        {
            foreach (var path in stale) Console.Error.WriteLine($"Out of date: {path}. Run npm run generate and commit the result.");
            return 1;
        }

        Console.WriteLine(generate ? "Generated the Worker tables and the Contracts identity." : "The generated outputs are current.");
        return 0;
    }

    private static string FindRoot(string start)
    {
        var directory = new DirectoryInfo(start);
        while (directory is not null && !File.Exists(Path.Combine(directory.FullName, "Cloud.slnx"))) directory = directory.Parent;
        return directory?.FullName ?? throw new InvalidOperationException("Run the generator inside the Cloud repository.");
    }
}
