// SPDX-License-Identifier: AGPL-3.0-only
using System.Globalization;
using System.Text;

namespace ArcForges.Cloud.Tools.Generation;

/// <summary>
/// Renders worker/tables/cloud-tables.generated.ts from the model. The layout is the one prettier keeps unchanged under this repository's
/// settings (printWidth 100, double quotes, trailing commas, two-space indentation), so the file passes format:check without a formatter run.
/// </summary>
public static class TypeScriptTables
{
    private const string Header = """
        // SPDX-License-Identifier: AGPL-3.0-only
        // GENERATED by tools/ArcForges.Cloud.Generation from the C# host registrations (HelloModule and PipelineProbe), the transport
        // budgets and correlation guards in src/ArcForges.Cloud/Generation and the edge-guard constants of IngressPipeline. Do not edit by hand: run
        // `npm run generate` and commit the result. `npm run check:generated` fails on any drift. The Worker applies these guards
        // before it forwards a call; nothing here grants anything.
        """;

    public static string Render(TableModel model)
    {
        var text = new StringBuilder();
        text.Append(Header).Append('\n');
        text.Append('\n');
        text.Append("""
            /** The kind of a method the Worker admits: one unary reply, or a server stream. */
            export type RouteKind = "unary" | "serverStream";
            /** anonymous: no credential is read or forwarded; session: bearer or origin-bound cookie, checked again by the host. */
            export type RouteAuth = "anonymous" | "session";

            export interface ApiRoute {
              /** The method path without the owned /api prefix: /package.Service/Method. */
              readonly path: string;
              readonly kind: RouteKind;
              readonly auth: RouteAuth;
              /** Bound of the whole request body, frame header included. Unary and server-streaming requests are one message. */
              readonly maxRequestBytes: number;
              /** Bound of one response frame. */
              readonly maxFrameBytes: number;
              /** Bound of a whole unary response (buffered); a stream has no total bound, only its lifetime. */
              readonly maxUnaryResponseBytes: number;
              /** Cap of the RPC deadline (unary) or of the stream's lifetime (server stream). */
              readonly maxDurationMs: number;
              /** The Container instance (Durable Object name) that serves the method. */
              readonly instance: string;
              /**
               * The request message starts with a RequestMeta (field 1, wire registry 04). Only then does the edge read the client's
               * correlation id from it; a method whose field 1 means something else (the Hello name) is never interpreted.
               */
              readonly requestMeta: boolean;
            }
            """).Append("\n\n");
        text.Append("export const helloPath = ").Append(Quote(model.HelloPath)).Append(";\n");
        text.Append("export const healthPath = ").Append(Quote(model.HealthPath)).Append(";\n");
        text.Append("/** The bound of a whole request body of a method that declares no larger one, frame header included. */\n");
        text.Append("export const maxBodyBytes = ").Append(Number(model.MaxBodyBytes)).Append(";\n");
        text.Append("/** The Container may take at most this long to start before a stream's response headers arrive. */\n");
        text.Append("export const coldStartBudgetMs = ").Append(Number(model.ColdStartMilliseconds)).Append(";\n");
        text.Append("/** A server stream's lifetime when the client states no shorter deadline: the annex 10 server close after five minutes plus slack. */\n");
        text.Append("export const streamLifetimeMs = ").Append(Number(model.StreamLifetimeMilliseconds)).Append(";\n");
        text.Append('\n');

        text.Append("/** The health route: a small plain reply that the pipeline answers itself. */\n");
        text.Append("export const healthRoute: ApiRoute = {\n");
        Route(text, model.Health, "  ");
        text.Append("};\n\n");

        text.Append("/** The methods the production Worker serves. */\n");
        text.Append("export const productionRoutes: readonly ApiRoute[] = [\n");
        foreach (var route in model.Production)
        {
            text.Append("  {\n");
            Route(text, route, "    ");
            text.Append("  },\n");
        }

        text.Append("];\n\n");

        text.Append("// Proof-only pipeline probe (the isolated proof environment, FOUNDATION_PROOF=enabled): an authenticated\n");
        text.Append("// workspace-scoped unary call, a timed server stream and an observation of how the host saw its streams end.\n");
        text.Append("export const proofRoutes: readonly ApiRoute[] = [\n");
        foreach (var route in model.Proof)
        {
            text.Append("  {\n");
            Route(text, route, "    ");
            text.Append("  },\n");
        }

        text.Append("];\n\n");

        text.Append("/** The session credential names the edge checks read; the header name is lowercase as the Worker forwards it. */\n");
        text.Append("export const edgeGuard = {\n");
        text.Append("  sessionCookieName: ").Append(Quote(model.SessionCookieName)).Append(",\n");
        text.Append("  csrfHeader: ").Append(Quote(model.CsrfHeader)).Append(",\n");
        text.Append("} as const;\n\n");

        var correlation = model.Correlation;
        text.Append("/** The correlation guards (CR-01, CR-03): the identity shape, the fields that carry it and the traceparent form the Worker writes. */\n");
        text.Append("export const correlationGuard = {\n");
        text.Append("  uuidPattern: ").Append(Quote(correlation.UuidPattern)).Append(",\n");
        text.Append("  nilUuid: ").Append(Quote(correlation.NilUuid)).Append(",\n");
        text.Append("  requestMetaField: ").Append(Number(correlation.RequestMetaField)).Append(",\n");
        text.Append("  correlationIdField: ").Append(Number(correlation.CorrelationIdField)).Append(",\n");
        text.Append("  idValueField: ").Append(Number(correlation.IdValueField)).Append(",\n");
        text.Append("  idByteLength: ").Append(Number(correlation.IdByteLength)).Append(",\n");
        text.Append("  traceparentVersion: ").Append(Quote(correlation.TraceparentVersion)).Append(",\n");
        text.Append("  traceparentFlags: ").Append(Quote(correlation.TraceparentFlags)).Append(",\n");
        text.Append("} as const;\n");
        return text.ToString();
    }

    private static void Route(StringBuilder text, RouteRow route, string indent)
    {
        text.Append(indent).Append("path: ").Append(Quote(route.Path)).Append(",\n");
        text.Append(indent).Append("kind: ").Append(Quote(route.Kind)).Append(",\n");
        text.Append(indent).Append("auth: ").Append(Quote(route.Auth)).Append(",\n");
        text.Append(indent).Append("maxRequestBytes: ").Append(Number(route.MaxRequestBytes)).Append(",\n");
        text.Append(indent).Append("maxFrameBytes: ").Append(Number(route.MaxFrameBytes)).Append(",\n");
        text.Append(indent).Append("maxUnaryResponseBytes: ").Append(Number(route.MaxUnaryResponseBytes)).Append(",\n");
        text.Append(indent).Append("maxDurationMs: ").Append(Number(route.MaxDurationMilliseconds)).Append(",\n");
        text.Append(indent).Append("instance: ").Append(Quote(route.Instance)).Append(",\n");
        text.Append(indent).Append("requestMeta: ").Append(route.RequestMeta ? "true" : "false").Append(",\n");
    }

    private static string Number(int value) => value.ToString(CultureInfo.InvariantCulture);

    /// <summary>A double-quoted TypeScript string. The values are method paths, names and fixed words, so only the escapes that could occur are handled.</summary>
    private static string Quote(string value)
    {
        if (value.Any(character => character is '"' or '\\' or '\n' or '\r'))
            throw new InvalidOperationException("A generated TypeScript string may not contain quotes, backslashes or line breaks.");
        return "\"" + value + "\"";
    }
}
