// SPDX-License-Identifier: AGPL-3.0-only
// The three outputs of the storage-plan generator (CLOUD.84 U7; port of the renderers and generate() in eng/verification/storage-plans.ts):
//   worker/storage/plans.generated.ts            the Worker dictionary (formatted as Prettier formats it)
//   src/ArcForges.Cloud.Storage.D1/PlanManifest.g.cs  the typed C# definitions and the manifest identity
//   storage/plans/families.expanded.json          every family plan with its expanded statements (formatted as Prettier formats JSON)
using System.Globalization;
using System.Text;

namespace ArcForges.Cloud.Tools.Generation.StoragePlans;

public static class StoragePlanOutputs
{
    public const string TypeScriptOutput = "worker/storage/plans.generated.ts";
    public const string CSharpOutput = "src/ArcForges.Cloud.Storage.D1/PlanManifest.g.cs";
    public const string FamilyExpansionOutput = "storage/plans/families.expanded.json";

    /// <summary>The C# enum member of each SU-04 module and of the platform pseudo-module (SharedFamilies/FamilyModule.cs).</summary>
    private static readonly IReadOnlyDictionary<string, string> ModuleEnum = new Dictionary<string, string>(StringComparer.Ordinal)
    {
        ["config"] = "Configuration",
        ["identity"] = "Identity",
        ["workspace"] = "Workspace",
        ["device"] = "Device",
        ["entitlement"] = "Entitlement",
        ["commerce"] = "Commerce",
        ["policy"] = "Policy",
        ["agent"] = "Agent",
        ["chat"] = "Chat",
        ["scope"] = "Scope",
        ["task"] = "Task",
        ["search"] = "Search",
        ["package-catalog"] = "PackageCatalog",
        ["notification"] = "Notification",
        ["resource"] = "Resource",
        ["sync"] = "Sync",
        ["audit"] = "Audit",
        ["platform"] = "Platform",
    };

    private const string TypeScriptHeader =
        "// SPDX-License-Identifier: AGPL-3.0-only\n" +
        "// <auto-generated />\n" +
        "// Generated by eng/verification/storage-plans.ts from the reviewed plan files; do not edit.\n";

    /// <summary>The three outputs of a manifest, in the order the Node generator wrote them.</summary>
    public static IReadOnlyList<(string Path, string Text)> Render(PlanManifest manifest) =>
    [
        (TypeScriptOutput, RenderTypeScript(manifest)),
        (CSharpOutput, RenderCSharp(manifest)),
        (FamilyExpansionOutput, RenderFamilyExpansion(manifest)),
    ];

    /// <summary>The Node-compatible JSON string of a value: the escapes JavaScript's JSON.stringify writes.</summary>
    public static string JsonString(string value)
    {
        var builder = new StringBuilder(value.Length + 2);
        builder.Append('"');
        foreach (var character in value)
        {
            switch (character)
            {
                case '"':
                    builder.Append("\\\"");
                    break;
                case '\\':
                    builder.Append("\\\\");
                    break;
                case '\b':
                    builder.Append("\\b");
                    break;
                case '\f':
                    builder.Append("\\f");
                    break;
                case '\n':
                    builder.Append("\\n");
                    break;
                case '\r':
                    builder.Append("\\r");
                    break;
                case '\t':
                    builder.Append("\\t");
                    break;
                default:
                    if (character < 0x20)
                        builder.Append("\\u").Append(((int)character).ToString("x4", CultureInfo.InvariantCulture));
                    else
                        builder.Append(character);
                    break;
            }
        }

        builder.Append('"');
        return builder.ToString();
    }

    private static Doc ObjectLiteral(IReadOnlyList<(string Key, Doc Value)> properties, bool trailingComma)
    {
        if (properties.Count == 0) return Layout.Text("{}");
        var parts = new List<Doc>();
        for (var index = 0; index < properties.Count; index++)
        {
            if (index > 0)
            {
                parts.Add(Layout.Text(","));
                parts.Add(Layout.Line);
            }

            parts.Add(Layout.Text($"{properties[index].Key}: "));
            parts.Add(properties[index].Value);
        }

        return Layout.Group(
            Layout.Concat(
                Layout.Text("{"),
                Layout.Indent(Layout.Concat(Layout.Line, Layout.Concat(parts.ToArray()))),
                trailingComma ? Layout.IfBreak(Layout.Text(","), Layout.Text(string.Empty)) : Layout.Text(string.Empty),
                Layout.Line,
                Layout.Text("}")));
    }

    /// <summary>
    /// An array literal. Prettier breaks an array of two or more objects that each have more than one property, so the
    /// <paramref name="multiKeyObjects"/> flag is set for those arrays.
    /// </summary>
    private static Doc ArrayLiteral(IReadOnlyList<Doc> items, bool trailingComma, bool multiKeyObjects)
    {
        if (items.Count == 0) return Layout.Text("[]");
        var parts = new List<Doc>();
        for (var index = 0; index < items.Count; index++)
        {
            if (index > 0)
            {
                parts.Add(Layout.Text(","));
                parts.Add(Layout.Line);
            }

            parts.Add(items[index]);
        }

        return Layout.Group(
            Layout.Concat(
                Layout.Text("["),
                Layout.Indent(Layout.Concat(Layout.SoftLine, Layout.Concat(parts.ToArray()))),
                trailingComma ? Layout.IfBreak(Layout.Text(","), Layout.Text(string.Empty)) : Layout.Text(string.Empty),
                Layout.SoftLine,
                Layout.Text("]")),
            shouldBreak: items.Count > 1 && multiKeyObjects);
    }

    private static Doc ParameterArray(IReadOnlyList<PlanParameter> parameters, bool trailingComma) =>
        ArrayLiteral(
            parameters.Select(parameter => ObjectLiteral(
                [
                    ("kind", Layout.Text(JsonString(parameter.Kind))),
                    ("nullable", Layout.Text(parameter.Nullable ? "true" : "false")),
                ],
                trailingComma)).ToList(),
            trailingComma,
            multiKeyObjects: true);

    /// <summary>The Worker dictionary: the same shape the Node generator wrote, formatted with Prettier's layout at print width 100.</summary>
    public static string RenderTypeScript(PlanManifest manifest)
    {
        var plans = manifest.Plans.Select(plan => ObjectLiteral(
            [
                ("id", Layout.Text(JsonString(plan.Id))),
                ("version", Layout.Text(plan.Version.ToString(CultureInfo.InvariantCulture))),
                ("access", Layout.Text(JsonString(plan.Access))),
                ("maxRows", Layout.Text(plan.MaxRows.ToString(CultureInfo.InvariantCulture))),
                ("statements", ArrayLiteral(
                    plan.Statements.Select(statement => ObjectLiteral(
                        [
                            ("sql", Layout.Text(JsonString(statement.Sql))),
                            ("params", ParameterArray(statement.Params, trailingComma: true)),
                            ("returns", statement.Returns is null ? Layout.Text("null") : ParameterArray(statement.Returns, trailingComma: true)),
                        ],
                        trailingComma: true)).ToList(),
                    trailingComma: true,
                    multiKeyObjects: true)),
            ],
            trailingComma: true)).ToList();
        var body = ArrayLiteral(plans, trailingComma: true, multiKeyObjects: true);
        var prefix = TypeScriptHeader
            + "import type { PlanDefinition } from \"./plan-types.ts\";\n\n"
            + $"export const manifestHash = {JsonString(manifest.ManifestHash)};\n\n"
            + "export const plans: readonly PlanDefinition[] = ";
        return prefix + Layout.Print(body, startColumn: prefix.Length - prefix.LastIndexOf('\n') - 1) + ";\n";
    }

    private static string CSharpKind(string kind) => kind switch
    {
        "int64" => "Int64",
        "uint64" => "Uint64",
        "decimal" => "Decimal",
        "text" => "Text",
        "bytes" => "Bytes",
        "bool" => "Bool",
        "scope" => "Scope",
        _ => throw new PlanRefusal($"unknown kind {kind}"),
    };

    private static string ModuleMember(string module) =>
        ModuleEnum.TryGetValue(module, out var member) ? member : throw new PlanRefusal(module);

    /// <summary>The pascal-cased word of each dash-separated part, with the Node quirk that an empty part reads as "undefined".</summary>
    private static string Pascal(string text) =>
        string.Concat(text.Split('-').Select(part =>
            part.Length > 0 ? char.ToUpperInvariant(part[0]) + part[1..] : "undefined"));

    /// <summary>The member name of a plan inside its owner's class: the id without the owner segment.</summary>
    private static string MemberName(string id) => Pascal(string.Join("-", id.Split('.').Skip(1)));

    private static string IndentLines(string text, string indent) => indent + text.Replace("\n", "\n" + indent, StringComparison.Ordinal);

    /// <summary>The typed C# definitions and the single manifest identity.</summary>
    public static string RenderCSharp(PlanManifest manifest)
    {
        string Param(PlanParameter value) => $"new(PlanKind.{CSharpKind(value.Kind)}{(value.Nullable ? ", true" : string.Empty)})";
        string ParamList(IReadOnlyList<PlanParameter> values) => $"[{string.Join(", ", values.Select(Param))}]";
        string Member(PlanDefinition plan)
        {
            var statements = string.Join(
                ",\n",
                plan.Statements.Select(statement =>
                    $"            new({ParamList(statement.Params)}, {(statement.Returns is null ? "null" : ParamList(statement.Returns))})"));
            return "        public static readonly PlanDefinition " + MemberName(plan.Id) + " = new(\n"
                + $"            {JsonString(plan.Id)},\n"
                + $"            {plan.Version.ToString(CultureInfo.InvariantCulture)},\n"
                + $"            PlanAccess.{(plan.Access == "read" ? "Read" : "Write")},\n"
                + $"            {plan.MaxRows.ToString(CultureInfo.InvariantCulture)},\n"
                + "            [\n"
                + IndentLines(statements, "    ") + "\n"
                + "            ]);";
        }

        var owners = manifest.Registry.Owners
            .Where(entry => manifest.Plans.Any(plan => plan.Id.StartsWith(entry.Owner + ".", StringComparison.Ordinal)))
            .ToList();
        var classes = new List<string>();
        var all = new List<string>();
        foreach (var entry in owners)
        {
            var own = manifest.Plans.Where(plan => plan.Id.StartsWith(entry.Owner + ".", StringComparison.Ordinal)).ToList();
            var names = own.Select(plan => MemberName(plan.Id)).ToList();
            SqlText.Require(names.Distinct(StringComparer.Ordinal).Count() == names.Count, $"{entry.Owner}: two plans share a member name");
            classes.Add(
                $"    /// <summary>The reviewed plans of the {entry.Owner} owner (<c>storage/plans/{entry.Owner}</c>).</summary>\n"
                + $"    internal static class {entry.ClassName}\n"
                + "    {\n"
                + string.Join("\n\n", own.Select(Member)) + "\n"
                + "    }");
            all.AddRange(own.Select(plan => $"{entry.ClassName}.{MemberName(plan.Id)}"));
        }

        var familyPlans = manifest.Plans.Where(plan => plan.Family is not null).ToList();
        var familyNames = familyPlans.Select(plan => MemberName(plan.Id)).ToList();
        SqlText.Require(familyNames.Distinct(StringComparer.Ordinal).Count() == familyNames.Count, "two family plans share a member name");
        var familyClass = familyPlans.Count == 0
            ? string.Empty
            : "\n\n    /// <summary>The reviewed shared family plans (<c>storage/plans/families</c>); <see cref=\"FamilyPlans\"/> describes their statements.</summary>\n"
                + "    internal static class Families\n"
                + "    {\n"
                + string.Join("\n\n", familyPlans.Select(Member)) + "\n"
                + "    }";
        all.AddRange(familyNames.Select(name => $"Families.{name}"));
        var catalog = manifest.Families.Families.Select(family =>
            $"        new({JsonString(family.Family)}, {JsonString(family.Title)}, {JsonString(family.Source)}, [{string.Join(", ", family.Participants.Select(participant =>
                $"new(FamilyModule.{ModuleMember(participant.Module)}, {(participant.Requirement == "required" ? "true" : "false")}, {(participant.When is null ? "null" : JsonString(participant.When))})"))}])")
            .ToList();
        var roles = familyPlans.Select(plan =>
            $"        new(Families.{MemberName(plan.Id)}, {JsonString(plan.Family ?? string.Empty)}, [\n"
            + string.Join(",\n", plan.Statements.Select(statement =>
                {
                    var meta = statement.Family ?? throw new PlanRefusal($"{plan.Id}: a statement has no family role");
                    return $"            new(FamilyModule.{ModuleMember(meta.Module)}, FamilyPhase.{Pascal(meta.Phase)}, FamilyClass.{Pascal(meta.Class)}, {JsonString(meta.Key)})";
                }))
            + "\n        ])")
            .ToList();
        return "// SPDX-License-Identifier: AGPL-3.0-only\n"
            + "// <auto-generated />\n"
            + "// Generated by eng/verification/storage-plans.ts from the reviewed plan files; do not edit.\n"
            + "#nullable enable\n"
            + "using ArcForges.Cloud.Storage.SharedFamilies;\n\n"
            + "namespace ArcForges.Cloud.Storage;\n\n"
            + "/// <summary>Typed definitions of the reviewed named plans and their single manifest identity.</summary>\n"
            + "internal static class PlanManifest\n"
            + "{\n"
            + $"    public const string Hash = \"{manifest.ManifestHash}\";\n\n"
            + string.Join("\n\n", classes) + familyClass + "\n\n"
            + $"    public static readonly IReadOnlyList<PlanDefinition> All = [{string.Join(", ", all)}];\n\n"
            + "    /// <summary>The closed registry of shared transaction families (<c>storage/plans/families.json</c>, Design SU-01).</summary>\n"
            + $"    public static readonly IReadOnlyList<FamilyDefinition> FamilyCatalog = {ListLiteral(catalog)};\n\n"
            + "    /// <summary>The statement roles of every shared family plan, in plan order.</summary>\n"
            + $"    public static readonly IReadOnlyList<FamilyPlanDefinition> FamilyPlans = {ListLiteral(roles)};\n"
            + "}\n";
    }

    private static string ListLiteral(IReadOnlyList<string> items) =>
        items.Count == 0 ? "[]" : $"[\n{string.Join(",\n", items)}\n    ]";

    /// <summary>Every family plan with its expanded statements: the SQL, the role and the parameter kinds, formatted as Prettier formats JSON.</summary>
    public static string RenderFamilyExpansion(PlanManifest manifest)
    {
        var plans = manifest.Plans
            .Where(plan => plan.Family is not null)
            .Select(plan => ObjectLiteral(
                [
                    ("\"id\"", Layout.Text(JsonString(plan.Id))),
                    ("\"version\"", Layout.Text(plan.Version.ToString(CultureInfo.InvariantCulture))),
                    ("\"family\"", Layout.Text(JsonString(plan.Family ?? string.Empty))),
                    ("\"sha256\"", Layout.Text(JsonString(plan.Sha256))),
                    ("\"statements\"", ArrayLiteral(
                        plan.Statements.Select(statement => ObjectLiteral(
                            [
                                ("\"role\"", Layout.Text(JsonString(statement.Family is null
                                    ? string.Empty
                                    : $"{statement.Family.Phase} {statement.Family.Module} {statement.Family.Class} {statement.Family.Key}"))),
                                ("\"sql\"", Layout.Text(JsonString(statement.Sql))),
                                ("\"params\"", ArrayLiteral(
                                    statement.Params.Select(parameter => Layout.Text(JsonString(parameter.Kind + (parameter.Nullable ? "?" : string.Empty)))).ToList(),
                                    trailingComma: false,
                                    multiKeyObjects: false)),
                            ],
                            trailingComma: false)).ToList(),
                        trailingComma: false,
                        multiKeyObjects: true)),
                ],
                trailingComma: false))
            .ToList();
        var root = ObjectLiteral(
            [
                ("\"schemaVersion\"", Layout.Text("1")),
                ("\"plans\"", ArrayLiteral(plans, trailingComma: false, multiKeyObjects: true)),
            ],
            trailingComma: false);
        return Layout.Print(root, startColumn: 0) + "\n";
    }
}
