// SPDX-License-Identifier: AGPL-3.0-only
// <auto-generated />
// Generated by eng/verification/storage-plans.ts from the reviewed plan files; do not edit.
import type { PlanDefinition } from "./plan-types.ts";

export const manifestHash = "fd997113ed229737822cc0e346e27d19db8ac628edfb53557dc672bfd00768b5";

export const plans: readonly PlanDefinition[] = [
  {
    id: "foundation.account-load",
    version: 1,
    access: "read",
    maxRows: 1,
    statements: [
      {
        sql: "SELECT CAST(balance AS TEXT), CAST(revision AS TEXT) FROM probe_account WHERE scope = ? AND id = ?;",
        params: [
          { kind: "scope", nullable: false },
          { kind: "text", nullable: false },
        ],
        returns: [
          { kind: "int64", nullable: false },
          { kind: "int64", nullable: false },
        ],
      },
    ],
  },
  {
    id: "foundation.account-seed",
    version: 1,
    access: "write",
    maxRows: 0,
    statements: [
      {
        sql: "INSERT INTO probe_account (scope, id, balance, revision) VALUES (?, ?, CAST(? AS INTEGER), 1)\nON CONFLICT (scope, id) DO NOTHING;",
        params: [
          { kind: "scope", nullable: false },
          { kind: "text", nullable: false },
          { kind: "int64", nullable: false },
        ],
        returns: null,
      },
    ],
  },
  {
    id: "foundation.exact-load",
    version: 1,
    access: "read",
    maxRows: 1,
    statements: [
      {
        sql: "SELECT CAST(signed_value AS TEXT), unsigned_text, decimal_text, payload, CAST(revision AS TEXT)\nFROM probe_exact WHERE scope = ? AND id = ?;",
        params: [
          { kind: "scope", nullable: false },
          { kind: "text", nullable: false },
        ],
        returns: [
          { kind: "int64", nullable: false },
          { kind: "uint64", nullable: false },
          { kind: "decimal", nullable: false },
          { kind: "bytes", nullable: true },
          { kind: "int64", nullable: false },
        ],
      },
    ],
  },
  {
    id: "foundation.exact-store",
    version: 1,
    access: "write",
    maxRows: 0,
    statements: [
      {
        sql: "INSERT INTO probe_guard (command_id, allowed)\nSELECT ?, CASE WHEN COALESCE((SELECT revision FROM probe_exact WHERE scope = ? AND id = ?), 0) = CAST(? AS INTEGER) THEN 1 ELSE 0 END;",
        params: [
          { kind: "text", nullable: false },
          { kind: "scope", nullable: false },
          { kind: "text", nullable: false },
          { kind: "int64", nullable: false },
        ],
        returns: null,
      },
      {
        sql: "INSERT INTO probe_exact (scope, id, signed_value, unsigned_text, decimal_text, payload, revision)\nVALUES (?, ?, CAST(? AS INTEGER), ?, ?, ?, CAST(? AS INTEGER) + 1)\nON CONFLICT (scope, id) DO UPDATE SET signed_value = excluded.signed_value, unsigned_text = excluded.unsigned_text,\n  decimal_text = excluded.decimal_text, payload = excluded.payload, revision = excluded.revision;",
        params: [
          { kind: "scope", nullable: false },
          { kind: "text", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "uint64", nullable: false },
          { kind: "decimal", nullable: false },
          { kind: "bytes", nullable: true },
          { kind: "int64", nullable: false },
        ],
        returns: null,
      },
      {
        sql: "INSERT INTO probe_receipt (scope, command_id, request_hash, result_json) VALUES (?, ?, ?, ?);",
        params: [
          { kind: "scope", nullable: false },
          { kind: "text", nullable: false },
          { kind: "text", nullable: false },
          { kind: "text", nullable: false },
        ],
        returns: null,
      },
      {
        sql: "DELETE FROM probe_guard WHERE command_id = ?;",
        params: [{ kind: "text", nullable: false }],
        returns: null,
      },
    ],
  },
  {
    id: "foundation.inbox-seen",
    version: 1,
    access: "read",
    maxRows: 1,
    statements: [
      {
        sql: "SELECT CAST(COUNT(*) AS TEXT) FROM probe_inbox WHERE scope = ? AND consumer = 'job-slice' AND event_id = ? AND generation = CAST(? AS INTEGER);",
        params: [
          { kind: "scope", nullable: false },
          { kind: "text", nullable: false },
          { kind: "int64", nullable: false },
        ],
        returns: [{ kind: "int64", nullable: false }],
      },
    ],
  },
  {
    id: "foundation.job-claim",
    version: 1,
    access: "write",
    maxRows: 0,
    statements: [
      {
        sql: "INSERT INTO probe_guard (command_id, allowed)\nSELECT ?, CASE WHEN EXISTS (SELECT 1 FROM probe_job WHERE scope = ? AND job_id = ? AND state = 'running'\n  AND (lease_owner IS NULL OR lease_until <= CAST(? AS INTEGER) OR lease_owner = ?)) THEN 1 ELSE 0 END;",
        params: [
          { kind: "text", nullable: false },
          { kind: "scope", nullable: false },
          { kind: "text", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "text", nullable: false },
        ],
        returns: null,
      },
      {
        sql: "UPDATE probe_job SET lease_owner = ?, lease_until = CAST(? AS INTEGER), fence = fence + 1 WHERE scope = ? AND job_id = ?;",
        params: [
          { kind: "text", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "scope", nullable: false },
          { kind: "text", nullable: false },
        ],
        returns: null,
      },
      {
        sql: "DELETE FROM probe_guard WHERE command_id = ?;",
        params: [{ kind: "text", nullable: false }],
        returns: null,
      },
    ],
  },
  {
    id: "foundation.job-commit",
    version: 1,
    access: "write",
    maxRows: 0,
    statements: [
      {
        sql: "INSERT INTO probe_guard (command_id, allowed)\nSELECT ?, CASE WHEN EXISTS (SELECT 1 FROM probe_job WHERE scope = ? AND job_id = ? AND state = 'running'\n  AND fence = CAST(? AS INTEGER) AND lease_owner = ? AND cursor = CAST(? AS INTEGER) AND lease_until > CAST(? AS INTEGER)) THEN 1 ELSE 0 END;",
        params: [
          { kind: "text", nullable: false },
          { kind: "scope", nullable: false },
          { kind: "text", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "text", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "int64", nullable: false },
        ],
        returns: null,
      },
      {
        sql: "INSERT INTO probe_job_item (scope, job_id, item_no, amount)\nSELECT ?, ?, CAST(json_extract(value, '$.n') AS INTEGER), CAST(json_extract(value, '$.a') AS INTEGER) FROM json_each(?);",
        params: [
          { kind: "scope", nullable: false },
          { kind: "text", nullable: false },
          { kind: "text", nullable: false },
        ],
        returns: null,
      },
      {
        sql: "UPDATE probe_job SET cursor = CAST(? AS INTEGER), checksum = ?,\n  state = CASE WHEN CAST(? AS INTEGER) >= total THEN 'complete' ELSE 'running' END, revision = revision + 1,\n  lease_owner = NULL, lease_until = NULL\nWHERE scope = ? AND job_id = ? AND fence = CAST(? AS INTEGER);",
        params: [
          { kind: "int64", nullable: false },
          { kind: "uint64", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "scope", nullable: false },
          { kind: "text", nullable: false },
          { kind: "int64", nullable: false },
        ],
        returns: null,
      },
      {
        sql: "INSERT INTO probe_inbox (scope, consumer, event_id, generation) VALUES (?, 'job-slice', ?, CAST(? AS INTEGER));",
        params: [
          { kind: "scope", nullable: false },
          { kind: "text", nullable: false },
          { kind: "int64", nullable: false },
        ],
        returns: null,
      },
      {
        sql: "INSERT INTO probe_outbox (scope, command_id, event_key, payload_json) VALUES (?, ?, ?, ?);",
        params: [
          { kind: "scope", nullable: false },
          { kind: "text", nullable: false },
          { kind: "text", nullable: false },
          { kind: "text", nullable: false },
        ],
        returns: null,
      },
      {
        sql: "DELETE FROM probe_guard WHERE command_id = ?;",
        params: [{ kind: "text", nullable: false }],
        returns: null,
      },
    ],
  },
  {
    id: "foundation.job-items",
    version: 1,
    access: "read",
    maxRows: 1,
    statements: [
      {
        sql: "SELECT CAST(COUNT(*) AS TEXT), CAST(COALESCE(SUM(amount), 0) AS TEXT) FROM probe_job_item WHERE scope = ? AND job_id = ?;",
        params: [
          { kind: "scope", nullable: false },
          { kind: "text", nullable: false },
        ],
        returns: [
          { kind: "int64", nullable: false },
          { kind: "int64", nullable: false },
        ],
      },
    ],
  },
  {
    id: "foundation.job-load",
    version: 1,
    access: "read",
    maxRows: 1,
    statements: [
      {
        sql: "SELECT CAST(total AS TEXT), CAST(cursor AS TEXT), CAST(fence AS TEXT), lease_owner, CAST(lease_until AS TEXT), state, checksum, CAST(revision AS TEXT)\nFROM probe_job WHERE scope = ? AND job_id = ?;",
        params: [
          { kind: "scope", nullable: false },
          { kind: "text", nullable: false },
        ],
        returns: [
          { kind: "int64", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "text", nullable: true },
          { kind: "int64", nullable: true },
          { kind: "text", nullable: false },
          { kind: "uint64", nullable: false },
          { kind: "int64", nullable: false },
        ],
      },
    ],
  },
  {
    id: "foundation.job-start",
    version: 1,
    access: "write",
    maxRows: 0,
    statements: [
      {
        sql: "INSERT INTO probe_job (scope, job_id, total, cursor, fence, lease_owner, lease_until, state, checksum, revision)\nVALUES (?, ?, CAST(? AS INTEGER), 0, 0, NULL, NULL, 'running', '0', 1);",
        params: [
          { kind: "scope", nullable: false },
          { kind: "text", nullable: false },
          { kind: "int64", nullable: false },
        ],
        returns: null,
      },
      {
        sql: "INSERT INTO probe_outbox (scope, command_id, event_key, payload_json) VALUES (?, ?, ?, ?);",
        params: [
          { kind: "scope", nullable: false },
          { kind: "text", nullable: false },
          { kind: "text", nullable: false },
          { kind: "text", nullable: false },
        ],
        returns: null,
      },
    ],
  },
  {
    id: "foundation.outbox-state",
    version: 1,
    access: "read",
    maxRows: 1,
    statements: [
      {
        sql: "SELECT CAST(COUNT(*) AS TEXT), CAST(COALESCE(MAX(sequence), 0) AS TEXT) FROM probe_outbox WHERE scope = ?;",
        params: [{ kind: "scope", nullable: false }],
        returns: [
          { kind: "int64", nullable: false },
          { kind: "int64", nullable: false },
        ],
      },
    ],
  },
  {
    id: "foundation.readiness",
    version: 1,
    access: "read",
    maxRows: 1,
    statements: [
      {
        sql: "SELECT CAST(version AS TEXT) FROM probe_schema;",
        params: [],
        returns: [{ kind: "int64", nullable: false }],
      },
    ],
  },
  {
    id: "foundation.receipt-load",
    version: 1,
    access: "read",
    maxRows: 1,
    statements: [
      {
        sql: "SELECT request_hash, result_json FROM probe_receipt WHERE scope = ? AND command_id = ?;",
        params: [
          { kind: "scope", nullable: false },
          { kind: "text", nullable: false },
        ],
        returns: [
          { kind: "text", nullable: false },
          { kind: "text", nullable: false },
        ],
      },
    ],
  },
  {
    id: "foundation.session-create",
    version: 1,
    access: "write",
    maxRows: 0,
    statements: [
      {
        sql: "INSERT INTO probe_session (scope, session_id, handle_hash, user_id, device_id, workspace_ids_json, recovery_generation, auth_epoch,\n  created_at, absolute_expires_at, idle_expires_at, last_seen_at, revoked_at, revoke_reason)\nVALUES (?, ?, ?, ?, ?, ?, CAST(? AS INTEGER), CAST(? AS INTEGER), CAST(? AS INTEGER), CAST(? AS INTEGER), CAST(? AS INTEGER), CAST(? AS INTEGER), NULL, NULL);",
        params: [
          { kind: "scope", nullable: false },
          { kind: "text", nullable: false },
          { kind: "bytes", nullable: false },
          { kind: "text", nullable: false },
          { kind: "text", nullable: false },
          { kind: "text", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "int64", nullable: false },
        ],
        returns: null,
      },
      {
        sql: "INSERT INTO probe_outbox (scope, command_id, event_key, payload_json) VALUES (?, ?, ?, ?);",
        params: [
          { kind: "scope", nullable: false },
          { kind: "text", nullable: false },
          { kind: "text", nullable: false },
          { kind: "text", nullable: false },
        ],
        returns: null,
      },
    ],
  },
  {
    id: "foundation.session-load",
    version: 1,
    access: "read",
    maxRows: 1,
    statements: [
      {
        sql: "SELECT session_id, user_id, device_id, workspace_ids_json, CAST(recovery_generation AS TEXT), CAST(auth_epoch AS TEXT),\n  CAST(created_at AS TEXT), CAST(absolute_expires_at AS TEXT), CAST(idle_expires_at AS TEXT), CAST(last_seen_at AS TEXT),\n  CAST(revoked_at AS TEXT), revoke_reason\nFROM probe_session WHERE scope = ? AND handle_hash = ?;",
        params: [
          { kind: "scope", nullable: false },
          { kind: "bytes", nullable: false },
        ],
        returns: [
          { kind: "text", nullable: false },
          { kind: "text", nullable: false },
          { kind: "text", nullable: false },
          { kind: "text", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "int64", nullable: true },
          { kind: "text", nullable: true },
        ],
      },
    ],
  },
  {
    id: "foundation.session-load-by-id",
    version: 1,
    access: "read",
    maxRows: 1,
    statements: [
      {
        sql: "SELECT session_id, user_id, device_id, workspace_ids_json, CAST(recovery_generation AS TEXT), CAST(auth_epoch AS TEXT),\n  CAST(created_at AS TEXT), CAST(absolute_expires_at AS TEXT), CAST(idle_expires_at AS TEXT), CAST(last_seen_at AS TEXT),\n  CAST(revoked_at AS TEXT), revoke_reason\nFROM probe_session WHERE scope = ? AND session_id = ?;",
        params: [
          { kind: "scope", nullable: false },
          { kind: "text", nullable: false },
        ],
        returns: [
          { kind: "text", nullable: false },
          { kind: "text", nullable: false },
          { kind: "text", nullable: false },
          { kind: "text", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "int64", nullable: true },
          { kind: "text", nullable: true },
        ],
      },
    ],
  },
  {
    id: "foundation.session-revoke",
    version: 1,
    access: "write",
    maxRows: 0,
    statements: [
      {
        sql: "INSERT INTO probe_guard (command_id, allowed)\nSELECT ?, CASE WHEN EXISTS (SELECT 1 FROM probe_session WHERE scope = ? AND session_id = ? AND revoked_at IS NULL) THEN 1 ELSE 0 END;",
        params: [
          { kind: "text", nullable: false },
          { kind: "scope", nullable: false },
          { kind: "text", nullable: false },
        ],
        returns: null,
      },
      {
        sql: "UPDATE probe_session SET revoked_at = CAST(? AS INTEGER), revoke_reason = ?\nWHERE scope = ? AND session_id = ? AND revoked_at IS NULL;",
        params: [
          { kind: "int64", nullable: false },
          { kind: "text", nullable: false },
          { kind: "scope", nullable: false },
          { kind: "text", nullable: false },
        ],
        returns: null,
      },
      {
        sql: "INSERT INTO probe_outbox (scope, command_id, event_key, payload_json) VALUES (?, ?, ?, ?);",
        params: [
          { kind: "scope", nullable: false },
          { kind: "text", nullable: false },
          { kind: "text", nullable: false },
          { kind: "text", nullable: false },
        ],
        returns: null,
      },
      {
        sql: "DELETE FROM probe_guard WHERE command_id = ?;",
        params: [{ kind: "text", nullable: false }],
        returns: null,
      },
    ],
  },
  {
    id: "foundation.session-touch",
    version: 1,
    access: "write",
    maxRows: 0,
    statements: [
      {
        sql: "UPDATE probe_session SET last_seen_at = CAST(? AS INTEGER), idle_expires_at = CAST(? AS INTEGER)\nWHERE scope = ? AND handle_hash = ? AND revoked_at IS NULL\n  AND idle_expires_at > CAST(? AS INTEGER) AND absolute_expires_at > CAST(? AS INTEGER);",
        params: [
          { kind: "int64", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "scope", nullable: false },
          { kind: "bytes", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "int64", nullable: false },
        ],
        returns: null,
      },
    ],
  },
  {
    id: "foundation.transfer",
    version: 1,
    access: "write",
    maxRows: 0,
    statements: [
      {
        sql: "INSERT INTO probe_guard (command_id, allowed)\nSELECT ?, CASE WHEN\n  EXISTS (SELECT 1 FROM probe_account WHERE scope = ? AND id = ? AND revision = CAST(? AS INTEGER) AND balance >= CAST(? AS INTEGER))\n  AND EXISTS (SELECT 1 FROM probe_account WHERE scope = ? AND id = ? AND revision = CAST(? AS INTEGER))\nTHEN 1 ELSE 0 END;",
        params: [
          { kind: "text", nullable: false },
          { kind: "scope", nullable: false },
          { kind: "text", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "scope", nullable: false },
          { kind: "text", nullable: false },
          { kind: "int64", nullable: false },
        ],
        returns: null,
      },
      {
        sql: "UPDATE probe_account SET balance = balance - CAST(? AS INTEGER), revision = revision + 1\nWHERE scope = ? AND id = ? AND revision = CAST(? AS INTEGER);",
        params: [
          { kind: "int64", nullable: false },
          { kind: "scope", nullable: false },
          { kind: "text", nullable: false },
          { kind: "int64", nullable: false },
        ],
        returns: null,
      },
      {
        sql: "UPDATE probe_account SET balance = balance + CAST(? AS INTEGER), revision = revision + 1\nWHERE scope = ? AND id = ? AND revision = CAST(? AS INTEGER);",
        params: [
          { kind: "int64", nullable: false },
          { kind: "scope", nullable: false },
          { kind: "text", nullable: false },
          { kind: "int64", nullable: false },
        ],
        returns: null,
      },
      {
        sql: "INSERT INTO probe_receipt (scope, command_id, request_hash, result_json) VALUES (?, ?, ?, ?);",
        params: [
          { kind: "scope", nullable: false },
          { kind: "text", nullable: false },
          { kind: "text", nullable: false },
          { kind: "text", nullable: false },
        ],
        returns: null,
      },
      {
        sql: "INSERT INTO probe_outbox (scope, command_id, event_key, payload_json) VALUES (?, ?, ?, ?);",
        params: [
          { kind: "scope", nullable: false },
          { kind: "text", nullable: false },
          { kind: "text", nullable: false },
          { kind: "text", nullable: false },
        ],
        returns: null,
      },
      {
        sql: "DELETE FROM probe_guard WHERE command_id = ?;",
        params: [{ kind: "text", nullable: false }],
        returns: null,
      },
    ],
  },
  {
    id: "platform.archive-ack",
    version: 1,
    access: "write",
    maxRows: 0,
    statements: [
      {
        sql: "INSERT INTO platform_command_guard (command_id, guard_key, allowed)\nSELECT ?, 'platform.archive-ack', CASE WHEN\n  EXISTS (SELECT 1 FROM platform_sequence_stream WHERE stream_key = 'platform:change-archive' AND published_watermark = CAST(? AS INTEGER) AND publish_rev = CAST(? AS INTEGER) AND fence = CAST(? AS INTEGER) AND last_sequence >= CAST(? AS INTEGER))\n  AND (SELECT COUNT(*) FROM platform_change_archive WHERE archive_sequence > CAST(? AS INTEGER) AND archive_sequence <= CAST(? AS INTEGER)) = CAST(? AS INTEGER)\nTHEN 1 ELSE 0 END;",
        params: [
          { kind: "text", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "int64", nullable: false },
        ],
        returns: null,
      },
      {
        sql: "UPDATE platform_sequence_stream SET published_watermark = CAST(? AS INTEGER), publish_rev = publish_rev + 1, ack_receipt = ?, updated_at = CAST(? AS INTEGER)\nWHERE stream_key = 'platform:change-archive' AND published_watermark = CAST(? AS INTEGER) AND publish_rev = CAST(? AS INTEGER) AND fence = CAST(? AS INTEGER);",
        params: [
          { kind: "int64", nullable: false },
          { kind: "text", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "int64", nullable: false },
        ],
        returns: null,
      },
      {
        sql: "DELETE FROM platform_command_guard WHERE command_id = ?;",
        params: [{ kind: "text", nullable: false }],
        returns: null,
      },
    ],
  },
  {
    id: "platform.archive-purge",
    version: 1,
    access: "write",
    maxRows: 0,
    statements: [
      {
        sql: "INSERT INTO platform_command_guard (command_id, guard_key, allowed)\nSELECT ?, 'platform.archive-purge', CASE WHEN EXISTS (SELECT 1 FROM platform_sequence_stream WHERE stream_key = 'platform:change-archive' AND published_watermark >= CAST(? AS INTEGER)) THEN 1 ELSE 0 END;",
        params: [
          { kind: "text", nullable: false },
          { kind: "int64", nullable: false },
        ],
        returns: null,
      },
      {
        sql: "DELETE FROM platform_change_archive WHERE archive_sequence <= MIN(CAST(? AS INTEGER), COALESCE((SELECT published_watermark FROM platform_sequence_stream WHERE stream_key = 'platform:change-archive'), 0)) AND created_at < CAST(? AS INTEGER);",
        params: [
          { kind: "int64", nullable: false },
          { kind: "int64", nullable: false },
        ],
        returns: null,
      },
      {
        sql: "DELETE FROM platform_command_guard WHERE command_id = ?;",
        params: [{ kind: "text", nullable: false }],
        returns: null,
      },
    ],
  },
  {
    id: "platform.archive-select",
    version: 1,
    access: "read",
    maxRows: 100,
    statements: [
      {
        sql: "SELECT CAST(archive_sequence AS TEXT), command_id, CAST(schema_version AS TEXT), record, record_hash, CAST(created_at AS TEXT)\nFROM (\n  SELECT archive_sequence, command_id, schema_version, record, record_hash, created_at,\n    SUM(length(CAST(record AS BLOB))) OVER (ORDER BY archive_sequence) AS running_bytes\n  FROM platform_change_archive\n  WHERE archive_sequence > CAST(? AS INTEGER) AND archive_sequence <= CAST(? AS INTEGER)\n)\nWHERE running_bytes <= 98304 ORDER BY archive_sequence;",
        params: [
          { kind: "int64", nullable: false },
          { kind: "int64", nullable: false },
        ],
        returns: [
          { kind: "int64", nullable: false },
          { kind: "text", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "text", nullable: false },
          { kind: "bytes", nullable: false },
          { kind: "int64", nullable: false },
        ],
      },
    ],
  },
  {
    id: "platform.archive-state",
    version: 1,
    access: "read",
    maxRows: 1,
    statements: [
      {
        sql: "SELECT CAST(last_sequence AS TEXT), CAST(published_watermark AS TEXT), CAST(publish_rev AS TEXT), CAST(fence AS TEXT), ack_receipt\nFROM platform_sequence_stream WHERE stream_key = 'platform:change-archive';",
        params: [],
        returns: [
          { kind: "int64", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "text", nullable: true },
        ],
      },
    ],
  },
  {
    id: "platform.command-load",
    version: 1,
    access: "read",
    maxRows: 1,
    statements: [
      {
        sql: "SELECT request_hash, CAST(status AS TEXT), result_payload, CAST(result_rev AS TEXT), error_code, CAST(expires_at AS TEXT), actor_ref, operation, workspace_id\nFROM platform_command WHERE command_id = ?;",
        params: [{ kind: "text", nullable: false }],
        returns: [
          { kind: "text", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "text", nullable: true },
          { kind: "int64", nullable: true },
          { kind: "text", nullable: true },
          { kind: "int64", nullable: false },
          { kind: "text", nullable: false },
          { kind: "text", nullable: false },
          { kind: "text", nullable: true },
        ],
      },
    ],
  },
  {
    id: "platform.command-record-failure",
    version: 1,
    access: "write",
    maxRows: 0,
    statements: [
      {
        sql: "INSERT INTO platform_command (command_id, workspace_id, actor_ref, operation, request_hash, status, result_payload, result_rev, error_code, created_at, expires_at)\nVALUES (?, ?, ?, ?, ?, 3, NULL, NULL, ?, CAST(? AS INTEGER), CAST(? AS INTEGER));",
        params: [
          { kind: "text", nullable: false },
          { kind: "text", nullable: true },
          { kind: "text", nullable: false },
          { kind: "text", nullable: false },
          { kind: "text", nullable: false },
          { kind: "text", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "int64", nullable: false },
        ],
        returns: null,
      },
    ],
  },
  {
    id: "platform.inbox-load",
    version: 1,
    access: "read",
    maxRows: 1,
    statements: [
      {
        sql: "SELECT CAST(outcome AS TEXT), CAST(processed_at AS TEXT) FROM platform_inbox WHERE source = ? AND message_id = ?;",
        params: [
          { kind: "text", nullable: false },
          { kind: "text", nullable: false },
        ],
        returns: [
          { kind: "int64", nullable: true },
          { kind: "int64", nullable: true },
        ],
      },
    ],
  },
  {
    id: "platform.inbox-record",
    version: 1,
    access: "write",
    maxRows: 0,
    statements: [
      {
        sql: "INSERT INTO platform_inbox (source, message_id, received_at, processed_at, outcome, expires_at)\nVALUES (?, ?, CAST(? AS INTEGER), CAST(? AS INTEGER), CAST(? AS INTEGER), CAST(? AS INTEGER));",
        params: [
          { kind: "text", nullable: false },
          { kind: "text", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "int64", nullable: false },
        ],
        returns: null,
      },
    ],
  },
  {
    id: "platform.outbox-ack",
    version: 1,
    access: "write",
    maxRows: 0,
    statements: [
      {
        sql: "INSERT INTO platform_command_guard (command_id, guard_key, allowed)\nSELECT ?, 'platform.outbox-ack', CASE WHEN\n  EXISTS (SELECT 1 FROM platform_sequence_stream WHERE stream_key = ? AND published_watermark = CAST(? AS INTEGER) AND publish_rev = CAST(? AS INTEGER) AND fence = CAST(? AS INTEGER) AND last_sequence >= CAST(? AS INTEGER))\n  AND (SELECT COUNT(*) FROM platform_outbox_position p JOIN platform_outbox o ON o.outbox_id = p.outbox_id WHERE p.stream_key = ? AND p.sequence > CAST(? AS INTEGER) AND p.sequence <= CAST(? AS INTEGER) AND o.state = 1) = CAST(? AS INTEGER)\nTHEN 1 ELSE 0 END;",
        params: [
          { kind: "text", nullable: false },
          { kind: "scope", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "scope", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "int64", nullable: false },
        ],
        returns: null,
      },
      {
        sql: "UPDATE platform_outbox SET state = 2, dispatched_at = CAST(? AS INTEGER)\nWHERE state = 1 AND outbox_id IN (SELECT outbox_id FROM platform_outbox_position WHERE stream_key = ? AND sequence > CAST(? AS INTEGER) AND sequence <= CAST(? AS INTEGER));",
        params: [
          { kind: "int64", nullable: false },
          { kind: "scope", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "int64", nullable: false },
        ],
        returns: null,
      },
      {
        sql: "UPDATE platform_sequence_stream SET published_watermark = CAST(? AS INTEGER), publish_rev = publish_rev + 1, ack_receipt = ?, updated_at = CAST(? AS INTEGER)\nWHERE stream_key = ? AND published_watermark = CAST(? AS INTEGER) AND publish_rev = CAST(? AS INTEGER) AND fence = CAST(? AS INTEGER);",
        params: [
          { kind: "int64", nullable: false },
          { kind: "text", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "scope", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "int64", nullable: false },
        ],
        returns: null,
      },
      {
        sql: "DELETE FROM platform_command_guard WHERE command_id = ?;",
        params: [{ kind: "text", nullable: false }],
        returns: null,
      },
    ],
  },
  {
    id: "platform.outbox-attempt",
    version: 1,
    access: "write",
    maxRows: 0,
    statements: [
      {
        sql: "INSERT INTO platform_command_guard (command_id, guard_key, allowed)\nSELECT ?, 'platform.outbox-attempt', CASE WHEN EXISTS (\n  SELECT 1 FROM platform_outbox o JOIN platform_outbox_position p ON p.outbox_id = o.outbox_id JOIN platform_sequence_stream s ON s.stream_key = p.stream_key\n  WHERE o.outbox_id = ? AND p.stream_key = ? AND o.state = 1 AND o.attempts = CAST(? AS INTEGER) AND s.fence = CAST(? AS INTEGER)\n) THEN 1 ELSE 0 END;",
        params: [
          { kind: "text", nullable: false },
          { kind: "text", nullable: false },
          { kind: "scope", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "int64", nullable: false },
        ],
        returns: null,
      },
      {
        sql: "UPDATE platform_outbox SET attempts = attempts + 1 WHERE outbox_id = ? AND state = 1 AND attempts = CAST(? AS INTEGER);",
        params: [
          { kind: "text", nullable: false },
          { kind: "int64", nullable: false },
        ],
        returns: null,
      },
      {
        sql: "DELETE FROM platform_command_guard WHERE command_id = ?;",
        params: [{ kind: "text", nullable: false }],
        returns: null,
      },
    ],
  },
  {
    id: "platform.outbox-dead-letter",
    version: 1,
    access: "write",
    maxRows: 0,
    statements: [
      {
        sql: "INSERT INTO platform_command_guard (command_id, guard_key, allowed)\nSELECT ?, 'platform.outbox-dead-letter', CASE WHEN EXISTS (\n  SELECT 1 FROM platform_outbox o JOIN platform_outbox_position p ON p.outbox_id = o.outbox_id JOIN platform_sequence_stream s ON s.stream_key = p.stream_key\n  WHERE o.outbox_id = ? AND p.stream_key = ? AND o.state = 1 AND o.attempts = CAST(? AS INTEGER) AND s.fence = CAST(? AS INTEGER)\n) THEN 1 ELSE 0 END;",
        params: [
          { kind: "text", nullable: false },
          { kind: "text", nullable: false },
          { kind: "scope", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "int64", nullable: false },
        ],
        returns: null,
      },
      {
        sql: "UPDATE platform_outbox SET state = 3 WHERE outbox_id = ? AND state = 1 AND attempts = CAST(? AS INTEGER);",
        params: [
          { kind: "text", nullable: false },
          { kind: "int64", nullable: false },
        ],
        returns: null,
      },
      {
        sql: "DELETE FROM platform_command_guard WHERE command_id = ?;",
        params: [{ kind: "text", nullable: false }],
        returns: null,
      },
    ],
  },
  {
    id: "platform.outbox-purge",
    version: 1,
    access: "write",
    maxRows: 0,
    statements: [
      {
        sql: "INSERT INTO platform_command_guard (command_id, guard_key, allowed)\nSELECT ?, 'platform.outbox-purge', CASE WHEN EXISTS (SELECT 1 FROM platform_sequence_stream WHERE stream_key = ? AND published_watermark >= CAST(? AS INTEGER)) THEN 1 ELSE 0 END;",
        params: [
          { kind: "text", nullable: false },
          { kind: "scope", nullable: false },
          { kind: "int64", nullable: false },
        ],
        returns: null,
      },
      {
        sql: "DELETE FROM platform_outbox_position WHERE stream_key = ? AND sequence <= MIN(CAST(? AS INTEGER), COALESCE((SELECT published_watermark FROM platform_sequence_stream WHERE stream_key = ?), 0)) AND outbox_id IN (SELECT outbox_id FROM platform_outbox WHERE state = 2 AND created_at < CAST(? AS INTEGER));",
        params: [
          { kind: "scope", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "scope", nullable: false },
          { kind: "int64", nullable: false },
        ],
        returns: null,
      },
      {
        sql: "DELETE FROM platform_outbox WHERE state = 2 AND created_at < CAST(? AS INTEGER) AND outbox_id NOT IN (SELECT outbox_id FROM platform_outbox_position);",
        params: [{ kind: "int64", nullable: false }],
        returns: null,
      },
      {
        sql: "DELETE FROM platform_command_guard WHERE command_id = ?;",
        params: [{ kind: "text", nullable: false }],
        returns: null,
      },
    ],
  },
  {
    id: "platform.outbox-requeue",
    version: 1,
    access: "write",
    maxRows: 0,
    statements: [
      {
        sql: "INSERT INTO platform_command_guard (command_id, guard_key, allowed)\nSELECT ?, 'platform.outbox-requeue', CASE WHEN EXISTS (\n  SELECT 1 FROM platform_outbox o JOIN platform_outbox_position p ON p.outbox_id = o.outbox_id JOIN platform_sequence_stream s ON s.stream_key = p.stream_key\n  WHERE o.outbox_id = ? AND p.stream_key = ? AND o.state = 3 AND s.fence = CAST(? AS INTEGER)\n) THEN 1 ELSE 0 END;",
        params: [
          { kind: "text", nullable: false },
          { kind: "text", nullable: false },
          { kind: "scope", nullable: false },
          { kind: "int64", nullable: false },
        ],
        returns: null,
      },
      {
        sql: "UPDATE platform_outbox SET state = 1, attempts = 0 WHERE outbox_id = ? AND state = 3;",
        params: [{ kind: "text", nullable: false }],
        returns: null,
      },
      {
        sql: "DELETE FROM platform_command_guard WHERE command_id = ?;",
        params: [{ kind: "text", nullable: false }],
        returns: null,
      },
    ],
  },
  {
    id: "platform.outbox-select",
    version: 1,
    access: "read",
    maxRows: 50,
    statements: [
      {
        sql: "SELECT CAST(sequence AS TEXT), outbox_id, aggregate_kind, aggregate_id, CAST(aggregate_rev AS TEXT), event_type, payload, workspace_id, correlation_id, causation_id, CAST(state AS TEXT), CAST(attempts AS TEXT), CAST(created_at AS TEXT)\nFROM (\n  SELECT p.sequence AS sequence, o.outbox_id AS outbox_id, o.aggregate_kind AS aggregate_kind, o.aggregate_id AS aggregate_id, o.aggregate_rev AS aggregate_rev, o.event_type AS event_type, o.payload AS payload, o.workspace_id AS workspace_id, o.correlation_id AS correlation_id, o.causation_id AS causation_id, o.state AS state, o.attempts AS attempts, o.created_at AS created_at,\n    SUM(length(CAST(o.payload AS BLOB))) OVER (ORDER BY p.sequence) AS running_bytes\n  FROM platform_outbox_position p JOIN platform_outbox o ON o.outbox_id = p.outbox_id\n  WHERE p.stream_key = ? AND p.sequence > CAST(? AS INTEGER) AND p.sequence <= CAST(? AS INTEGER)\n)\nWHERE running_bytes <= 65536 ORDER BY sequence;",
        params: [
          { kind: "scope", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "int64", nullable: false },
        ],
        returns: [
          { kind: "int64", nullable: false },
          { kind: "text", nullable: false },
          { kind: "text", nullable: false },
          { kind: "text", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "text", nullable: false },
          { kind: "text", nullable: false },
          { kind: "text", nullable: true },
          { kind: "text", nullable: false },
          { kind: "text", nullable: true },
          { kind: "int64", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "int64", nullable: false },
        ],
      },
    ],
  },
  {
    id: "platform.stream-fence",
    version: 1,
    access: "write",
    maxRows: 0,
    statements: [
      {
        sql: "INSERT INTO platform_command_guard (command_id, guard_key, allowed)\nSELECT ?, 'platform.stream-fence', CASE WHEN EXISTS (SELECT 1 FROM platform_sequence_stream WHERE stream_key = ? AND fence = CAST(? AS INTEGER)) THEN 1 ELSE 0 END;",
        params: [
          { kind: "text", nullable: false },
          { kind: "scope", nullable: false },
          { kind: "int64", nullable: false },
        ],
        returns: null,
      },
      {
        sql: "UPDATE platform_sequence_stream SET fence = fence + 1, publish_rev = publish_rev + 1, updated_at = CAST(? AS INTEGER)\nWHERE stream_key = ? AND fence = CAST(? AS INTEGER);",
        params: [
          { kind: "int64", nullable: false },
          { kind: "scope", nullable: false },
          { kind: "int64", nullable: false },
        ],
        returns: null,
      },
      {
        sql: "DELETE FROM platform_command_guard WHERE command_id = ?;",
        params: [{ kind: "text", nullable: false }],
        returns: null,
      },
    ],
  },
  {
    id: "platform.stream-load",
    version: 1,
    access: "read",
    maxRows: 1,
    statements: [
      {
        sql: "SELECT CAST(last_sequence AS TEXT), CAST(published_watermark AS TEXT), CAST(publish_rev AS TEXT), CAST(fence AS TEXT), ack_receipt\nFROM platform_sequence_stream WHERE stream_key = ?;",
        params: [{ kind: "scope", nullable: false }],
        returns: [
          { kind: "int64", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "text", nullable: true },
        ],
      },
    ],
  },
];
