// SPDX-License-Identifier: AGPL-3.0-only
// <auto-generated />
// Generated by eng/verification/storage-plans.ts from the reviewed plan files; do not edit.
import type { PlanDefinition } from "./plan-types.ts";

export const manifestHash = "3716534cb8f64bea85f02c18a6f07281f0703b64115f0087ec73a405dd3bc7d7";

export const plans: readonly PlanDefinition[] = [
  {
    id: "foundation.account-load",
    version: 1,
    access: "read",
    maxRows: 1,
    statements: [
      {
        sql: "SELECT CAST(balance AS TEXT), CAST(revision AS TEXT) FROM probe_account WHERE scope = ? AND id = ?;",
        params: [
          { kind: "scope", nullable: false },
          { kind: "text", nullable: false },
        ],
        returns: [
          { kind: "int64", nullable: false },
          { kind: "int64", nullable: false },
        ],
      },
    ],
  },
  {
    id: "foundation.account-seed",
    version: 1,
    access: "write",
    maxRows: 0,
    statements: [
      {
        sql: "INSERT INTO probe_account (scope, id, balance, revision) VALUES (?, ?, CAST(? AS INTEGER), 1)\nON CONFLICT (scope, id) DO NOTHING;",
        params: [
          { kind: "scope", nullable: false },
          { kind: "text", nullable: false },
          { kind: "int64", nullable: false },
        ],
        returns: null,
      },
    ],
  },
  {
    id: "foundation.exact-load",
    version: 1,
    access: "read",
    maxRows: 1,
    statements: [
      {
        sql: "SELECT CAST(signed_value AS TEXT), unsigned_text, decimal_text, payload, CAST(revision AS TEXT)\nFROM probe_exact WHERE scope = ? AND id = ?;",
        params: [
          { kind: "scope", nullable: false },
          { kind: "text", nullable: false },
        ],
        returns: [
          { kind: "int64", nullable: false },
          { kind: "uint64", nullable: false },
          { kind: "decimal", nullable: false },
          { kind: "bytes", nullable: true },
          { kind: "int64", nullable: false },
        ],
      },
    ],
  },
  {
    id: "foundation.exact-store",
    version: 1,
    access: "write",
    maxRows: 0,
    statements: [
      {
        sql: "INSERT INTO probe_guard (command_id, allowed)\nSELECT ?, CASE WHEN COALESCE((SELECT revision FROM probe_exact WHERE scope = ? AND id = ?), 0) = CAST(? AS INTEGER) THEN 1 ELSE 0 END;",
        params: [
          { kind: "text", nullable: false },
          { kind: "scope", nullable: false },
          { kind: "text", nullable: false },
          { kind: "int64", nullable: false },
        ],
        returns: null,
      },
      {
        sql: "INSERT INTO probe_exact (scope, id, signed_value, unsigned_text, decimal_text, payload, revision)\nVALUES (?, ?, CAST(? AS INTEGER), ?, ?, ?, CAST(? AS INTEGER) + 1)\nON CONFLICT (scope, id) DO UPDATE SET signed_value = excluded.signed_value, unsigned_text = excluded.unsigned_text,\n  decimal_text = excluded.decimal_text, payload = excluded.payload, revision = excluded.revision;",
        params: [
          { kind: "scope", nullable: false },
          { kind: "text", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "uint64", nullable: false },
          { kind: "decimal", nullable: false },
          { kind: "bytes", nullable: true },
          { kind: "int64", nullable: false },
        ],
        returns: null,
      },
      {
        sql: "INSERT INTO probe_receipt (scope, command_id, request_hash, result_json) VALUES (?, ?, ?, ?);",
        params: [
          { kind: "scope", nullable: false },
          { kind: "text", nullable: false },
          { kind: "text", nullable: false },
          { kind: "text", nullable: false },
        ],
        returns: null,
      },
      {
        sql: "DELETE FROM probe_guard WHERE command_id = ?;",
        params: [{ kind: "text", nullable: false }],
        returns: null,
      },
    ],
  },
  {
    id: "foundation.inbox-seen",
    version: 1,
    access: "read",
    maxRows: 1,
    statements: [
      {
        sql: "SELECT CAST(COUNT(*) AS TEXT) FROM probe_inbox WHERE scope = ? AND consumer = 'job-slice' AND event_id = ? AND generation = CAST(? AS INTEGER);",
        params: [
          { kind: "scope", nullable: false },
          { kind: "text", nullable: false },
          { kind: "int64", nullable: false },
        ],
        returns: [{ kind: "int64", nullable: false }],
      },
    ],
  },
  {
    id: "foundation.job-claim",
    version: 1,
    access: "write",
    maxRows: 0,
    statements: [
      {
        sql: "INSERT INTO probe_guard (command_id, allowed)\nSELECT ?, CASE WHEN EXISTS (SELECT 1 FROM probe_job WHERE scope = ? AND job_id = ? AND state = 'running'\n  AND (lease_owner IS NULL OR lease_until <= CAST(? AS INTEGER) OR lease_owner = ?)) THEN 1 ELSE 0 END;",
        params: [
          { kind: "text", nullable: false },
          { kind: "scope", nullable: false },
          { kind: "text", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "text", nullable: false },
        ],
        returns: null,
      },
      {
        sql: "UPDATE probe_job SET lease_owner = ?, lease_until = CAST(? AS INTEGER), fence = fence + 1 WHERE scope = ? AND job_id = ?;",
        params: [
          { kind: "text", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "scope", nullable: false },
          { kind: "text", nullable: false },
        ],
        returns: null,
      },
      {
        sql: "DELETE FROM probe_guard WHERE command_id = ?;",
        params: [{ kind: "text", nullable: false }],
        returns: null,
      },
    ],
  },
  {
    id: "foundation.job-commit",
    version: 1,
    access: "write",
    maxRows: 0,
    statements: [
      {
        sql: "INSERT INTO probe_guard (command_id, allowed)\nSELECT ?, CASE WHEN EXISTS (SELECT 1 FROM probe_job WHERE scope = ? AND job_id = ? AND state = 'running'\n  AND fence = CAST(? AS INTEGER) AND lease_owner = ? AND cursor = CAST(? AS INTEGER) AND lease_until > CAST(? AS INTEGER)) THEN 1 ELSE 0 END;",
        params: [
          { kind: "text", nullable: false },
          { kind: "scope", nullable: false },
          { kind: "text", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "text", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "int64", nullable: false },
        ],
        returns: null,
      },
      {
        sql: "INSERT INTO probe_job_item (scope, job_id, item_no, amount)\nSELECT ?, ?, CAST(json_extract(value, '$.n') AS INTEGER), CAST(json_extract(value, '$.a') AS INTEGER) FROM json_each(?);",
        params: [
          { kind: "scope", nullable: false },
          { kind: "text", nullable: false },
          { kind: "text", nullable: false },
        ],
        returns: null,
      },
      {
        sql: "UPDATE probe_job SET cursor = CAST(? AS INTEGER), checksum = ?,\n  state = CASE WHEN CAST(? AS INTEGER) >= total THEN 'complete' ELSE 'running' END, revision = revision + 1,\n  lease_owner = NULL, lease_until = NULL\nWHERE scope = ? AND job_id = ? AND fence = CAST(? AS INTEGER);",
        params: [
          { kind: "int64", nullable: false },
          { kind: "uint64", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "scope", nullable: false },
          { kind: "text", nullable: false },
          { kind: "int64", nullable: false },
        ],
        returns: null,
      },
      {
        sql: "INSERT INTO probe_inbox (scope, consumer, event_id, generation) VALUES (?, 'job-slice', ?, CAST(? AS INTEGER));",
        params: [
          { kind: "scope", nullable: false },
          { kind: "text", nullable: false },
          { kind: "int64", nullable: false },
        ],
        returns: null,
      },
      {
        sql: "INSERT INTO probe_outbox (scope, command_id, event_key, payload_json) VALUES (?, ?, ?, ?);",
        params: [
          { kind: "scope", nullable: false },
          { kind: "text", nullable: false },
          { kind: "text", nullable: false },
          { kind: "text", nullable: false },
        ],
        returns: null,
      },
      {
        sql: "DELETE FROM probe_guard WHERE command_id = ?;",
        params: [{ kind: "text", nullable: false }],
        returns: null,
      },
    ],
  },
  {
    id: "foundation.job-items",
    version: 1,
    access: "read",
    maxRows: 1,
    statements: [
      {
        sql: "SELECT CAST(COUNT(*) AS TEXT), CAST(COALESCE(SUM(amount), 0) AS TEXT) FROM probe_job_item WHERE scope = ? AND job_id = ?;",
        params: [
          { kind: "scope", nullable: false },
          { kind: "text", nullable: false },
        ],
        returns: [
          { kind: "int64", nullable: false },
          { kind: "int64", nullable: false },
        ],
      },
    ],
  },
  {
    id: "foundation.job-load",
    version: 1,
    access: "read",
    maxRows: 1,
    statements: [
      {
        sql: "SELECT CAST(total AS TEXT), CAST(cursor AS TEXT), CAST(fence AS TEXT), lease_owner, CAST(lease_until AS TEXT), state, checksum, CAST(revision AS TEXT)\nFROM probe_job WHERE scope = ? AND job_id = ?;",
        params: [
          { kind: "scope", nullable: false },
          { kind: "text", nullable: false },
        ],
        returns: [
          { kind: "int64", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "text", nullable: true },
          { kind: "int64", nullable: true },
          { kind: "text", nullable: false },
          { kind: "uint64", nullable: false },
          { kind: "int64", nullable: false },
        ],
      },
    ],
  },
  {
    id: "foundation.job-start",
    version: 1,
    access: "write",
    maxRows: 0,
    statements: [
      {
        sql: "INSERT INTO probe_job (scope, job_id, total, cursor, fence, lease_owner, lease_until, state, checksum, revision)\nVALUES (?, ?, CAST(? AS INTEGER), 0, 0, NULL, NULL, 'running', '0', 1);",
        params: [
          { kind: "scope", nullable: false },
          { kind: "text", nullable: false },
          { kind: "int64", nullable: false },
        ],
        returns: null,
      },
      {
        sql: "INSERT INTO probe_outbox (scope, command_id, event_key, payload_json) VALUES (?, ?, ?, ?);",
        params: [
          { kind: "scope", nullable: false },
          { kind: "text", nullable: false },
          { kind: "text", nullable: false },
          { kind: "text", nullable: false },
        ],
        returns: null,
      },
    ],
  },
  {
    id: "foundation.outbox-state",
    version: 1,
    access: "read",
    maxRows: 1,
    statements: [
      {
        sql: "SELECT CAST(COUNT(*) AS TEXT), CAST(COALESCE(MAX(sequence), 0) AS TEXT) FROM probe_outbox WHERE scope = ?;",
        params: [{ kind: "scope", nullable: false }],
        returns: [
          { kind: "int64", nullable: false },
          { kind: "int64", nullable: false },
        ],
      },
    ],
  },
  {
    id: "foundation.readiness",
    version: 1,
    access: "read",
    maxRows: 1,
    statements: [
      {
        sql: "SELECT CAST(version AS TEXT) FROM probe_schema;",
        params: [],
        returns: [{ kind: "int64", nullable: false }],
      },
    ],
  },
  {
    id: "foundation.receipt-load",
    version: 1,
    access: "read",
    maxRows: 1,
    statements: [
      {
        sql: "SELECT request_hash, result_json FROM probe_receipt WHERE scope = ? AND command_id = ?;",
        params: [
          { kind: "scope", nullable: false },
          { kind: "text", nullable: false },
        ],
        returns: [
          { kind: "text", nullable: false },
          { kind: "text", nullable: false },
        ],
      },
    ],
  },
  {
    id: "foundation.session-create",
    version: 1,
    access: "write",
    maxRows: 0,
    statements: [
      {
        sql: "INSERT INTO probe_session (scope, session_id, handle_hash, user_id, device_id, workspace_ids_json, recovery_generation, auth_epoch,\n  created_at, absolute_expires_at, idle_expires_at, last_seen_at, revoked_at, revoke_reason)\nVALUES (?, ?, ?, ?, ?, ?, CAST(? AS INTEGER), CAST(? AS INTEGER), CAST(? AS INTEGER), CAST(? AS INTEGER), CAST(? AS INTEGER), CAST(? AS INTEGER), NULL, NULL);",
        params: [
          { kind: "scope", nullable: false },
          { kind: "text", nullable: false },
          { kind: "bytes", nullable: false },
          { kind: "text", nullable: false },
          { kind: "text", nullable: false },
          { kind: "text", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "int64", nullable: false },
        ],
        returns: null,
      },
      {
        sql: "INSERT INTO probe_outbox (scope, command_id, event_key, payload_json) VALUES (?, ?, ?, ?);",
        params: [
          { kind: "scope", nullable: false },
          { kind: "text", nullable: false },
          { kind: "text", nullable: false },
          { kind: "text", nullable: false },
        ],
        returns: null,
      },
    ],
  },
  {
    id: "foundation.session-load",
    version: 1,
    access: "read",
    maxRows: 1,
    statements: [
      {
        sql: "SELECT session_id, user_id, device_id, workspace_ids_json, CAST(recovery_generation AS TEXT), CAST(auth_epoch AS TEXT),\n  CAST(created_at AS TEXT), CAST(absolute_expires_at AS TEXT), CAST(idle_expires_at AS TEXT), CAST(last_seen_at AS TEXT),\n  CAST(revoked_at AS TEXT), revoke_reason\nFROM probe_session WHERE scope = ? AND handle_hash = ?;",
        params: [
          { kind: "scope", nullable: false },
          { kind: "bytes", nullable: false },
        ],
        returns: [
          { kind: "text", nullable: false },
          { kind: "text", nullable: false },
          { kind: "text", nullable: false },
          { kind: "text", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "int64", nullable: true },
          { kind: "text", nullable: true },
        ],
      },
    ],
  },
  {
    id: "foundation.session-load-by-id",
    version: 1,
    access: "read",
    maxRows: 1,
    statements: [
      {
        sql: "SELECT session_id, user_id, device_id, workspace_ids_json, CAST(recovery_generation AS TEXT), CAST(auth_epoch AS TEXT),\n  CAST(created_at AS TEXT), CAST(absolute_expires_at AS TEXT), CAST(idle_expires_at AS TEXT), CAST(last_seen_at AS TEXT),\n  CAST(revoked_at AS TEXT), revoke_reason\nFROM probe_session WHERE scope = ? AND session_id = ?;",
        params: [
          { kind: "scope", nullable: false },
          { kind: "text", nullable: false },
        ],
        returns: [
          { kind: "text", nullable: false },
          { kind: "text", nullable: false },
          { kind: "text", nullable: false },
          { kind: "text", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "int64", nullable: true },
          { kind: "text", nullable: true },
        ],
      },
    ],
  },
  {
    id: "foundation.session-revoke",
    version: 1,
    access: "write",
    maxRows: 0,
    statements: [
      {
        sql: "INSERT INTO probe_guard (command_id, allowed)\nSELECT ?, CASE WHEN EXISTS (SELECT 1 FROM probe_session WHERE scope = ? AND session_id = ? AND revoked_at IS NULL) THEN 1 ELSE 0 END;",
        params: [
          { kind: "text", nullable: false },
          { kind: "scope", nullable: false },
          { kind: "text", nullable: false },
        ],
        returns: null,
      },
      {
        sql: "UPDATE probe_session SET revoked_at = CAST(? AS INTEGER), revoke_reason = ?\nWHERE scope = ? AND session_id = ? AND revoked_at IS NULL;",
        params: [
          { kind: "int64", nullable: false },
          { kind: "text", nullable: false },
          { kind: "scope", nullable: false },
          { kind: "text", nullable: false },
        ],
        returns: null,
      },
      {
        sql: "INSERT INTO probe_outbox (scope, command_id, event_key, payload_json) VALUES (?, ?, ?, ?);",
        params: [
          { kind: "scope", nullable: false },
          { kind: "text", nullable: false },
          { kind: "text", nullable: false },
          { kind: "text", nullable: false },
        ],
        returns: null,
      },
      {
        sql: "DELETE FROM probe_guard WHERE command_id = ?;",
        params: [{ kind: "text", nullable: false }],
        returns: null,
      },
    ],
  },
  {
    id: "foundation.session-touch",
    version: 1,
    access: "write",
    maxRows: 0,
    statements: [
      {
        sql: "UPDATE probe_session SET last_seen_at = CAST(? AS INTEGER), idle_expires_at = CAST(? AS INTEGER)\nWHERE scope = ? AND handle_hash = ? AND revoked_at IS NULL\n  AND idle_expires_at > CAST(? AS INTEGER) AND absolute_expires_at > CAST(? AS INTEGER);",
        params: [
          { kind: "int64", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "scope", nullable: false },
          { kind: "bytes", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "int64", nullable: false },
        ],
        returns: null,
      },
    ],
  },
  {
    id: "foundation.transfer",
    version: 1,
    access: "write",
    maxRows: 0,
    statements: [
      {
        sql: "INSERT INTO probe_guard (command_id, allowed)\nSELECT ?, CASE WHEN\n  EXISTS (SELECT 1 FROM probe_account WHERE scope = ? AND id = ? AND revision = CAST(? AS INTEGER) AND balance >= CAST(? AS INTEGER))\n  AND EXISTS (SELECT 1 FROM probe_account WHERE scope = ? AND id = ? AND revision = CAST(? AS INTEGER))\nTHEN 1 ELSE 0 END;",
        params: [
          { kind: "text", nullable: false },
          { kind: "scope", nullable: false },
          { kind: "text", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "scope", nullable: false },
          { kind: "text", nullable: false },
          { kind: "int64", nullable: false },
        ],
        returns: null,
      },
      {
        sql: "UPDATE probe_account SET balance = balance - CAST(? AS INTEGER), revision = revision + 1\nWHERE scope = ? AND id = ? AND revision = CAST(? AS INTEGER);",
        params: [
          { kind: "int64", nullable: false },
          { kind: "scope", nullable: false },
          { kind: "text", nullable: false },
          { kind: "int64", nullable: false },
        ],
        returns: null,
      },
      {
        sql: "UPDATE probe_account SET balance = balance + CAST(? AS INTEGER), revision = revision + 1\nWHERE scope = ? AND id = ? AND revision = CAST(? AS INTEGER);",
        params: [
          { kind: "int64", nullable: false },
          { kind: "scope", nullable: false },
          { kind: "text", nullable: false },
          { kind: "int64", nullable: false },
        ],
        returns: null,
      },
      {
        sql: "INSERT INTO probe_receipt (scope, command_id, request_hash, result_json) VALUES (?, ?, ?, ?);",
        params: [
          { kind: "scope", nullable: false },
          { kind: "text", nullable: false },
          { kind: "text", nullable: false },
          { kind: "text", nullable: false },
        ],
        returns: null,
      },
      {
        sql: "INSERT INTO probe_outbox (scope, command_id, event_key, payload_json) VALUES (?, ?, ?, ?);",
        params: [
          { kind: "scope", nullable: false },
          { kind: "text", nullable: false },
          { kind: "text", nullable: false },
          { kind: "text", nullable: false },
        ],
        returns: null,
      },
      {
        sql: "DELETE FROM probe_guard WHERE command_id = ?;",
        params: [{ kind: "text", nullable: false }],
        returns: null,
      },
    ],
  },
];
