// SPDX-License-Identifier: AGPL-3.0-only
// <auto-generated />
// Generated by eng/verification/storage-plans.ts from the reviewed plan files; do not edit.
import type { PlanDefinition } from "./plan-types.ts";

export const manifestHash = "da57ac5d74917b54cc1e2ea577218008bfddde961752ef14accc892b756572f9";

export const plans: readonly PlanDefinition[] = [
  {
    id: "entitlement.activations-load",
    version: 1,
    access: "read",
    maxRows: 100,
    statements: [
      {
        sql: "SELECT definitions_version, CAST(activated_at AS TEXT)\nFROM entitlement_definitions_activation\nWHERE workspace_id = ? AND activated_at > CAST(? AS INTEGER)\nORDER BY activated_at LIMIT 100;",
        params: [
          { kind: "scope", nullable: false },
          { kind: "int64", nullable: false },
        ],
        returns: [
          { kind: "text", nullable: false },
          { kind: "int64", nullable: false },
        ],
      },
    ],
  },
  {
    id: "entitlement.commit",
    version: 1,
    access: "write",
    maxRows: 0,
    statements: [
      {
        sql: "INSERT INTO platform_command_guard (command_id, guard_key, allowed)\nSELECT ?, 'entitlement.workspace-revision', CASE WHEN COALESCE((SELECT rev FROM entitlement_revision WHERE workspace_id = ?), 0) = CAST(? AS INTEGER) THEN 1 ELSE 0 END;",
        params: [
          { kind: "text", nullable: false },
          { kind: "scope", nullable: false },
          { kind: "int64", nullable: false },
        ],
        returns: null,
      },
      {
        sql: "INSERT INTO entitlement_revision (workspace_id, rev, updated_at) VALUES (?, CAST(? AS INTEGER), CAST(? AS INTEGER))\nON CONFLICT (workspace_id) DO UPDATE SET rev = excluded.rev, updated_at = excluded.updated_at WHERE entitlement_revision.rev = CAST(? AS INTEGER);",
        params: [
          { kind: "scope", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "int64", nullable: false },
        ],
        returns: null,
      },
      {
        sql: "INSERT INTO entitlement_grant (grant_id, workspace_id, kind, subject, value, source, source_ref, effective_from, effective_until, issued_by_actor, created_at, reason)\nSELECT json_extract(j.value, '$.id'), ?, json_extract(j.value, '$.kind'), json_extract(j.value, '$.subject'), json_extract(j.value, '$.value'), json_extract(j.value, '$.source'), json_extract(j.value, '$.sourceRef'), CAST(json_extract(j.value, '$.from') AS INTEGER), CAST(json_extract(j.value, '$.until') AS INTEGER), json_extract(j.value, '$.actor'), CAST(json_extract(j.value, '$.createdAt') AS INTEGER), json_extract(j.value, '$.reason')\nFROM json_each(?) AS j;",
        params: [
          { kind: "scope", nullable: false },
          { kind: "text", nullable: false },
        ],
        returns: null,
      },
      {
        sql: "INSERT INTO entitlement_revocation (revocation_id, grant_id, reason_code, effective_from, issued_by_actor, created_at)\nSELECT json_extract(j.value, '$.id'), json_extract(j.value, '$.grantId'), json_extract(j.value, '$.reasonCode'), CAST(json_extract(j.value, '$.from') AS INTEGER), json_extract(j.value, '$.actor'), CAST(json_extract(j.value, '$.createdAt') AS INTEGER)\nFROM json_each(?) AS j;",
        params: [{ kind: "text", nullable: false }],
        returns: null,
      },
      {
        sql: "INSERT INTO entitlement_service_term (service_term_id, workspace_id, realm_id, kind, subscription_ref, period_ref, starts_at, ends_at, grace_ends_at, supersedes_id, offer_id, offer_snapshot_id, authorized_at, selection_priority, created_at)\nSELECT json_extract(j.value, '$.id'), ?, json_extract(j.value, '$.realmId'), json_extract(j.value, '$.kind'), json_extract(j.value, '$.subscriptionRef'), json_extract(j.value, '$.periodRef'), CAST(json_extract(j.value, '$.startsAt') AS INTEGER), CAST(json_extract(j.value, '$.endsAt') AS INTEGER), CAST(json_extract(j.value, '$.graceEndsAt') AS INTEGER), json_extract(j.value, '$.supersedesId'), json_extract(j.value, '$.offerId'), json_extract(j.value, '$.offerSnapshotId'), CAST(json_extract(j.value, '$.authorizedAt') AS INTEGER), CAST(json_extract(j.value, '$.selectionPriority') AS INTEGER), CAST(json_extract(j.value, '$.createdAt') AS INTEGER)\nFROM json_each(?) AS j;",
        params: [
          { kind: "scope", nullable: false },
          { kind: "text", nullable: false },
        ],
        returns: null,
      },
      {
        sql: "INSERT INTO entitlement_service_term_action (term_action_id, term_id, kind, effective_at, recorded_at, source_ref, replacement_term_id)\nSELECT json_extract(j.value, '$.id'), json_extract(j.value, '$.termId'), json_extract(j.value, '$.kind'), CAST(json_extract(j.value, '$.effectiveAt') AS INTEGER), CAST(json_extract(j.value, '$.recordedAt') AS INTEGER), json_extract(j.value, '$.sourceRef'), json_extract(j.value, '$.replacementTermId')\nFROM json_each(?) AS j;",
        params: [{ kind: "text", nullable: false }],
        returns: null,
      },
      {
        sql: "INSERT INTO entitlement_definitions_activation (workspace_id, activated_at, definitions_version)\nSELECT ?, CAST(json_extract(j.value, '$.activatedAt') AS INTEGER), json_extract(j.value, '$.version')\nFROM json_each(?) AS j;",
        params: [
          { kind: "scope", nullable: false },
          { kind: "text", nullable: false },
        ],
        returns: null,
      },
      {
        sql: "INSERT INTO entitlement_workspace_status_fact (status_fact_id, workspace_id, recorded_at, status, auto_renew, purchase_pending, source_ref)\nSELECT json_extract(j.value, '$.id'), ?, CAST(json_extract(j.value, '$.recordedAt') AS INTEGER), json_extract(j.value, '$.status'), json_extract(j.value, '$.autoRenew'), json_extract(j.value, '$.purchasePending'), json_extract(j.value, '$.sourceRef')\nFROM json_each(?) AS j;",
        params: [
          { kind: "scope", nullable: false },
          { kind: "text", nullable: false },
        ],
        returns: null,
      },
      {
        sql: "INSERT INTO entitlement_snapshot (workspace_id, entitlement_version, computed_at, valid_until, capabilities, quotas, features)\nVALUES (?, CAST(? AS INTEGER), CAST(? AS INTEGER), NULLIF(CAST(? AS INTEGER), -1), ?, ?, ?)\nON CONFLICT (workspace_id) DO UPDATE SET entitlement_version = excluded.entitlement_version, computed_at = excluded.computed_at, valid_until = excluded.valid_until, capabilities = excluded.capabilities, quotas = excluded.quotas, features = excluded.features;",
        params: [
          { kind: "scope", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "text", nullable: false },
          { kind: "text", nullable: false },
          { kind: "text", nullable: false },
        ],
        returns: null,
      },
      {
        sql: "INSERT INTO platform_command (command_id, workspace_id, actor_ref, operation, request_hash, status, result_payload, result_rev, error_code, created_at, expires_at)\nVALUES (?, ?, ?, ?, ?, 2, ?, NULLIF(CAST(? AS INTEGER), -1), NULL, CAST(? AS INTEGER), CAST(? AS INTEGER));",
        params: [
          { kind: "text", nullable: false },
          { kind: "text", nullable: true },
          { kind: "text", nullable: false },
          { kind: "text", nullable: false },
          { kind: "text", nullable: false },
          { kind: "text", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "int64", nullable: false },
        ],
        returns: null,
      },
      {
        sql: "INSERT INTO platform_sequence_stream (stream_key, last_sequence, published_watermark, publish_rev, fence, ack_receipt, updated_at)\nVALUES (?, 1, 0, 0, 0, NULL, CAST(? AS INTEGER))\nON CONFLICT (stream_key) DO UPDATE SET last_sequence = last_sequence + 1, updated_at = excluded.updated_at;",
        params: [
          { kind: "scope", nullable: false },
          { kind: "int64", nullable: false },
        ],
        returns: null,
      },
      {
        sql: "INSERT INTO platform_outbox (outbox_id, aggregate_kind, aggregate_id, aggregate_rev, event_type, payload, workspace_id, correlation_id, causation_id, state, attempts, created_at, dispatched_at)\nVALUES (?, ?, ?, CAST(? AS INTEGER), ?, ?, ?, ?, ?, 1, 0, CAST(? AS INTEGER), NULL);",
        params: [
          { kind: "text", nullable: false },
          { kind: "text", nullable: false },
          { kind: "text", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "text", nullable: false },
          { kind: "text", nullable: false },
          { kind: "text", nullable: true },
          { kind: "text", nullable: false },
          { kind: "text", nullable: true },
          { kind: "int64", nullable: false },
        ],
        returns: null,
      },
      {
        sql: "INSERT INTO platform_outbox_position (outbox_id, stream_key, sequence)\nVALUES (?, ?, (SELECT last_sequence FROM platform_sequence_stream WHERE stream_key = ?));",
        params: [
          { kind: "text", nullable: false },
          { kind: "scope", nullable: false },
          { kind: "scope", nullable: false },
        ],
        returns: null,
      },
      {
        sql: "INSERT INTO platform_sequence_stream (stream_key, last_sequence, published_watermark, publish_rev, fence, ack_receipt, updated_at)\nVALUES ('platform:change-archive', 1, 0, 0, 0, NULL, CAST(? AS INTEGER))\nON CONFLICT (stream_key) DO UPDATE SET last_sequence = last_sequence + 1, updated_at = excluded.updated_at;",
        params: [{ kind: "int64", nullable: false }],
        returns: null,
      },
      {
        sql: "INSERT INTO platform_change_archive (archive_sequence, command_id, schema_version, record, record_hash, created_at)\nVALUES ((SELECT last_sequence FROM platform_sequence_stream WHERE stream_key = 'platform:change-archive'), ?, CAST(? AS INTEGER), ?, ?, CAST(? AS INTEGER));",
        params: [
          { kind: "text", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "text", nullable: false },
          { kind: "bytes", nullable: false },
          { kind: "int64", nullable: false },
        ],
        returns: null,
      },
      {
        sql: "DELETE FROM platform_command_guard WHERE command_id = ?;",
        params: [{ kind: "text", nullable: false }],
        returns: null,
      },
    ],
  },
  {
    id: "entitlement.feature-release-append",
    version: 1,
    access: "write",
    maxRows: 0,
    statements: [
      {
        sql: "INSERT INTO entitlement_feature_release (feature_key, released_at) VALUES (?, CAST(? AS INTEGER));",
        params: [
          { kind: "scope", nullable: false },
          { kind: "int64", nullable: false },
        ],
        returns: null,
      },
    ],
  },
  {
    id: "entitlement.feature-release-get",
    version: 1,
    access: "read",
    maxRows: 1,
    statements: [
      {
        sql: "SELECT CAST(released_at AS TEXT) FROM entitlement_feature_release WHERE feature_key = ?;",
        params: [{ kind: "scope", nullable: false }],
        returns: [{ kind: "int64", nullable: false }],
      },
    ],
  },
  {
    id: "entitlement.feature-releases-load",
    version: 1,
    access: "read",
    maxRows: 100,
    statements: [
      {
        sql: "SELECT feature_key, CAST(released_at AS TEXT) FROM entitlement_feature_release WHERE ? = 'entitlement.global' AND feature_key > ? ORDER BY feature_key LIMIT 100;",
        params: [
          { kind: "scope", nullable: false },
          { kind: "text", nullable: false },
        ],
        returns: [
          { kind: "text", nullable: false },
          { kind: "int64", nullable: false },
        ],
      },
    ],
  },
  {
    id: "entitlement.grants-load",
    version: 1,
    access: "read",
    maxRows: 100,
    statements: [
      {
        sql: "SELECT grant_id, CAST(kind AS TEXT), subject, value, CAST(source AS TEXT), source_ref, CAST(effective_from AS TEXT), CAST(effective_until AS TEXT), issued_by_actor, CAST(created_at AS TEXT), reason\nFROM entitlement_grant\nWHERE workspace_id = ? AND (kind, effective_from, grant_id) > (CAST(? AS INTEGER), CAST(? AS INTEGER), ?)\nORDER BY kind, effective_from, grant_id LIMIT 100;",
        params: [
          { kind: "scope", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "text", nullable: false },
        ],
        returns: [
          { kind: "text", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "text", nullable: false },
          { kind: "text", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "text", nullable: true },
          { kind: "int64", nullable: false },
          { kind: "int64", nullable: true },
          { kind: "text", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "text", nullable: true },
        ],
      },
    ],
  },
  {
    id: "entitlement.revision-load",
    version: 1,
    access: "read",
    maxRows: 1,
    statements: [
      {
        sql: "SELECT CAST(rev AS TEXT) FROM entitlement_revision WHERE workspace_id = ?;",
        params: [{ kind: "scope", nullable: false }],
        returns: [{ kind: "int64", nullable: false }],
      },
    ],
  },
  {
    id: "entitlement.revocations-load",
    version: 1,
    access: "read",
    maxRows: 100,
    statements: [
      {
        sql: "SELECT r.revocation_id, r.grant_id, r.reason_code, CAST(r.effective_from AS TEXT), r.issued_by_actor, CAST(r.created_at AS TEXT)\nFROM entitlement_revocation r JOIN entitlement_grant g ON g.grant_id = r.grant_id\nWHERE g.workspace_id = ? AND (r.created_at, r.revocation_id) > (CAST(? AS INTEGER), ?)\nORDER BY r.created_at, r.revocation_id LIMIT 100;",
        params: [
          { kind: "scope", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "text", nullable: false },
        ],
        returns: [
          { kind: "text", nullable: false },
          { kind: "text", nullable: false },
          { kind: "text", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "text", nullable: false },
          { kind: "int64", nullable: false },
        ],
      },
    ],
  },
  {
    id: "entitlement.snapshot-load",
    version: 1,
    access: "read",
    maxRows: 1,
    statements: [
      {
        sql: "SELECT CAST(entitlement_version AS TEXT), CAST(computed_at AS TEXT), CAST(valid_until AS TEXT), capabilities, quotas, features FROM entitlement_snapshot WHERE workspace_id = ?;",
        params: [{ kind: "scope", nullable: false }],
        returns: [
          { kind: "int64", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "int64", nullable: true },
          { kind: "text", nullable: false },
          { kind: "text", nullable: false },
          { kind: "text", nullable: false },
        ],
      },
    ],
  },
  {
    id: "entitlement.status-facts-load",
    version: 1,
    access: "read",
    maxRows: 100,
    statements: [
      {
        sql: "SELECT status_fact_id, CAST(recorded_at AS TEXT), CAST(status AS TEXT), CAST(auto_renew AS TEXT), CAST(purchase_pending AS TEXT)\nFROM entitlement_workspace_status_fact\nWHERE workspace_id = ? AND (recorded_at, status_fact_id) > (CAST(? AS INTEGER), ?)\nORDER BY recorded_at, status_fact_id LIMIT 100;",
        params: [
          { kind: "scope", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "text", nullable: false },
        ],
        returns: [
          { kind: "text", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "int64", nullable: false },
        ],
      },
    ],
  },
  {
    id: "entitlement.term-actions-load",
    version: 1,
    access: "read",
    maxRows: 100,
    statements: [
      {
        sql: "SELECT a.term_action_id, a.term_id, CAST(a.kind AS TEXT), CAST(a.effective_at AS TEXT), CAST(a.recorded_at AS TEXT)\nFROM entitlement_service_term_action a JOIN entitlement_service_term t ON t.service_term_id = a.term_id\nWHERE t.workspace_id = ? AND (a.recorded_at, a.term_action_id) > (CAST(? AS INTEGER), ?)\nORDER BY a.recorded_at, a.term_action_id LIMIT 100;",
        params: [
          { kind: "scope", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "text", nullable: false },
        ],
        returns: [
          { kind: "text", nullable: false },
          { kind: "text", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "int64", nullable: false },
        ],
      },
    ],
  },
  {
    id: "entitlement.terms-load",
    version: 1,
    access: "read",
    maxRows: 100,
    statements: [
      {
        sql: "SELECT service_term_id, CAST(kind AS TEXT), CAST(starts_at AS TEXT), CAST(ends_at AS TEXT), CAST(grace_ends_at AS TEXT), CAST(authorized_at AS TEXT), CAST(created_at AS TEXT)\nFROM entitlement_service_term\nWHERE workspace_id = ? AND (starts_at, service_term_id) > (CAST(? AS INTEGER), ?)\nORDER BY starts_at, service_term_id LIMIT 100;",
        params: [
          { kind: "scope", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "text", nullable: false },
        ],
        returns: [
          { kind: "text", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "int64", nullable: true },
          { kind: "int64", nullable: false },
          { kind: "int64", nullable: false },
        ],
      },
    ],
  },
  {
    id: "foundation.account-load",
    version: 1,
    access: "read",
    maxRows: 1,
    statements: [
      {
        sql: "SELECT CAST(balance AS TEXT), CAST(revision AS TEXT) FROM probe_account WHERE scope = ? AND id = ?;",
        params: [
          { kind: "scope", nullable: false },
          { kind: "text", nullable: false },
        ],
        returns: [
          { kind: "int64", nullable: false },
          { kind: "int64", nullable: false },
        ],
      },
    ],
  },
  {
    id: "foundation.account-seed",
    version: 1,
    access: "write",
    maxRows: 0,
    statements: [
      {
        sql: "INSERT INTO probe_account (scope, id, balance, revision) VALUES (?, ?, CAST(? AS INTEGER), 1)\nON CONFLICT (scope, id) DO NOTHING;",
        params: [
          { kind: "scope", nullable: false },
          { kind: "text", nullable: false },
          { kind: "int64", nullable: false },
        ],
        returns: null,
      },
    ],
  },
  {
    id: "foundation.exact-load",
    version: 1,
    access: "read",
    maxRows: 1,
    statements: [
      {
        sql: "SELECT CAST(signed_value AS TEXT), unsigned_text, decimal_text, payload, CAST(revision AS TEXT)\nFROM probe_exact WHERE scope = ? AND id = ?;",
        params: [
          { kind: "scope", nullable: false },
          { kind: "text", nullable: false },
        ],
        returns: [
          { kind: "int64", nullable: false },
          { kind: "uint64", nullable: false },
          { kind: "decimal", nullable: false },
          { kind: "bytes", nullable: true },
          { kind: "int64", nullable: false },
        ],
      },
    ],
  },
  {
    id: "foundation.exact-store",
    version: 1,
    access: "write",
    maxRows: 0,
    statements: [
      {
        sql: "INSERT INTO probe_guard (command_id, allowed)\nSELECT ?, CASE WHEN COALESCE((SELECT revision FROM probe_exact WHERE scope = ? AND id = ?), 0) = CAST(? AS INTEGER) THEN 1 ELSE 0 END;",
        params: [
          { kind: "text", nullable: false },
          { kind: "scope", nullable: false },
          { kind: "text", nullable: false },
          { kind: "int64", nullable: false },
        ],
        returns: null,
      },
      {
        sql: "INSERT INTO probe_exact (scope, id, signed_value, unsigned_text, decimal_text, payload, revision)\nVALUES (?, ?, CAST(? AS INTEGER), ?, ?, ?, CAST(? AS INTEGER) + 1)\nON CONFLICT (scope, id) DO UPDATE SET signed_value = excluded.signed_value, unsigned_text = excluded.unsigned_text,\n  decimal_text = excluded.decimal_text, payload = excluded.payload, revision = excluded.revision;",
        params: [
          { kind: "scope", nullable: false },
          { kind: "text", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "uint64", nullable: false },
          { kind: "decimal", nullable: false },
          { kind: "bytes", nullable: true },
          { kind: "int64", nullable: false },
        ],
        returns: null,
      },
      {
        sql: "INSERT INTO probe_receipt (scope, command_id, request_hash, result_json) VALUES (?, ?, ?, ?);",
        params: [
          { kind: "scope", nullable: false },
          { kind: "text", nullable: false },
          { kind: "text", nullable: false },
          { kind: "text", nullable: false },
        ],
        returns: null,
      },
      {
        sql: "DELETE FROM probe_guard WHERE command_id = ?;",
        params: [{ kind: "text", nullable: false }],
        returns: null,
      },
    ],
  },
  {
    id: "foundation.inbox-seen",
    version: 1,
    access: "read",
    maxRows: 1,
    statements: [
      {
        sql: "SELECT CAST(COUNT(*) AS TEXT) FROM probe_inbox WHERE scope = ? AND consumer = 'job-slice' AND event_id = ? AND generation = CAST(? AS INTEGER);",
        params: [
          { kind: "scope", nullable: false },
          { kind: "text", nullable: false },
          { kind: "int64", nullable: false },
        ],
        returns: [{ kind: "int64", nullable: false }],
      },
    ],
  },
  {
    id: "foundation.job-claim",
    version: 1,
    access: "write",
    maxRows: 0,
    statements: [
      {
        sql: "INSERT INTO probe_guard (command_id, allowed)\nSELECT ?, CASE WHEN EXISTS (SELECT 1 FROM probe_job WHERE scope = ? AND job_id = ? AND state = 'running'\n  AND (lease_owner IS NULL OR lease_until <= CAST(? AS INTEGER) OR lease_owner = ?)) THEN 1 ELSE 0 END;",
        params: [
          { kind: "text", nullable: false },
          { kind: "scope", nullable: false },
          { kind: "text", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "text", nullable: false },
        ],
        returns: null,
      },
      {
        sql: "UPDATE probe_job SET lease_owner = ?, lease_until = CAST(? AS INTEGER), fence = fence + 1 WHERE scope = ? AND job_id = ?;",
        params: [
          { kind: "text", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "scope", nullable: false },
          { kind: "text", nullable: false },
        ],
        returns: null,
      },
      {
        sql: "DELETE FROM probe_guard WHERE command_id = ?;",
        params: [{ kind: "text", nullable: false }],
        returns: null,
      },
    ],
  },
  {
    id: "foundation.job-commit",
    version: 1,
    access: "write",
    maxRows: 0,
    statements: [
      {
        sql: "INSERT INTO probe_guard (command_id, allowed)\nSELECT ?, CASE WHEN EXISTS (SELECT 1 FROM probe_job WHERE scope = ? AND job_id = ? AND state = 'running'\n  AND fence = CAST(? AS INTEGER) AND lease_owner = ? AND cursor = CAST(? AS INTEGER) AND lease_until > CAST(? AS INTEGER)) THEN 1 ELSE 0 END;",
        params: [
          { kind: "text", nullable: false },
          { kind: "scope", nullable: false },
          { kind: "text", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "text", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "int64", nullable: false },
        ],
        returns: null,
      },
      {
        sql: "INSERT INTO probe_job_item (scope, job_id, item_no, amount)\nSELECT ?, ?, CAST(json_extract(value, '$.n') AS INTEGER), CAST(json_extract(value, '$.a') AS INTEGER) FROM json_each(?);",
        params: [
          { kind: "scope", nullable: false },
          { kind: "text", nullable: false },
          { kind: "text", nullable: false },
        ],
        returns: null,
      },
      {
        sql: "UPDATE probe_job SET cursor = CAST(? AS INTEGER), checksum = ?,\n  state = CASE WHEN CAST(? AS INTEGER) >= total THEN 'complete' ELSE 'running' END, revision = revision + 1,\n  lease_owner = NULL, lease_until = NULL\nWHERE scope = ? AND job_id = ? AND fence = CAST(? AS INTEGER);",
        params: [
          { kind: "int64", nullable: false },
          { kind: "uint64", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "scope", nullable: false },
          { kind: "text", nullable: false },
          { kind: "int64", nullable: false },
        ],
        returns: null,
      },
      {
        sql: "INSERT INTO probe_inbox (scope, consumer, event_id, generation) VALUES (?, 'job-slice', ?, CAST(? AS INTEGER));",
        params: [
          { kind: "scope", nullable: false },
          { kind: "text", nullable: false },
          { kind: "int64", nullable: false },
        ],
        returns: null,
      },
      {
        sql: "INSERT INTO probe_outbox (scope, command_id, event_key, payload_json) VALUES (?, ?, ?, ?);",
        params: [
          { kind: "scope", nullable: false },
          { kind: "text", nullable: false },
          { kind: "text", nullable: false },
          { kind: "text", nullable: false },
        ],
        returns: null,
      },
      {
        sql: "DELETE FROM probe_guard WHERE command_id = ?;",
        params: [{ kind: "text", nullable: false }],
        returns: null,
      },
    ],
  },
  {
    id: "foundation.job-items",
    version: 1,
    access: "read",
    maxRows: 1,
    statements: [
      {
        sql: "SELECT CAST(COUNT(*) AS TEXT), CAST(COALESCE(SUM(amount), 0) AS TEXT) FROM probe_job_item WHERE scope = ? AND job_id = ?;",
        params: [
          { kind: "scope", nullable: false },
          { kind: "text", nullable: false },
        ],
        returns: [
          { kind: "int64", nullable: false },
          { kind: "int64", nullable: false },
        ],
      },
    ],
  },
  {
    id: "foundation.job-load",
    version: 1,
    access: "read",
    maxRows: 1,
    statements: [
      {
        sql: "SELECT CAST(total AS TEXT), CAST(cursor AS TEXT), CAST(fence AS TEXT), lease_owner, CAST(lease_until AS TEXT), state, checksum, CAST(revision AS TEXT)\nFROM probe_job WHERE scope = ? AND job_id = ?;",
        params: [
          { kind: "scope", nullable: false },
          { kind: "text", nullable: false },
        ],
        returns: [
          { kind: "int64", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "text", nullable: true },
          { kind: "int64", nullable: true },
          { kind: "text", nullable: false },
          { kind: "uint64", nullable: false },
          { kind: "int64", nullable: false },
        ],
      },
    ],
  },
  {
    id: "foundation.job-start",
    version: 1,
    access: "write",
    maxRows: 0,
    statements: [
      {
        sql: "INSERT INTO probe_job (scope, job_id, total, cursor, fence, lease_owner, lease_until, state, checksum, revision)\nVALUES (?, ?, CAST(? AS INTEGER), 0, 0, NULL, NULL, 'running', '0', 1);",
        params: [
          { kind: "scope", nullable: false },
          { kind: "text", nullable: false },
          { kind: "int64", nullable: false },
        ],
        returns: null,
      },
      {
        sql: "INSERT INTO probe_outbox (scope, command_id, event_key, payload_json) VALUES (?, ?, ?, ?);",
        params: [
          { kind: "scope", nullable: false },
          { kind: "text", nullable: false },
          { kind: "text", nullable: false },
          { kind: "text", nullable: false },
        ],
        returns: null,
      },
    ],
  },
  {
    id: "foundation.outbox-state",
    version: 1,
    access: "read",
    maxRows: 1,
    statements: [
      {
        sql: "SELECT CAST(COUNT(*) AS TEXT), CAST(COALESCE(MAX(sequence), 0) AS TEXT) FROM probe_outbox WHERE scope = ?;",
        params: [{ kind: "scope", nullable: false }],
        returns: [
          { kind: "int64", nullable: false },
          { kind: "int64", nullable: false },
        ],
      },
    ],
  },
  {
    id: "foundation.readiness",
    version: 1,
    access: "read",
    maxRows: 1,
    statements: [
      {
        sql: "SELECT CAST(version AS TEXT) FROM probe_schema;",
        params: [],
        returns: [{ kind: "int64", nullable: false }],
      },
    ],
  },
  {
    id: "foundation.receipt-load",
    version: 1,
    access: "read",
    maxRows: 1,
    statements: [
      {
        sql: "SELECT request_hash, result_json FROM probe_receipt WHERE scope = ? AND command_id = ?;",
        params: [
          { kind: "scope", nullable: false },
          { kind: "text", nullable: false },
        ],
        returns: [
          { kind: "text", nullable: false },
          { kind: "text", nullable: false },
        ],
      },
    ],
  },
  {
    id: "foundation.session-create",
    version: 1,
    access: "write",
    maxRows: 0,
    statements: [
      {
        sql: "INSERT INTO probe_session (scope, session_id, handle_hash, user_id, device_id, workspace_ids_json, recovery_generation, auth_epoch,\n  created_at, absolute_expires_at, idle_expires_at, last_seen_at, revoked_at, revoke_reason)\nVALUES (?, ?, ?, ?, ?, ?, CAST(? AS INTEGER), CAST(? AS INTEGER), CAST(? AS INTEGER), CAST(? AS INTEGER), CAST(? AS INTEGER), CAST(? AS INTEGER), NULL, NULL);",
        params: [
          { kind: "scope", nullable: false },
          { kind: "text", nullable: false },
          { kind: "bytes", nullable: false },
          { kind: "text", nullable: false },
          { kind: "text", nullable: false },
          { kind: "text", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "int64", nullable: false },
        ],
        returns: null,
      },
      {
        sql: "INSERT INTO probe_outbox (scope, command_id, event_key, payload_json) VALUES (?, ?, ?, ?);",
        params: [
          { kind: "scope", nullable: false },
          { kind: "text", nullable: false },
          { kind: "text", nullable: false },
          { kind: "text", nullable: false },
        ],
        returns: null,
      },
    ],
  },
  {
    id: "foundation.session-load",
    version: 1,
    access: "read",
    maxRows: 1,
    statements: [
      {
        sql: "SELECT session_id, user_id, device_id, workspace_ids_json, CAST(recovery_generation AS TEXT), CAST(auth_epoch AS TEXT),\n  CAST(created_at AS TEXT), CAST(absolute_expires_at AS TEXT), CAST(idle_expires_at AS TEXT), CAST(last_seen_at AS TEXT),\n  CAST(revoked_at AS TEXT), revoke_reason\nFROM probe_session WHERE scope = ? AND handle_hash = ?;",
        params: [
          { kind: "scope", nullable: false },
          { kind: "bytes", nullable: false },
        ],
        returns: [
          { kind: "text", nullable: false },
          { kind: "text", nullable: false },
          { kind: "text", nullable: false },
          { kind: "text", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "int64", nullable: true },
          { kind: "text", nullable: true },
        ],
      },
    ],
  },
  {
    id: "foundation.session-load-by-id",
    version: 1,
    access: "read",
    maxRows: 1,
    statements: [
      {
        sql: "SELECT session_id, user_id, device_id, workspace_ids_json, CAST(recovery_generation AS TEXT), CAST(auth_epoch AS TEXT),\n  CAST(created_at AS TEXT), CAST(absolute_expires_at AS TEXT), CAST(idle_expires_at AS TEXT), CAST(last_seen_at AS TEXT),\n  CAST(revoked_at AS TEXT), revoke_reason\nFROM probe_session WHERE scope = ? AND session_id = ?;",
        params: [
          { kind: "scope", nullable: false },
          { kind: "text", nullable: false },
        ],
        returns: [
          { kind: "text", nullable: false },
          { kind: "text", nullable: false },
          { kind: "text", nullable: false },
          { kind: "text", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "int64", nullable: true },
          { kind: "text", nullable: true },
        ],
      },
    ],
  },
  {
    id: "foundation.session-revoke",
    version: 1,
    access: "write",
    maxRows: 0,
    statements: [
      {
        sql: "INSERT INTO probe_guard (command_id, allowed)\nSELECT ?, CASE WHEN EXISTS (SELECT 1 FROM probe_session WHERE scope = ? AND session_id = ? AND revoked_at IS NULL) THEN 1 ELSE 0 END;",
        params: [
          { kind: "text", nullable: false },
          { kind: "scope", nullable: false },
          { kind: "text", nullable: false },
        ],
        returns: null,
      },
      {
        sql: "UPDATE probe_session SET revoked_at = CAST(? AS INTEGER), revoke_reason = ?\nWHERE scope = ? AND session_id = ? AND revoked_at IS NULL;",
        params: [
          { kind: "int64", nullable: false },
          { kind: "text", nullable: false },
          { kind: "scope", nullable: false },
          { kind: "text", nullable: false },
        ],
        returns: null,
      },
      {
        sql: "INSERT INTO probe_outbox (scope, command_id, event_key, payload_json) VALUES (?, ?, ?, ?);",
        params: [
          { kind: "scope", nullable: false },
          { kind: "text", nullable: false },
          { kind: "text", nullable: false },
          { kind: "text", nullable: false },
        ],
        returns: null,
      },
      {
        sql: "DELETE FROM probe_guard WHERE command_id = ?;",
        params: [{ kind: "text", nullable: false }],
        returns: null,
      },
    ],
  },
  {
    id: "foundation.session-touch",
    version: 1,
    access: "write",
    maxRows: 0,
    statements: [
      {
        sql: "UPDATE probe_session SET last_seen_at = CAST(? AS INTEGER), idle_expires_at = CAST(? AS INTEGER)\nWHERE scope = ? AND handle_hash = ? AND revoked_at IS NULL\n  AND idle_expires_at > CAST(? AS INTEGER) AND absolute_expires_at > CAST(? AS INTEGER);",
        params: [
          { kind: "int64", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "scope", nullable: false },
          { kind: "bytes", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "int64", nullable: false },
        ],
        returns: null,
      },
    ],
  },
  {
    id: "foundation.transfer",
    version: 1,
    access: "write",
    maxRows: 0,
    statements: [
      {
        sql: "INSERT INTO probe_guard (command_id, allowed)\nSELECT ?, CASE WHEN\n  EXISTS (SELECT 1 FROM probe_account WHERE scope = ? AND id = ? AND revision = CAST(? AS INTEGER) AND balance >= CAST(? AS INTEGER))\n  AND EXISTS (SELECT 1 FROM probe_account WHERE scope = ? AND id = ? AND revision = CAST(? AS INTEGER))\nTHEN 1 ELSE 0 END;",
        params: [
          { kind: "text", nullable: false },
          { kind: "scope", nullable: false },
          { kind: "text", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "scope", nullable: false },
          { kind: "text", nullable: false },
          { kind: "int64", nullable: false },
        ],
        returns: null,
      },
      {
        sql: "UPDATE probe_account SET balance = balance - CAST(? AS INTEGER), revision = revision + 1\nWHERE scope = ? AND id = ? AND revision = CAST(? AS INTEGER);",
        params: [
          { kind: "int64", nullable: false },
          { kind: "scope", nullable: false },
          { kind: "text", nullable: false },
          { kind: "int64", nullable: false },
        ],
        returns: null,
      },
      {
        sql: "UPDATE probe_account SET balance = balance + CAST(? AS INTEGER), revision = revision + 1\nWHERE scope = ? AND id = ? AND revision = CAST(? AS INTEGER);",
        params: [
          { kind: "int64", nullable: false },
          { kind: "scope", nullable: false },
          { kind: "text", nullable: false },
          { kind: "int64", nullable: false },
        ],
        returns: null,
      },
      {
        sql: "INSERT INTO probe_receipt (scope, command_id, request_hash, result_json) VALUES (?, ?, ?, ?);",
        params: [
          { kind: "scope", nullable: false },
          { kind: "text", nullable: false },
          { kind: "text", nullable: false },
          { kind: "text", nullable: false },
        ],
        returns: null,
      },
      {
        sql: "INSERT INTO probe_outbox (scope, command_id, event_key, payload_json) VALUES (?, ?, ?, ?);",
        params: [
          { kind: "scope", nullable: false },
          { kind: "text", nullable: false },
          { kind: "text", nullable: false },
          { kind: "text", nullable: false },
        ],
        returns: null,
      },
      {
        sql: "DELETE FROM probe_guard WHERE command_id = ?;",
        params: [{ kind: "text", nullable: false }],
        returns: null,
      },
    ],
  },
  {
    id: "platform.archive-ack",
    version: 1,
    access: "write",
    maxRows: 0,
    statements: [
      {
        sql: "INSERT INTO platform_command_guard (command_id, guard_key, allowed)\nSELECT ?, 'platform.archive-ack', CASE WHEN\n  EXISTS (SELECT 1 FROM platform_sequence_stream WHERE stream_key = 'platform:change-archive' AND published_watermark = CAST(? AS INTEGER) AND publish_rev = CAST(? AS INTEGER) AND fence = CAST(? AS INTEGER) AND last_sequence >= CAST(? AS INTEGER))\n  AND (SELECT COUNT(*) FROM platform_change_archive WHERE archive_sequence > CAST(? AS INTEGER) AND archive_sequence <= CAST(? AS INTEGER)) = CAST(? AS INTEGER)\nTHEN 1 ELSE 0 END;",
        params: [
          { kind: "text", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "int64", nullable: false },
        ],
        returns: null,
      },
      {
        sql: "UPDATE platform_sequence_stream SET published_watermark = CAST(? AS INTEGER), publish_rev = publish_rev + 1, ack_receipt = ?, updated_at = CAST(? AS INTEGER)\nWHERE stream_key = 'platform:change-archive' AND published_watermark = CAST(? AS INTEGER) AND publish_rev = CAST(? AS INTEGER) AND fence = CAST(? AS INTEGER);",
        params: [
          { kind: "int64", nullable: false },
          { kind: "text", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "int64", nullable: false },
        ],
        returns: null,
      },
      {
        sql: "DELETE FROM platform_command_guard WHERE command_id = ?;",
        params: [{ kind: "text", nullable: false }],
        returns: null,
      },
    ],
  },
  {
    id: "platform.archive-purge",
    version: 1,
    access: "write",
    maxRows: 0,
    statements: [
      {
        sql: "INSERT INTO platform_command_guard (command_id, guard_key, allowed)\nSELECT ?, 'platform.archive-purge', CASE WHEN EXISTS (SELECT 1 FROM platform_sequence_stream WHERE stream_key = 'platform:change-archive' AND published_watermark >= CAST(? AS INTEGER)) THEN 1 ELSE 0 END;",
        params: [
          { kind: "text", nullable: false },
          { kind: "int64", nullable: false },
        ],
        returns: null,
      },
      {
        sql: "DELETE FROM platform_change_archive WHERE archive_sequence <= MIN(CAST(? AS INTEGER), COALESCE((SELECT published_watermark FROM platform_sequence_stream WHERE stream_key = 'platform:change-archive'), 0)) AND created_at < CAST(? AS INTEGER);",
        params: [
          { kind: "int64", nullable: false },
          { kind: "int64", nullable: false },
        ],
        returns: null,
      },
      {
        sql: "DELETE FROM platform_command_guard WHERE command_id = ?;",
        params: [{ kind: "text", nullable: false }],
        returns: null,
      },
    ],
  },
  {
    id: "platform.archive-select",
    version: 1,
    access: "read",
    maxRows: 100,
    statements: [
      {
        sql: "SELECT CAST(archive_sequence AS TEXT), command_id, CAST(schema_version AS TEXT), record, record_hash, CAST(created_at AS TEXT)\nFROM (\n  SELECT archive_sequence, command_id, schema_version, record, record_hash, created_at,\n    SUM(length(CAST(record AS BLOB))) OVER (ORDER BY archive_sequence) AS running_bytes\n  FROM platform_change_archive\n  WHERE archive_sequence > CAST(? AS INTEGER) AND archive_sequence <= CAST(? AS INTEGER)\n)\nWHERE running_bytes <= 98304 ORDER BY archive_sequence;",
        params: [
          { kind: "int64", nullable: false },
          { kind: "int64", nullable: false },
        ],
        returns: [
          { kind: "int64", nullable: false },
          { kind: "text", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "text", nullable: false },
          { kind: "bytes", nullable: false },
          { kind: "int64", nullable: false },
        ],
      },
    ],
  },
  {
    id: "platform.archive-state",
    version: 1,
    access: "read",
    maxRows: 1,
    statements: [
      {
        sql: "SELECT CAST(last_sequence AS TEXT), CAST(published_watermark AS TEXT), CAST(publish_rev AS TEXT), CAST(fence AS TEXT), ack_receipt\nFROM platform_sequence_stream WHERE stream_key = 'platform:change-archive';",
        params: [],
        returns: [
          { kind: "int64", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "text", nullable: true },
        ],
      },
    ],
  },
  {
    id: "platform.command-load",
    version: 1,
    access: "read",
    maxRows: 1,
    statements: [
      {
        sql: "SELECT request_hash, CAST(status AS TEXT), result_payload, CAST(result_rev AS TEXT), error_code, CAST(expires_at AS TEXT), actor_ref, operation, workspace_id\nFROM platform_command WHERE command_id = ?;",
        params: [{ kind: "text", nullable: false }],
        returns: [
          { kind: "text", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "text", nullable: true },
          { kind: "int64", nullable: true },
          { kind: "text", nullable: true },
          { kind: "int64", nullable: false },
          { kind: "text", nullable: false },
          { kind: "text", nullable: false },
          { kind: "text", nullable: true },
        ],
      },
    ],
  },
  {
    id: "platform.command-record-failure",
    version: 1,
    access: "write",
    maxRows: 0,
    statements: [
      {
        sql: "INSERT INTO platform_command (command_id, workspace_id, actor_ref, operation, request_hash, status, result_payload, result_rev, error_code, created_at, expires_at)\nVALUES (?, ?, ?, ?, ?, 3, NULL, NULL, ?, CAST(? AS INTEGER), CAST(? AS INTEGER));",
        params: [
          { kind: "text", nullable: false },
          { kind: "text", nullable: true },
          { kind: "text", nullable: false },
          { kind: "text", nullable: false },
          { kind: "text", nullable: false },
          { kind: "text", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "int64", nullable: false },
        ],
        returns: null,
      },
    ],
  },
  {
    id: "platform.inbox-load",
    version: 1,
    access: "read",
    maxRows: 1,
    statements: [
      {
        sql: "SELECT CAST(outcome AS TEXT), CAST(processed_at AS TEXT) FROM platform_inbox WHERE source = ? AND message_id = ?;",
        params: [
          { kind: "text", nullable: false },
          { kind: "text", nullable: false },
        ],
        returns: [
          { kind: "int64", nullable: true },
          { kind: "int64", nullable: true },
        ],
      },
    ],
  },
  {
    id: "platform.inbox-record",
    version: 1,
    access: "write",
    maxRows: 0,
    statements: [
      {
        sql: "INSERT INTO platform_inbox (source, message_id, received_at, processed_at, outcome, expires_at)\nVALUES (?, ?, CAST(? AS INTEGER), CAST(? AS INTEGER), CAST(? AS INTEGER), CAST(? AS INTEGER));",
        params: [
          { kind: "text", nullable: false },
          { kind: "text", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "int64", nullable: false },
        ],
        returns: null,
      },
    ],
  },
  {
    id: "platform.outbox-ack",
    version: 1,
    access: "write",
    maxRows: 0,
    statements: [
      {
        sql: "INSERT INTO platform_command_guard (command_id, guard_key, allowed)\nSELECT ?, 'platform.outbox-ack', CASE WHEN\n  EXISTS (SELECT 1 FROM platform_sequence_stream WHERE stream_key = ? AND published_watermark = CAST(? AS INTEGER) AND publish_rev = CAST(? AS INTEGER) AND fence = CAST(? AS INTEGER) AND last_sequence >= CAST(? AS INTEGER))\n  AND (SELECT COUNT(*) FROM platform_outbox_position p JOIN platform_outbox o ON o.outbox_id = p.outbox_id WHERE p.stream_key = ? AND p.sequence > CAST(? AS INTEGER) AND p.sequence <= CAST(? AS INTEGER) AND o.state = 1) = CAST(? AS INTEGER)\nTHEN 1 ELSE 0 END;",
        params: [
          { kind: "text", nullable: false },
          { kind: "scope", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "scope", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "int64", nullable: false },
        ],
        returns: null,
      },
      {
        sql: "UPDATE platform_outbox SET state = 2, dispatched_at = CAST(? AS INTEGER)\nWHERE state = 1 AND outbox_id IN (SELECT outbox_id FROM platform_outbox_position WHERE stream_key = ? AND sequence > CAST(? AS INTEGER) AND sequence <= CAST(? AS INTEGER));",
        params: [
          { kind: "int64", nullable: false },
          { kind: "scope", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "int64", nullable: false },
        ],
        returns: null,
      },
      {
        sql: "UPDATE platform_sequence_stream SET published_watermark = CAST(? AS INTEGER), publish_rev = publish_rev + 1, ack_receipt = ?, updated_at = CAST(? AS INTEGER)\nWHERE stream_key = ? AND published_watermark = CAST(? AS INTEGER) AND publish_rev = CAST(? AS INTEGER) AND fence = CAST(? AS INTEGER);",
        params: [
          { kind: "int64", nullable: false },
          { kind: "text", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "scope", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "int64", nullable: false },
        ],
        returns: null,
      },
      {
        sql: "DELETE FROM platform_command_guard WHERE command_id = ?;",
        params: [{ kind: "text", nullable: false }],
        returns: null,
      },
    ],
  },
  {
    id: "platform.outbox-attempt",
    version: 1,
    access: "write",
    maxRows: 0,
    statements: [
      {
        sql: "INSERT INTO platform_command_guard (command_id, guard_key, allowed)\nSELECT ?, 'platform.outbox-attempt', CASE WHEN EXISTS (\n  SELECT 1 FROM platform_outbox o JOIN platform_outbox_position p ON p.outbox_id = o.outbox_id JOIN platform_sequence_stream s ON s.stream_key = p.stream_key\n  WHERE o.outbox_id = ? AND p.stream_key = ? AND o.state = 1 AND o.attempts = CAST(? AS INTEGER) AND s.fence = CAST(? AS INTEGER)\n) THEN 1 ELSE 0 END;",
        params: [
          { kind: "text", nullable: false },
          { kind: "text", nullable: false },
          { kind: "scope", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "int64", nullable: false },
        ],
        returns: null,
      },
      {
        sql: "UPDATE platform_outbox SET attempts = attempts + 1 WHERE outbox_id = ? AND state = 1 AND attempts = CAST(? AS INTEGER);",
        params: [
          { kind: "text", nullable: false },
          { kind: "int64", nullable: false },
        ],
        returns: null,
      },
      {
        sql: "DELETE FROM platform_command_guard WHERE command_id = ?;",
        params: [{ kind: "text", nullable: false }],
        returns: null,
      },
    ],
  },
  {
    id: "platform.outbox-dead-letter",
    version: 1,
    access: "write",
    maxRows: 0,
    statements: [
      {
        sql: "INSERT INTO platform_command_guard (command_id, guard_key, allowed)\nSELECT ?, 'platform.outbox-dead-letter', CASE WHEN EXISTS (\n  SELECT 1 FROM platform_outbox o JOIN platform_outbox_position p ON p.outbox_id = o.outbox_id JOIN platform_sequence_stream s ON s.stream_key = p.stream_key\n  WHERE o.outbox_id = ? AND p.stream_key = ? AND o.state = 1 AND o.attempts = CAST(? AS INTEGER) AND s.fence = CAST(? AS INTEGER)\n) THEN 1 ELSE 0 END;",
        params: [
          { kind: "text", nullable: false },
          { kind: "text", nullable: false },
          { kind: "scope", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "int64", nullable: false },
        ],
        returns: null,
      },
      {
        sql: "UPDATE platform_outbox SET state = 3 WHERE outbox_id = ? AND state = 1 AND attempts = CAST(? AS INTEGER);",
        params: [
          { kind: "text", nullable: false },
          { kind: "int64", nullable: false },
        ],
        returns: null,
      },
      {
        sql: "DELETE FROM platform_command_guard WHERE command_id = ?;",
        params: [{ kind: "text", nullable: false }],
        returns: null,
      },
    ],
  },
  {
    id: "platform.outbox-purge",
    version: 1,
    access: "write",
    maxRows: 0,
    statements: [
      {
        sql: "INSERT INTO platform_command_guard (command_id, guard_key, allowed)\nSELECT ?, 'platform.outbox-purge', CASE WHEN EXISTS (SELECT 1 FROM platform_sequence_stream WHERE stream_key = ? AND published_watermark >= CAST(? AS INTEGER)) THEN 1 ELSE 0 END;",
        params: [
          { kind: "text", nullable: false },
          { kind: "scope", nullable: false },
          { kind: "int64", nullable: false },
        ],
        returns: null,
      },
      {
        sql: "DELETE FROM platform_outbox_position WHERE stream_key = ? AND sequence <= MIN(CAST(? AS INTEGER), COALESCE((SELECT published_watermark FROM platform_sequence_stream WHERE stream_key = ?), 0)) AND outbox_id IN (SELECT outbox_id FROM platform_outbox WHERE state = 2 AND created_at < CAST(? AS INTEGER));",
        params: [
          { kind: "scope", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "scope", nullable: false },
          { kind: "int64", nullable: false },
        ],
        returns: null,
      },
      {
        sql: "DELETE FROM platform_outbox WHERE state = 2 AND created_at < CAST(? AS INTEGER) AND outbox_id NOT IN (SELECT outbox_id FROM platform_outbox_position);",
        params: [{ kind: "int64", nullable: false }],
        returns: null,
      },
      {
        sql: "DELETE FROM platform_command_guard WHERE command_id = ?;",
        params: [{ kind: "text", nullable: false }],
        returns: null,
      },
    ],
  },
  {
    id: "platform.outbox-requeue",
    version: 1,
    access: "write",
    maxRows: 0,
    statements: [
      {
        sql: "INSERT INTO platform_command_guard (command_id, guard_key, allowed)\nSELECT ?, 'platform.outbox-requeue', CASE WHEN EXISTS (\n  SELECT 1 FROM platform_outbox o JOIN platform_outbox_position p ON p.outbox_id = o.outbox_id JOIN platform_sequence_stream s ON s.stream_key = p.stream_key\n  WHERE o.outbox_id = ? AND p.stream_key = ? AND o.state = 3 AND s.fence = CAST(? AS INTEGER)\n) THEN 1 ELSE 0 END;",
        params: [
          { kind: "text", nullable: false },
          { kind: "text", nullable: false },
          { kind: "scope", nullable: false },
          { kind: "int64", nullable: false },
        ],
        returns: null,
      },
      {
        sql: "UPDATE platform_outbox SET state = 1, attempts = 0 WHERE outbox_id = ? AND state = 3;",
        params: [{ kind: "text", nullable: false }],
        returns: null,
      },
      {
        sql: "DELETE FROM platform_command_guard WHERE command_id = ?;",
        params: [{ kind: "text", nullable: false }],
        returns: null,
      },
    ],
  },
  {
    id: "platform.outbox-select",
    version: 1,
    access: "read",
    maxRows: 50,
    statements: [
      {
        sql: "SELECT CAST(sequence AS TEXT), outbox_id, aggregate_kind, aggregate_id, CAST(aggregate_rev AS TEXT), event_type, payload, workspace_id, correlation_id, causation_id, CAST(state AS TEXT), CAST(attempts AS TEXT), CAST(created_at AS TEXT)\nFROM (\n  SELECT p.sequence AS sequence, o.outbox_id AS outbox_id, o.aggregate_kind AS aggregate_kind, o.aggregate_id AS aggregate_id, o.aggregate_rev AS aggregate_rev, o.event_type AS event_type, o.payload AS payload, o.workspace_id AS workspace_id, o.correlation_id AS correlation_id, o.causation_id AS causation_id, o.state AS state, o.attempts AS attempts, o.created_at AS created_at,\n    SUM(length(CAST(o.payload AS BLOB))) OVER (ORDER BY p.sequence) AS running_bytes\n  FROM platform_outbox_position p JOIN platform_outbox o ON o.outbox_id = p.outbox_id\n  WHERE p.stream_key = ? AND p.sequence > CAST(? AS INTEGER) AND p.sequence <= CAST(? AS INTEGER)\n)\nWHERE running_bytes <= 65536 ORDER BY sequence;",
        params: [
          { kind: "scope", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "int64", nullable: false },
        ],
        returns: [
          { kind: "int64", nullable: false },
          { kind: "text", nullable: false },
          { kind: "text", nullable: false },
          { kind: "text", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "text", nullable: false },
          { kind: "text", nullable: false },
          { kind: "text", nullable: true },
          { kind: "text", nullable: false },
          { kind: "text", nullable: true },
          { kind: "int64", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "int64", nullable: false },
        ],
      },
    ],
  },
  {
    id: "platform.stream-fence",
    version: 1,
    access: "write",
    maxRows: 0,
    statements: [
      {
        sql: "INSERT INTO platform_command_guard (command_id, guard_key, allowed)\nSELECT ?, 'platform.stream-fence', CASE WHEN EXISTS (SELECT 1 FROM platform_sequence_stream WHERE stream_key = ? AND fence = CAST(? AS INTEGER)) THEN 1 ELSE 0 END;",
        params: [
          { kind: "text", nullable: false },
          { kind: "scope", nullable: false },
          { kind: "int64", nullable: false },
        ],
        returns: null,
      },
      {
        sql: "UPDATE platform_sequence_stream SET fence = fence + 1, publish_rev = publish_rev + 1, updated_at = CAST(? AS INTEGER)\nWHERE stream_key = ? AND fence = CAST(? AS INTEGER);",
        params: [
          { kind: "int64", nullable: false },
          { kind: "scope", nullable: false },
          { kind: "int64", nullable: false },
        ],
        returns: null,
      },
      {
        sql: "DELETE FROM platform_command_guard WHERE command_id = ?;",
        params: [{ kind: "text", nullable: false }],
        returns: null,
      },
    ],
  },
  {
    id: "platform.stream-load",
    version: 1,
    access: "read",
    maxRows: 1,
    statements: [
      {
        sql: "SELECT CAST(last_sequence AS TEXT), CAST(published_watermark AS TEXT), CAST(publish_rev AS TEXT), CAST(fence AS TEXT), ack_receipt\nFROM platform_sequence_stream WHERE stream_key = ?;",
        params: [{ kind: "scope", nullable: false }],
        returns: [
          { kind: "int64", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "int64", nullable: false },
          { kind: "text", nullable: true },
        ],
      },
    ],
  },
];
