<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RuntimeIdentifiers>linux-x64;win-x64</RuntimeIdentifiers>
    <IsAotCompatible>true</IsAotCompatible>
    <JsonSerializerIsReflectionEnabledByDefault>false</JsonSerializerIsReflectionEnabledByDefault>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="ArcForges.Contracts.CloudInternal" />
    <ProjectReference Include="../ArcForges.Cloud.Modules.Abstractions/ArcForges.Cloud.Modules.Abstractions.csproj" />
    <InternalsVisibleTo Include="ArcForges.Cloud" />
    <InternalsVisibleTo Include="ArcForges.Cloud.Tests" />
  </ItemGroup>
  <PropertyGroup>
    <LicenceBoundary>AGPL</LicenceBoundary>
    <PackageLicenseExpression>AGPL-3.0-only</PackageLicenseExpression>
  </PropertyGroup>
</Project>
