// SPDX-License-Identifier: AGPL-3.0-only
// <auto-generated />
// Generated by eng/verification/storage-plans.ts from the reviewed plan files; do not edit.
#nullable enable
using ArcForges.Cloud.Storage.SharedFamilies;

namespace ArcForges.Cloud.Storage;

/// <summary>Typed definitions of the reviewed named plans and their single manifest identity.</summary>
internal static class PlanManifest
{
    public const string Hash = "a04a78fea1954bf0fa625ff4b39ce80e925fad92c9ebb0f72938bd88f2578606";

    /// <summary>The reviewed plans of the identity owner (<c>storage/plans/identity</c>).</summary>
    internal static class Identity
    {
        public static readonly PlanDefinition CredentialAdd = new(
            "identity.credential-add",
            1,
            PlanAccess.Write,
            0,
            [
                new([new(PlanKind.Text), new(PlanKind.Text), new(PlanKind.Text), new(PlanKind.Int64), new(PlanKind.Text), new(PlanKind.Text), new(PlanKind.Text)], null),
                new([new(PlanKind.Text), new(PlanKind.Text), new(PlanKind.Int64), new(PlanKind.Text), new(PlanKind.Bytes, true), new(PlanKind.Bytes, true), new(PlanKind.Int64), new(PlanKind.Int64), new(PlanKind.Text, true), new(PlanKind.Int64), new(PlanKind.Text, true), new(PlanKind.Int64), new(PlanKind.Text), new(PlanKind.Text), new(PlanKind.Text, true)], null),
                new([new(PlanKind.Text), new(PlanKind.Text), new(PlanKind.Int64)], null),
                new([new(PlanKind.Text), new(PlanKind.Text, true), new(PlanKind.Text), new(PlanKind.Text), new(PlanKind.Text), new(PlanKind.Text), new(PlanKind.Int64), new(PlanKind.Int64), new(PlanKind.Int64)], null),
                new([new(PlanKind.Scope), new(PlanKind.Int64)], null),
                new([new(PlanKind.Text), new(PlanKind.Text), new(PlanKind.Text), new(PlanKind.Int64), new(PlanKind.Text), new(PlanKind.Text), new(PlanKind.Text, true), new(PlanKind.Text), new(PlanKind.Text, true), new(PlanKind.Int64)], null),
                new([new(PlanKind.Text), new(PlanKind.Scope), new(PlanKind.Scope)], null),
                new([new(PlanKind.Int64)], null),
                new([new(PlanKind.Text), new(PlanKind.Int64), new(PlanKind.Text), new(PlanKind.Bytes), new(PlanKind.Int64)], null),
                new([new(PlanKind.Text)], null)
            ]);

        public static readonly PlanDefinition CredentialFind = new(
            "identity.credential-find",
            1,
            PlanAccess.Read,
            1,
            [
                new([new(PlanKind.Text), new(PlanKind.Text), new(PlanKind.Text)], [new(PlanKind.Text), new(PlanKind.Text), new(PlanKind.Int64), new(PlanKind.Text, true), new(PlanKind.Int64), new(PlanKind.Int64, true), new(PlanKind.Int64, true), new(PlanKind.Int64), new(PlanKind.Int64), new(PlanKind.Int64)])
            ]);

        public static readonly PlanDefinition CredentialList = new(
            "identity.credential-list",
            1,
            PlanAccess.Read,
            64,
            [
                new([new(PlanKind.Text), new(PlanKind.Text)], [new(PlanKind.Text), new(PlanKind.Int64), new(PlanKind.Text), new(PlanKind.Text, true), new(PlanKind.Int64), new(PlanKind.Int64, true), new(PlanKind.Int64, true), new(PlanKind.Int64)])
            ]);

        public static readonly PlanDefinition CredentialRelabel = new(
            "identity.credential-relabel",
            1,
            PlanAccess.Write,
            0,
            [
                new([new(PlanKind.Text), new(PlanKind.Text), new(PlanKind.Text), new(PlanKind.Text), new(PlanKind.Int64), new(PlanKind.Text), new(PlanKind.Text)], null),
                new([new(PlanKind.Text, true), new(PlanKind.Text), new(PlanKind.Text), new(PlanKind.Text), new(PlanKind.Int64)], null),
                new([new(PlanKind.Text), new(PlanKind.Text, true), new(PlanKind.Text), new(PlanKind.Text), new(PlanKind.Text), new(PlanKind.Text), new(PlanKind.Int64), new(PlanKind.Int64), new(PlanKind.Int64)], null),
                new([new(PlanKind.Scope), new(PlanKind.Int64)], null),
                new([new(PlanKind.Text), new(PlanKind.Text), new(PlanKind.Text), new(PlanKind.Int64), new(PlanKind.Text), new(PlanKind.Text), new(PlanKind.Text, true), new(PlanKind.Text), new(PlanKind.Text, true), new(PlanKind.Int64)], null),
                new([new(PlanKind.Text), new(PlanKind.Scope), new(PlanKind.Scope)], null),
                new([new(PlanKind.Int64)], null),
                new([new(PlanKind.Text), new(PlanKind.Int64), new(PlanKind.Text), new(PlanKind.Bytes), new(PlanKind.Int64)], null),
                new([new(PlanKind.Text)], null)
            ]);

        public static readonly PlanDefinition CredentialRevoke = new(
            "identity.credential-revoke",
            1,
            PlanAccess.Write,
            0,
            [
                new([new(PlanKind.Text), new(PlanKind.Text), new(PlanKind.Text), new(PlanKind.Text), new(PlanKind.Int64), new(PlanKind.Text), new(PlanKind.Text), new(PlanKind.Int64), new(PlanKind.Text), new(PlanKind.Text), new(PlanKind.Text), new(PlanKind.Text)], null),
                new([new(PlanKind.Int64), new(PlanKind.Text), new(PlanKind.Text), new(PlanKind.Text), new(PlanKind.Int64)], null),
                new([new(PlanKind.Text), new(PlanKind.Text), new(PlanKind.Int64)], null),
                new([new(PlanKind.Text), new(PlanKind.Text, true), new(PlanKind.Text), new(PlanKind.Text), new(PlanKind.Text), new(PlanKind.Text), new(PlanKind.Int64), new(PlanKind.Int64), new(PlanKind.Int64)], null),
                new([new(PlanKind.Scope), new(PlanKind.Int64)], null),
                new([new(PlanKind.Text), new(PlanKind.Text), new(PlanKind.Text), new(PlanKind.Int64), new(PlanKind.Text), new(PlanKind.Text), new(PlanKind.Text, true), new(PlanKind.Text), new(PlanKind.Text, true), new(PlanKind.Int64)], null),
                new([new(PlanKind.Text), new(PlanKind.Scope), new(PlanKind.Scope)], null),
                new([new(PlanKind.Int64)], null),
                new([new(PlanKind.Text), new(PlanKind.Int64), new(PlanKind.Text), new(PlanKind.Bytes), new(PlanKind.Int64)], null),
                new([new(PlanKind.Text)], null)
            ]);

        public static readonly PlanDefinition CredentialTouch = new(
            "identity.credential-touch",
            1,
            PlanAccess.Write,
            0,
            [
                new([new(PlanKind.Int64), new(PlanKind.Text), new(PlanKind.Text), new(PlanKind.Int64)], null)
            ]);

        public static readonly PlanDefinition UserLoad = new(
            "identity.user-load",
            1,
            PlanAccess.Read,
            1,
            [
                new([new(PlanKind.Text), new(PlanKind.Text)], [new(PlanKind.Text), new(PlanKind.Text), new(PlanKind.Int64), new(PlanKind.Int64), new(PlanKind.Int64, true), new(PlanKind.Int64)])
            ]);

        public static readonly PlanDefinition UserRename = new(
            "identity.user-rename",
            1,
            PlanAccess.Write,
            0,
            [
                new([new(PlanKind.Text), new(PlanKind.Text), new(PlanKind.Text), new(PlanKind.Int64)], null),
                new([new(PlanKind.Text), new(PlanKind.Text), new(PlanKind.Text), new(PlanKind.Int64)], null),
                new([new(PlanKind.Text), new(PlanKind.Text, true), new(PlanKind.Text), new(PlanKind.Text), new(PlanKind.Text), new(PlanKind.Text), new(PlanKind.Int64), new(PlanKind.Int64), new(PlanKind.Int64)], null),
                new([new(PlanKind.Scope), new(PlanKind.Int64)], null),
                new([new(PlanKind.Text), new(PlanKind.Text), new(PlanKind.Text), new(PlanKind.Int64), new(PlanKind.Text), new(PlanKind.Text), new(PlanKind.Text, true), new(PlanKind.Text), new(PlanKind.Text, true), new(PlanKind.Int64)], null),
                new([new(PlanKind.Text), new(PlanKind.Scope), new(PlanKind.Scope)], null),
                new([new(PlanKind.Int64)], null),
                new([new(PlanKind.Text), new(PlanKind.Int64), new(PlanKind.Text), new(PlanKind.Bytes), new(PlanKind.Int64)], null),
                new([new(PlanKind.Text)], null)
            ]);
    }

    /// <summary>The reviewed plans of the entitlement owner (<c>storage/plans/entitlement</c>).</summary>
    internal static class Entitlement
    {
        public static readonly PlanDefinition ActivationsLoad = new(
            "entitlement.activations-load",
            1,
            PlanAccess.Read,
            100,
            [
                new([new(PlanKind.Scope), new(PlanKind.Int64)], [new(PlanKind.Text), new(PlanKind.Int64)])
            ]);

        public static readonly PlanDefinition Commit = new(
            "entitlement.commit",
            1,
            PlanAccess.Write,
            0,
            [
                new([new(PlanKind.Text), new(PlanKind.Scope), new(PlanKind.Int64)], null),
                new([new(PlanKind.Scope), new(PlanKind.Int64), new(PlanKind.Int64), new(PlanKind.Int64)], null),
                new([new(PlanKind.Scope), new(PlanKind.Text)], null),
                new([new(PlanKind.Text)], null),
                new([new(PlanKind.Scope), new(PlanKind.Text)], null),
                new([new(PlanKind.Text)], null),
                new([new(PlanKind.Scope), new(PlanKind.Text)], null),
                new([new(PlanKind.Scope), new(PlanKind.Text)], null),
                new([new(PlanKind.Scope), new(PlanKind.Int64), new(PlanKind.Int64), new(PlanKind.Int64), new(PlanKind.Text), new(PlanKind.Text), new(PlanKind.Text)], null),
                new([new(PlanKind.Text), new(PlanKind.Text, true), new(PlanKind.Text), new(PlanKind.Text), new(PlanKind.Text), new(PlanKind.Text), new(PlanKind.Int64), new(PlanKind.Int64), new(PlanKind.Int64)], null),
                new([new(PlanKind.Scope), new(PlanKind.Int64)], null),
                new([new(PlanKind.Text), new(PlanKind.Text), new(PlanKind.Text), new(PlanKind.Int64), new(PlanKind.Text), new(PlanKind.Text), new(PlanKind.Text, true), new(PlanKind.Text), new(PlanKind.Text, true), new(PlanKind.Int64)], null),
                new([new(PlanKind.Text), new(PlanKind.Scope), new(PlanKind.Scope)], null),
                new([new(PlanKind.Int64)], null),
                new([new(PlanKind.Text), new(PlanKind.Int64), new(PlanKind.Text), new(PlanKind.Bytes), new(PlanKind.Int64)], null),
                new([new(PlanKind.Text)], null)
            ]);

        public static readonly PlanDefinition FeatureReleaseAppend = new(
            "entitlement.feature-release-append",
            1,
            PlanAccess.Write,
            0,
            [
                new([new(PlanKind.Scope), new(PlanKind.Int64)], null)
            ]);

        public static readonly PlanDefinition FeatureReleaseGet = new(
            "entitlement.feature-release-get",
            1,
            PlanAccess.Read,
            1,
            [
                new([new(PlanKind.Scope)], [new(PlanKind.Int64)])
            ]);

        public static readonly PlanDefinition FeatureReleasesLoad = new(
            "entitlement.feature-releases-load",
            1,
            PlanAccess.Read,
            100,
            [
                new([new(PlanKind.Scope), new(PlanKind.Text)], [new(PlanKind.Text), new(PlanKind.Int64)])
            ]);

        public static readonly PlanDefinition GrantsLoad = new(
            "entitlement.grants-load",
            1,
            PlanAccess.Read,
            100,
            [
                new([new(PlanKind.Scope), new(PlanKind.Int64), new(PlanKind.Int64), new(PlanKind.Text)], [new(PlanKind.Text), new(PlanKind.Int64), new(PlanKind.Text), new(PlanKind.Text), new(PlanKind.Int64), new(PlanKind.Text, true), new(PlanKind.Int64), new(PlanKind.Int64, true), new(PlanKind.Text), new(PlanKind.Int64), new(PlanKind.Text, true)])
            ]);

        public static readonly PlanDefinition RevisionLoad = new(
            "entitlement.revision-load",
            1,
            PlanAccess.Read,
            1,
            [
                new([new(PlanKind.Scope)], [new(PlanKind.Int64)])
            ]);

        public static readonly PlanDefinition RevocationsLoad = new(
            "entitlement.revocations-load",
            1,
            PlanAccess.Read,
            100,
            [
                new([new(PlanKind.Scope), new(PlanKind.Int64), new(PlanKind.Text)], [new(PlanKind.Text), new(PlanKind.Text), new(PlanKind.Text), new(PlanKind.Int64), new(PlanKind.Text), new(PlanKind.Int64)])
            ]);

        public static readonly PlanDefinition SnapshotLoad = new(
            "entitlement.snapshot-load",
            1,
            PlanAccess.Read,
            1,
            [
                new([new(PlanKind.Scope)], [new(PlanKind.Int64), new(PlanKind.Int64), new(PlanKind.Int64, true), new(PlanKind.Text), new(PlanKind.Text), new(PlanKind.Text)])
            ]);

        public static readonly PlanDefinition StatusFactsLoad = new(
            "entitlement.status-facts-load",
            1,
            PlanAccess.Read,
            100,
            [
                new([new(PlanKind.Scope), new(PlanKind.Int64), new(PlanKind.Text)], [new(PlanKind.Text), new(PlanKind.Int64), new(PlanKind.Int64), new(PlanKind.Int64), new(PlanKind.Int64)])
            ]);

        public static readonly PlanDefinition TermActionsLoad = new(
            "entitlement.term-actions-load",
            1,
            PlanAccess.Read,
            100,
            [
                new([new(PlanKind.Scope), new(PlanKind.Int64), new(PlanKind.Text)], [new(PlanKind.Text), new(PlanKind.Text), new(PlanKind.Int64), new(PlanKind.Int64), new(PlanKind.Int64)])
            ]);

        public static readonly PlanDefinition TermsLoad = new(
            "entitlement.terms-load",
            1,
            PlanAccess.Read,
            100,
            [
                new([new(PlanKind.Scope), new(PlanKind.Int64), new(PlanKind.Text)], [new(PlanKind.Text), new(PlanKind.Int64), new(PlanKind.Int64), new(PlanKind.Int64), new(PlanKind.Int64, true), new(PlanKind.Int64), new(PlanKind.Int64)])
            ]);
    }

    /// <summary>The reviewed plans of the commerce owner (<c>storage/plans/commerce</c>).</summary>
    internal static class Commerce
    {
        public static readonly PlanDefinition CatalogueEffective = new(
            "commerce.catalogue-effective",
            1,
            PlanAccess.Read,
            1,
            [
                new([new(PlanKind.Text), new(PlanKind.Int64), new(PlanKind.Int64)], [new(PlanKind.Text), new(PlanKind.Int64), new(PlanKind.Text), new(PlanKind.Text), new(PlanKind.Bool), new(PlanKind.Text), new(PlanKind.Int64), new(PlanKind.Text), new(PlanKind.Int64), new(PlanKind.Text), new(PlanKind.Text), new(PlanKind.Text), new(PlanKind.Int64), new(PlanKind.Int64, true), new(PlanKind.Text)])
            ]);

        public static readonly PlanDefinition CatalogueList = new(
            "commerce.catalogue-list",
            1,
            PlanAccess.Read,
            101,
            [
                new([new(PlanKind.Text), new(PlanKind.Int64), new(PlanKind.Int64), new(PlanKind.Int64)], [new(PlanKind.Text), new(PlanKind.Int64), new(PlanKind.Text), new(PlanKind.Text), new(PlanKind.Bool), new(PlanKind.Text), new(PlanKind.Int64), new(PlanKind.Text), new(PlanKind.Int64), new(PlanKind.Text), new(PlanKind.Text), new(PlanKind.Text), new(PlanKind.Int64), new(PlanKind.Int64, true), new(PlanKind.Text)])
            ]);

        public static readonly PlanDefinition CataloguePrice = new(
            "commerce.catalogue-price",
            1,
            PlanAccess.Read,
            1,
            [
                new([new(PlanKind.Text)], [new(PlanKind.Text), new(PlanKind.Int64), new(PlanKind.Text), new(PlanKind.Text), new(PlanKind.Bool), new(PlanKind.Text), new(PlanKind.Int64), new(PlanKind.Text), new(PlanKind.Int64), new(PlanKind.Text), new(PlanKind.Text), new(PlanKind.Text), new(PlanKind.Int64), new(PlanKind.Int64, true), new(PlanKind.Text)])
            ]);

        public static readonly PlanDefinition CataloguePublish = new(
            "commerce.catalogue-publish",
            1,
            PlanAccess.Write,
            0,
            [
                new([new(PlanKind.Text), new(PlanKind.Text), new(PlanKind.Int64), new(PlanKind.Text), new(PlanKind.Text), new(PlanKind.Bool), new(PlanKind.Text), new(PlanKind.Int64), new(PlanKind.Text), new(PlanKind.Int64), new(PlanKind.Int64), new(PlanKind.Int64)], null),
                new([new(PlanKind.Text), new(PlanKind.Int64), new(PlanKind.Text), new(PlanKind.Text), new(PlanKind.Bool), new(PlanKind.Text), new(PlanKind.Int64), new(PlanKind.Int64)], null),
                new([new(PlanKind.Text), new(PlanKind.Text), new(PlanKind.Int64), new(PlanKind.Text), new(PlanKind.Text), new(PlanKind.Text), new(PlanKind.Int64), new(PlanKind.Int64), new(PlanKind.Text)], null),
                new([new(PlanKind.Text), new(PlanKind.Text, true), new(PlanKind.Text), new(PlanKind.Text), new(PlanKind.Text), new(PlanKind.Text), new(PlanKind.Int64), new(PlanKind.Int64), new(PlanKind.Int64)], null),
                new([new(PlanKind.Int64)], null),
                new([new(PlanKind.Text), new(PlanKind.Int64), new(PlanKind.Text), new(PlanKind.Bytes), new(PlanKind.Int64)], null),
                new([new(PlanKind.Text)], null)
            ]);

        public static readonly PlanDefinition CatalogueState = new(
            "commerce.catalogue-state",
            1,
            PlanAccess.Read,
            1,
            [
                new([new(PlanKind.Text)], [new(PlanKind.Text), new(PlanKind.Int64), new(PlanKind.Text), new(PlanKind.Text), new(PlanKind.Bool), new(PlanKind.Text), new(PlanKind.Int64), new(PlanKind.Int64), new(PlanKind.Int64)])
            ]);
    }

    /// <summary>The reviewed plans of the platform owner (<c>storage/plans/platform</c>).</summary>
    internal static class Platform
    {
        public static readonly PlanDefinition ArchiveAck = new(
            "platform.archive-ack",
            1,
            PlanAccess.Write,
            0,
            [
                new([new(PlanKind.Text), new(PlanKind.Int64), new(PlanKind.Int64), new(PlanKind.Int64), new(PlanKind.Int64), new(PlanKind.Int64), new(PlanKind.Int64), new(PlanKind.Int64)], null),
                new([new(PlanKind.Int64), new(PlanKind.Text), new(PlanKind.Int64), new(PlanKind.Int64), new(PlanKind.Int64), new(PlanKind.Int64)], null),
                new([new(PlanKind.Text)], null)
            ]);

        public static readonly PlanDefinition ArchivePurge = new(
            "platform.archive-purge",
            1,
            PlanAccess.Write,
            0,
            [
                new([new(PlanKind.Text), new(PlanKind.Int64)], null),
                new([new(PlanKind.Int64), new(PlanKind.Int64)], null),
                new([new(PlanKind.Text)], null)
            ]);

        public static readonly PlanDefinition ArchiveSelect = new(
            "platform.archive-select",
            1,
            PlanAccess.Read,
            100,
            [
                new([new(PlanKind.Int64), new(PlanKind.Int64)], [new(PlanKind.Int64), new(PlanKind.Text), new(PlanKind.Int64), new(PlanKind.Text), new(PlanKind.Bytes), new(PlanKind.Int64)])
            ]);

        public static readonly PlanDefinition ArchiveState = new(
            "platform.archive-state",
            1,
            PlanAccess.Read,
            1,
            [
                new([], [new(PlanKind.Int64), new(PlanKind.Int64), new(PlanKind.Int64), new(PlanKind.Int64), new(PlanKind.Text, true)])
            ]);

        public static readonly PlanDefinition CommandLoad = new(
            "platform.command-load",
            1,
            PlanAccess.Read,
            1,
            [
                new([new(PlanKind.Text)], [new(PlanKind.Text), new(PlanKind.Int64), new(PlanKind.Text, true), new(PlanKind.Int64, true), new(PlanKind.Text, true), new(PlanKind.Int64), new(PlanKind.Text), new(PlanKind.Text), new(PlanKind.Text, true)])
            ]);

        public static readonly PlanDefinition CommandRecordFailure = new(
            "platform.command-record-failure",
            1,
            PlanAccess.Write,
            0,
            [
                new([new(PlanKind.Text), new(PlanKind.Text, true), new(PlanKind.Text), new(PlanKind.Text), new(PlanKind.Text), new(PlanKind.Text), new(PlanKind.Int64), new(PlanKind.Int64)], null)
            ]);

        public static readonly PlanDefinition InboxLoad = new(
            "platform.inbox-load",
            1,
            PlanAccess.Read,
            1,
            [
                new([new(PlanKind.Text), new(PlanKind.Text)], [new(PlanKind.Int64, true), new(PlanKind.Int64, true)])
            ]);

        public static readonly PlanDefinition InboxRecord = new(
            "platform.inbox-record",
            1,
            PlanAccess.Write,
            0,
            [
                new([new(PlanKind.Text), new(PlanKind.Text), new(PlanKind.Int64), new(PlanKind.Int64), new(PlanKind.Int64), new(PlanKind.Int64)], null)
            ]);

        public static readonly PlanDefinition OutboxAck = new(
            "platform.outbox-ack",
            1,
            PlanAccess.Write,
            0,
            [
                new([new(PlanKind.Text), new(PlanKind.Scope), new(PlanKind.Int64), new(PlanKind.Int64), new(PlanKind.Int64), new(PlanKind.Int64), new(PlanKind.Scope), new(PlanKind.Int64), new(PlanKind.Int64), new(PlanKind.Int64)], null),
                new([new(PlanKind.Int64), new(PlanKind.Scope), new(PlanKind.Int64), new(PlanKind.Int64)], null),
                new([new(PlanKind.Int64), new(PlanKind.Text), new(PlanKind.Int64), new(PlanKind.Scope), new(PlanKind.Int64), new(PlanKind.Int64), new(PlanKind.Int64)], null),
                new([new(PlanKind.Text)], null)
            ]);

        public static readonly PlanDefinition OutboxAttempt = new(
            "platform.outbox-attempt",
            1,
            PlanAccess.Write,
            0,
            [
                new([new(PlanKind.Text), new(PlanKind.Text), new(PlanKind.Scope), new(PlanKind.Int64), new(PlanKind.Int64)], null),
                new([new(PlanKind.Text), new(PlanKind.Int64)], null),
                new([new(PlanKind.Text)], null)
            ]);

        public static readonly PlanDefinition OutboxDeadLetter = new(
            "platform.outbox-dead-letter",
            1,
            PlanAccess.Write,
            0,
            [
                new([new(PlanKind.Text), new(PlanKind.Text), new(PlanKind.Scope), new(PlanKind.Int64), new(PlanKind.Int64)], null),
                new([new(PlanKind.Text), new(PlanKind.Int64)], null),
                new([new(PlanKind.Text)], null)
            ]);

        public static readonly PlanDefinition OutboxPurge = new(
            "platform.outbox-purge",
            1,
            PlanAccess.Write,
            0,
            [
                new([new(PlanKind.Text), new(PlanKind.Scope), new(PlanKind.Int64)], null),
                new([new(PlanKind.Scope), new(PlanKind.Int64), new(PlanKind.Scope), new(PlanKind.Int64)], null),
                new([new(PlanKind.Int64)], null),
                new([new(PlanKind.Text)], null)
            ]);

        public static readonly PlanDefinition OutboxRequeue = new(
            "platform.outbox-requeue",
            1,
            PlanAccess.Write,
            0,
            [
                new([new(PlanKind.Text), new(PlanKind.Text), new(PlanKind.Scope), new(PlanKind.Int64)], null),
                new([new(PlanKind.Text)], null),
                new([new(PlanKind.Text)], null)
            ]);

        public static readonly PlanDefinition OutboxSelect = new(
            "platform.outbox-select",
            1,
            PlanAccess.Read,
            50,
            [
                new([new(PlanKind.Scope), new(PlanKind.Int64), new(PlanKind.Int64)], [new(PlanKind.Int64), new(PlanKind.Text), new(PlanKind.Text), new(PlanKind.Text), new(PlanKind.Int64), new(PlanKind.Text), new(PlanKind.Text), new(PlanKind.Text, true), new(PlanKind.Text), new(PlanKind.Text, true), new(PlanKind.Int64), new(PlanKind.Int64), new(PlanKind.Int64)])
            ]);

        public static readonly PlanDefinition StreamFence = new(
            "platform.stream-fence",
            1,
            PlanAccess.Write,
            0,
            [
                new([new(PlanKind.Text), new(PlanKind.Scope), new(PlanKind.Int64)], null),
                new([new(PlanKind.Int64), new(PlanKind.Scope), new(PlanKind.Int64)], null),
                new([new(PlanKind.Text)], null)
            ]);

        public static readonly PlanDefinition StreamLoad = new(
            "platform.stream-load",
            1,
            PlanAccess.Read,
            1,
            [
                new([new(PlanKind.Scope)], [new(PlanKind.Int64), new(PlanKind.Int64), new(PlanKind.Int64), new(PlanKind.Int64), new(PlanKind.Text, true)])
            ]);
    }

    /// <summary>The reviewed plans of the foundation owner (<c>storage/plans/foundation</c>).</summary>
    internal static class Foundation
    {
        public static readonly PlanDefinition AccountLoad = new(
            "foundation.account-load",
            1,
            PlanAccess.Read,
            1,
            [
                new([new(PlanKind.Scope), new(PlanKind.Text)], [new(PlanKind.Int64), new(PlanKind.Int64)])
            ]);

        public static readonly PlanDefinition AccountSeed = new(
            "foundation.account-seed",
            1,
            PlanAccess.Write,
            0,
            [
                new([new(PlanKind.Scope), new(PlanKind.Text), new(PlanKind.Int64)], null)
            ]);

        public static readonly PlanDefinition ExactLoad = new(
            "foundation.exact-load",
            1,
            PlanAccess.Read,
            1,
            [
                new([new(PlanKind.Scope), new(PlanKind.Text)], [new(PlanKind.Int64), new(PlanKind.Uint64), new(PlanKind.Decimal), new(PlanKind.Bytes, true), new(PlanKind.Int64)])
            ]);

        public static readonly PlanDefinition ExactStore = new(
            "foundation.exact-store",
            1,
            PlanAccess.Write,
            0,
            [
                new([new(PlanKind.Text), new(PlanKind.Scope), new(PlanKind.Text), new(PlanKind.Int64)], null),
                new([new(PlanKind.Scope), new(PlanKind.Text), new(PlanKind.Int64), new(PlanKind.Uint64), new(PlanKind.Decimal), new(PlanKind.Bytes, true), new(PlanKind.Int64)], null),
                new([new(PlanKind.Scope), new(PlanKind.Text), new(PlanKind.Text), new(PlanKind.Text)], null),
                new([new(PlanKind.Text)], null)
            ]);

        public static readonly PlanDefinition InboxSeen = new(
            "foundation.inbox-seen",
            1,
            PlanAccess.Read,
            1,
            [
                new([new(PlanKind.Scope), new(PlanKind.Text), new(PlanKind.Int64)], [new(PlanKind.Int64)])
            ]);

        public static readonly PlanDefinition JobClaim = new(
            "foundation.job-claim",
            1,
            PlanAccess.Write,
            0,
            [
                new([new(PlanKind.Text), new(PlanKind.Scope), new(PlanKind.Text), new(PlanKind.Int64), new(PlanKind.Text)], null),
                new([new(PlanKind.Text), new(PlanKind.Int64), new(PlanKind.Scope), new(PlanKind.Text)], null),
                new([new(PlanKind.Text)], null)
            ]);

        public static readonly PlanDefinition JobCommit = new(
            "foundation.job-commit",
            1,
            PlanAccess.Write,
            0,
            [
                new([new(PlanKind.Text), new(PlanKind.Scope), new(PlanKind.Text), new(PlanKind.Int64), new(PlanKind.Text), new(PlanKind.Int64), new(PlanKind.Int64)], null),
                new([new(PlanKind.Scope), new(PlanKind.Text), new(PlanKind.Text)], null),
                new([new(PlanKind.Int64), new(PlanKind.Uint64), new(PlanKind.Int64), new(PlanKind.Scope), new(PlanKind.Text), new(PlanKind.Int64)], null),
                new([new(PlanKind.Scope), new(PlanKind.Text), new(PlanKind.Int64)], null),
                new([new(PlanKind.Scope), new(PlanKind.Text), new(PlanKind.Text), new(PlanKind.Text)], null),
                new([new(PlanKind.Text)], null)
            ]);

        public static readonly PlanDefinition JobItems = new(
            "foundation.job-items",
            1,
            PlanAccess.Read,
            1,
            [
                new([new(PlanKind.Scope), new(PlanKind.Text)], [new(PlanKind.Int64), new(PlanKind.Int64)])
            ]);

        public static readonly PlanDefinition JobLoad = new(
            "foundation.job-load",
            1,
            PlanAccess.Read,
            1,
            [
                new([new(PlanKind.Scope), new(PlanKind.Text)], [new(PlanKind.Int64), new(PlanKind.Int64), new(PlanKind.Int64), new(PlanKind.Text, true), new(PlanKind.Int64, true), new(PlanKind.Text), new(PlanKind.Uint64), new(PlanKind.Int64)])
            ]);

        public static readonly PlanDefinition JobStart = new(
            "foundation.job-start",
            1,
            PlanAccess.Write,
            0,
            [
                new([new(PlanKind.Scope), new(PlanKind.Text), new(PlanKind.Int64)], null),
                new([new(PlanKind.Scope), new(PlanKind.Text), new(PlanKind.Text), new(PlanKind.Text)], null)
            ]);

        public static readonly PlanDefinition OutboxState = new(
            "foundation.outbox-state",
            1,
            PlanAccess.Read,
            1,
            [
                new([new(PlanKind.Scope)], [new(PlanKind.Int64), new(PlanKind.Int64)])
            ]);

        public static readonly PlanDefinition Readiness = new(
            "foundation.readiness",
            1,
            PlanAccess.Read,
            1,
            [
                new([], [new(PlanKind.Int64)])
            ]);

        public static readonly PlanDefinition ReceiptLoad = new(
            "foundation.receipt-load",
            1,
            PlanAccess.Read,
            1,
            [
                new([new(PlanKind.Scope), new(PlanKind.Text)], [new(PlanKind.Text), new(PlanKind.Text)])
            ]);

        public static readonly PlanDefinition SessionCreate = new(
            "foundation.session-create",
            1,
            PlanAccess.Write,
            0,
            [
                new([new(PlanKind.Scope), new(PlanKind.Text), new(PlanKind.Bytes), new(PlanKind.Text), new(PlanKind.Text), new(PlanKind.Text), new(PlanKind.Int64), new(PlanKind.Int64), new(PlanKind.Int64), new(PlanKind.Int64), new(PlanKind.Int64), new(PlanKind.Int64)], null),
                new([new(PlanKind.Scope), new(PlanKind.Text), new(PlanKind.Text), new(PlanKind.Text)], null)
            ]);

        public static readonly PlanDefinition SessionLoad = new(
            "foundation.session-load",
            1,
            PlanAccess.Read,
            1,
            [
                new([new(PlanKind.Scope), new(PlanKind.Bytes)], [new(PlanKind.Text), new(PlanKind.Text), new(PlanKind.Text), new(PlanKind.Text), new(PlanKind.Int64), new(PlanKind.Int64), new(PlanKind.Int64), new(PlanKind.Int64), new(PlanKind.Int64), new(PlanKind.Int64), new(PlanKind.Int64, true), new(PlanKind.Text, true)])
            ]);

        public static readonly PlanDefinition SessionLoadById = new(
            "foundation.session-load-by-id",
            1,
            PlanAccess.Read,
            1,
            [
                new([new(PlanKind.Scope), new(PlanKind.Text)], [new(PlanKind.Text), new(PlanKind.Text), new(PlanKind.Text), new(PlanKind.Text), new(PlanKind.Int64), new(PlanKind.Int64), new(PlanKind.Int64), new(PlanKind.Int64), new(PlanKind.Int64), new(PlanKind.Int64), new(PlanKind.Int64, true), new(PlanKind.Text, true)])
            ]);

        public static readonly PlanDefinition SessionRevoke = new(
            "foundation.session-revoke",
            1,
            PlanAccess.Write,
            0,
            [
                new([new(PlanKind.Text), new(PlanKind.Scope), new(PlanKind.Text)], null),
                new([new(PlanKind.Int64), new(PlanKind.Text), new(PlanKind.Scope), new(PlanKind.Text)], null),
                new([new(PlanKind.Scope), new(PlanKind.Text), new(PlanKind.Text), new(PlanKind.Text)], null),
                new([new(PlanKind.Text)], null)
            ]);

        public static readonly PlanDefinition SessionTouch = new(
            "foundation.session-touch",
            1,
            PlanAccess.Write,
            0,
            [
                new([new(PlanKind.Int64), new(PlanKind.Int64), new(PlanKind.Scope), new(PlanKind.Bytes), new(PlanKind.Int64), new(PlanKind.Int64)], null)
            ]);

        public static readonly PlanDefinition Transfer = new(
            "foundation.transfer",
            1,
            PlanAccess.Write,
            0,
            [
                new([new(PlanKind.Text), new(PlanKind.Scope), new(PlanKind.Text), new(PlanKind.Int64), new(PlanKind.Int64), new(PlanKind.Scope), new(PlanKind.Text), new(PlanKind.Int64)], null),
                new([new(PlanKind.Int64), new(PlanKind.Scope), new(PlanKind.Text), new(PlanKind.Int64)], null),
                new([new(PlanKind.Int64), new(PlanKind.Scope), new(PlanKind.Text), new(PlanKind.Int64)], null),
                new([new(PlanKind.Scope), new(PlanKind.Text), new(PlanKind.Text), new(PlanKind.Text)], null),
                new([new(PlanKind.Scope), new(PlanKind.Text), new(PlanKind.Text), new(PlanKind.Text)], null),
                new([new(PlanKind.Text)], null)
            ]);
    }

    /// <summary>The reviewed shared family plans (<c>storage/plans/families</c>); <see cref="FamilyPlans"/> describes their statements.</summary>
    internal static class Families
    {
        public static readonly PlanDefinition AccountEnrollmentCreateUser = new(
            "families.account-enrollment.create-user",
            1,
            PlanAccess.Write,
            0,
            [
                new([new(PlanKind.Text), new(PlanKind.Text), new(PlanKind.Int64)], null),
                new([new(PlanKind.Text), new(PlanKind.Text), new(PlanKind.Text), new(PlanKind.Text), new(PlanKind.Int64)], null),
                new([new(PlanKind.Text), new(PlanKind.Text), new(PlanKind.Text), new(PlanKind.Int64)], null),
                new([new(PlanKind.Text), new(PlanKind.Text), new(PlanKind.Text), new(PlanKind.Int64)], null),
                new([new(PlanKind.Text), new(PlanKind.Scope), new(PlanKind.Int64)], null),
                new([new(PlanKind.Text), new(PlanKind.Text), new(PlanKind.Text), new(PlanKind.Int64)], null),
                new([new(PlanKind.Text), new(PlanKind.Text), new(PlanKind.Int64), new(PlanKind.Text), new(PlanKind.Bytes, true), new(PlanKind.Bytes, true), new(PlanKind.Int64), new(PlanKind.Int64), new(PlanKind.Text, true), new(PlanKind.Int64), new(PlanKind.Text, true), new(PlanKind.Int64), new(PlanKind.Text), new(PlanKind.Text), new(PlanKind.Text, true)], null),
                new([new(PlanKind.Scope), new(PlanKind.Text), new(PlanKind.Text), new(PlanKind.Text), new(PlanKind.Text), new(PlanKind.Int64)], null),
                new([new(PlanKind.Text), new(PlanKind.Text, true), new(PlanKind.Text), new(PlanKind.Text), new(PlanKind.Text), new(PlanKind.Text), new(PlanKind.Int64), new(PlanKind.Int64), new(PlanKind.Int64)], null),
                new([new(PlanKind.Scope), new(PlanKind.Int64)], null),
                new([new(PlanKind.Text), new(PlanKind.Text), new(PlanKind.Text), new(PlanKind.Int64), new(PlanKind.Text), new(PlanKind.Text), new(PlanKind.Text, true), new(PlanKind.Text), new(PlanKind.Text, true), new(PlanKind.Int64)], null),
                new([new(PlanKind.Text), new(PlanKind.Scope), new(PlanKind.Scope)], null),
                new([new(PlanKind.Int64)], null),
                new([new(PlanKind.Text), new(PlanKind.Int64), new(PlanKind.Text), new(PlanKind.Bytes), new(PlanKind.Int64)], null),
                new([new(PlanKind.Text)], null)
            ]);
    }

    public static readonly IReadOnlyList<PlanDefinition> All = [Identity.CredentialAdd, Identity.CredentialFind, Identity.CredentialList, Identity.CredentialRelabel, Identity.CredentialRevoke, Identity.CredentialTouch, Identity.UserLoad, Identity.UserRename, Entitlement.ActivationsLoad, Entitlement.Commit, Entitlement.FeatureReleaseAppend, Entitlement.FeatureReleaseGet, Entitlement.FeatureReleasesLoad, Entitlement.GrantsLoad, Entitlement.RevisionLoad, Entitlement.RevocationsLoad, Entitlement.SnapshotLoad, Entitlement.StatusFactsLoad, Entitlement.TermActionsLoad, Entitlement.TermsLoad, Commerce.CatalogueEffective, Commerce.CatalogueList, Commerce.CataloguePrice, Commerce.CataloguePublish, Commerce.CatalogueState, Platform.ArchiveAck, Platform.ArchivePurge, Platform.ArchiveSelect, Platform.ArchiveState, Platform.CommandLoad, Platform.CommandRecordFailure, Platform.InboxLoad, Platform.InboxRecord, Platform.OutboxAck, Platform.OutboxAttempt, Platform.OutboxDeadLetter, Platform.OutboxPurge, Platform.OutboxRequeue, Platform.OutboxSelect, Platform.StreamFence, Platform.StreamLoad, Foundation.AccountLoad, Foundation.AccountSeed, Foundation.ExactLoad, Foundation.ExactStore, Foundation.InboxSeen, Foundation.JobClaim, Foundation.JobCommit, Foundation.JobItems, Foundation.JobLoad, Foundation.JobStart, Foundation.OutboxState, Foundation.Readiness, Foundation.ReceiptLoad, Foundation.SessionCreate, Foundation.SessionLoad, Foundation.SessionLoadById, Foundation.SessionRevoke, Foundation.SessionTouch, Foundation.Transfer, Families.AccountEnrollmentCreateUser];

    /// <summary>The closed registry of shared transaction families (<c>storage/plans/families.json</c>, Design SU-01).</summary>
    public static readonly IReadOnlyList<FamilyDefinition> FamilyCatalog = [
        new("account-enrollment", "Authentication/enrollment completion and default workspace provisioning", "data model 00 section 6.1.1 (SU-01 row 'Authentication/enrollment completion and default workspace provisioning'); Device, Entitlement and Notification are conditional here because their tasks append their own plans of this family (CLOUD.11 planning repair, Design #248)", [new(FamilyModule.Identity, true, null), new(FamilyModule.Workspace, true, null), new(FamilyModule.Device, false, "when the completion creates the first installation and session (CLOUD.12, CLOUD.13)"), new(FamilyModule.Entitlement, false, "when configured initial grants apply to a new user"), new(FamilyModule.Notification, false, "when the completion queues a security notification (CLOUD.12)")])
    ];

    /// <summary>The statement roles of every shared family plan, in plan order.</summary>
    public static readonly IReadOnlyList<FamilyPlanDefinition> FamilyPlans = [
        new(Families.AccountEnrollmentCreateUser, "account-enrollment", [
            new(FamilyModule.Identity, FamilyPhase.Guard, FamilyClass.Revision, "credential-id"),
            new(FamilyModule.Identity, FamilyPhase.Guard, FamilyClass.Revision, "credential-subject"),
            new(FamilyModule.Identity, FamilyPhase.Guard, FamilyClass.Revision, "user"),
            new(FamilyModule.Workspace, FamilyPhase.Guard, FamilyClass.Revision, "owner"),
            new(FamilyModule.Workspace, FamilyPhase.Guard, FamilyClass.Revision, "workspace"),
            new(FamilyModule.Identity, FamilyPhase.Mutation, FamilyClass.Record, "account"),
            new(FamilyModule.Identity, FamilyPhase.Mutation, FamilyClass.Record, "credential"),
            new(FamilyModule.Workspace, FamilyPhase.Mutation, FamilyClass.Record, "workspace"),
            new(FamilyModule.Platform, FamilyPhase.Mutation, FamilyClass.Record, "a-receipt"),
            new(FamilyModule.Platform, FamilyPhase.Mutation, FamilyClass.Record, "b-stream"),
            new(FamilyModule.Platform, FamilyPhase.Mutation, FamilyClass.Record, "c-outbox"),
            new(FamilyModule.Platform, FamilyPhase.Mutation, FamilyClass.Record, "d-position"),
            new(FamilyModule.Platform, FamilyPhase.Mutation, FamilyClass.Record, "e-archive-stream"),
            new(FamilyModule.Platform, FamilyPhase.Mutation, FamilyClass.Record, "f-archive"),
            new(FamilyModule.Platform, FamilyPhase.Release, FamilyClass.Release, "release")
        ])
    ];
}
