// SPDX-License-Identifier: AGPL-3.0-only
using System.Text.Json.Nodes;
using System.Text.RegularExpressions;
using System.Xml.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace ArcForges.Cloud.ArchitectureTests.AiHarness;

/// <summary>The rule bodies of the GOV.10 successor (one method per obligation family).</summary>
internal static partial class HarnessArchitecture
{
    private const string ApacheBoundary = "Apache";
    private const string AgplBoundary = "AGPL";

    private static readonly string[] StoreKinds = ["d1_databases", "r2_buckets", "kv_namespaces", "hyperdrive"];

    private static readonly string[] AdapterStoreTypes = ["D1Database", "R2Bucket", "KVNamespace", "Hyperdrive", "Queue"];

    private static readonly string[] DurableObjectTypes = ["DurableObject", "DurableObjectNamespace", "DurableObjectState"];

    private static readonly string[] CodecFunctions = ["create", "fromBinary", "toBinary", "fromJson", "toJson", "fromJsonString", "toJsonString", "clone", "equals"];

    private static readonly string[] MoneyParts =
    [
        "credit", "credits", "balance", "balances", "money", "price", "prices", "amount", "amounts", "cost", "costs", "charge", "charges",
        "billing", "currency", "fee", "fees", "invoice", "payment", "payments", "refund", "usd", "cent", "cents", "tax",
    ];

    private static readonly string[] WireCodecNames = ["CodedOutputStream", "CodedInputStream", "WireFormat", "WriteVarint", "ReadVarint", "WriteTag", "ReadTag", "WriteRawVarint32"];

    private static readonly string[] ProviderNamespaces = ["OpenAI", "Anthropic", "Mistral", "Cohere", "Groq", "Ollama", "Replicate", "LangChain"];

    private static readonly Regex ProviderPackage = new(
        @"^(?:openai|@openai/|@anthropic-ai/|@google/(?:genai|generative-ai)|@google-cloud/(?:vertexai|aiplatform)|@mistralai/|@aws-sdk/client-bedrock|@azure/openai|cohere-ai|groq-sdk|ollama|replicate|together-ai|langchain|@langchain/|ai$|@ai-sdk/)",
        RegexOptions.CultureInvariant);

    private static readonly Regex ProviderNuget = new(
        @"^(?:OpenAI|Anthropic|Mistral|Cohere|Groq|Ollama|Replicate|Azure\.AI\.OpenAI|Google\.Cloud\.AIPlatform|Amazon\.BedrockRuntime|AWSSDK\.BedrockRuntime|LangChain)(?:\.|$)",
        RegexOptions.CultureInvariant);

    private static readonly Regex ProviderHost = new(
        @"(?:api\.openai\.com|api\.anthropic\.com|generativelanguage\.googleapis\.com|api\.cohere\.(?:ai|com)|api\.mistral\.ai|api\.groq\.com|openrouter\.ai|api\.together\.xyz|api\.replicate\.com|bedrock-runtime|api\.cloudflare\.com/client/v4/accounts/[^/]+/ai)",
        RegexOptions.IgnoreCase | RegexOptions.CultureInvariant);

    private static readonly Regex WireCodecPackage = new(
        @"^(?:@bufbuild/protobuf/(?:wire|codegenv\d+|reflect)(?:/|$)|protobufjs(?:/|$)|google-protobuf(?:/|$)|@protobuf-ts/|ts-proto|pbf$|long$)",
        RegexOptions.CultureInvariant);

    private static readonly Regex SensitiveName = new(
        @"secret|token|passw|credential|api[_-]?key|authoriz|cookie|session|prompt|messages?|content|conversation|completion|transcript|payload|^env$|^headers$|^request$|^body$",
        RegexOptions.IgnoreCase | RegexOptions.CultureInvariant);

    private static readonly Regex ReflectionCall = new(@"\b(?:Activator\.CreateInstance|Assembly\.Load(?:From|File)?|Type\.GetType|DynamicMethod|ILGenerator)\b", RegexOptions.CultureInvariant);

    private static readonly Regex LoggingCall = new(@"(?:^|\.)(?:Console\.Write\w*|Debug\.Write\w*|Trace\.Write\w*)$|(?:^|\.)Log\w*$", RegexOptions.CultureInvariant);

    private static readonly Regex ExternalSpecifier = new(@"^(?:[a-z][a-z\d+.-]*://|file:|git\+|[A-Za-z]:[\\/]|/)", RegexOptions.IgnoreCase | RegexOptions.CultureInvariant);

    private static readonly Regex UnresolvedAllowed = new(@"\.(?:json|css|txt|md)$", RegexOptions.CultureInvariant);

    private static readonly Regex GeneratedSuffix = new(@"(?:Request|Response|Event|Reply|Command|Query)$", RegexOptions.CultureInvariant);

    private static readonly Regex ProtoSchemaFile = new(@"\.proto$|_pb\.(?:[cm]?[jt]s|d\.ts)$|\.pb\.[cm]?[jt]s$|_connect\.[cm]?[jt]s$|\.pb\.cs$|_pb\.cs$|\.binpb$", RegexOptions.CultureInvariant);

    private static readonly Regex ProtocHeader = new(@"@generated by protoc-gen|Generated by the protocol buffer compiler", RegexOptions.CultureInvariant);

    private static readonly Regex NamingPublication = new(@"^https://github\.com/ArcForges/Contracts/actions/runs/[1-9]\d*$", RegexOptions.CultureInvariant);

    private static readonly Regex Sha512Base64 = new(@"^[A-Za-z0-9+/]{86}==$", RegexOptions.CultureInvariant);

    private static readonly Regex Sha256Hex = new(@"^[0-9a-f]{64}$", RegexOptions.CultureInvariant);

    private static readonly Regex CommitHex = new(@"^[0-9a-f]{40}$", RegexOptions.CultureInvariant);

    private static readonly Regex ExactVersion = new(@"^\d+\.\d+\.\d+(?:-[\w.-]+)?$", RegexOptions.CultureInvariant);

    private static readonly Regex LicenceIdentifier = new(@"^[A-Za-z0-9.+-]+$", RegexOptions.CultureInvariant);

    private static readonly Regex IdentifierBoundary = new("([a-z0-9])([A-Z])", RegexOptions.CultureInvariant);

    // ---------------------------------------------------------------- WP-05.00 layering

    private static void LayerRules(Context c)
    {
        // layer-cycle: the project graph (resolved references among audited projects) must be acyclic.
        var graph = c.Projects.ToDictionary(
            p => p.Key,
            p => p.Value.ProjectReferences.Where(r => r.Resolved is not null && c.Projects.ContainsKey(r.Resolved)).Select(r => r.Resolved!).ToList(),
            StringComparer.Ordinal);
        foreach (var cycle in FindCycles(graph))
        {
            c.Report("layer-cycle", cycle[0], "Project reference cycle: " + string.Join(" -> ", cycle));
        }

        // layer-entry: no source project references the host entry.
        foreach (var project in c.Projects.Values.Where(p => p.Path.StartsWith("src/", StringComparison.Ordinal)))
        {
            if (project.ProjectReferences.Any(r => r.Resolved == HostEntry))
            {
                c.Report("layer-entry", project.Path, "References the host entry " + HostEntry);
            }
        }

        // layer-escape: project references stay inside the repository.
        foreach (var project in c.Projects.Values)
        {
            foreach (var reference in project.ProjectReferences.Where(r => r.Resolved is null))
            {
                c.Report("layer-escape", project.Path, "Project reference leaves the repository: " + reference.Raw);
            }
        }

        // layer-runtime-dependency: source projects use only centrally declared packages.
        var central = c.CentralPackages();
        foreach (var project in c.Projects.Values.Where(p => p.Path.StartsWith("src/", StringComparison.Ordinal)))
        {
            foreach (var package in project.PackageReferences.Where(p => !central.ContainsKey(p.Id)))
            {
                c.Report("layer-runtime-dependency", project.Path, "Package is not centrally declared: " + package.Id);
            }
        }

        // layer-product-reference: other owners are referenced only through the published Contracts packages.
        foreach (var project in c.Projects.Values.Where(p => p.Path.StartsWith("src/", StringComparison.Ordinal)))
        {
            foreach (var package in project.PackageReferences.Where(p => p.Id.StartsWith("ArcForges.", StringComparison.Ordinal)))
            {
                if (package.Id == NamingCandidate.PackageId || !package.Id.StartsWith("ArcForges.Contracts.", StringComparison.Ordinal))
                {
                    c.Report("layer-product-reference", project.Path, "Unadmitted ArcForges package in source: " + package.Id);
                }
            }
        }

        // layer-business-authority: a module references only its abstractions.
        foreach (var project in c.Projects.Values.Where(p => p.Path.StartsWith("src/ArcForges.Cloud.Modules.", StringComparison.Ordinal)
            && !p.Path.StartsWith("src/ArcForges.Cloud.Modules.Abstractions/", StringComparison.Ordinal)))
        {
            foreach (var reference in project.ProjectReferences.Where(r => r.Resolved is not null && !r.Resolved.StartsWith("src/ArcForges.Cloud.Modules.Abstractions/", StringComparison.Ordinal)
                && !r.Resolved.StartsWith(ModuleFolder(project.Path), StringComparison.Ordinal)))
            {
                c.Report("layer-business-authority", project.Path, "Module references a non-abstraction project: " + reference.Raw);
            }
        }

        ManifestProductReferences(c);
        WorkerImportGraph(c);
        WorkerConfiguration(c);
    }

    /// <summary>layer-product-reference for manifests: every ArcForges package a manifest names is the wire package, an admitted Contracts package or a project of this repository.</summary>
    private static void ManifestProductReferences(Context c)
    {
        var ownNames = ManifestPaths(c).Select(file => Str(Obj(ParseJson(c.Text(file)))?["name"])).OfType<string>().ToHashSet(StringComparer.Ordinal);
        foreach (var file in ManifestPaths(c))
        {
            var manifest = Obj(ParseJson(c.Text(file)));
            foreach (var section in ManifestSections)
            {
                foreach (var name in StringMap(manifest?[section]).Keys)
                {
                    if (name.StartsWith("@arcforges/", StringComparison.OrdinalIgnoreCase) && !AdmittedPackages.Contains(name) && !ownNames.Contains(name))
                    {
                        c.Report("layer-product-reference", file, "Unadmitted ArcForges package: " + name);
                    }
                }
            }
        }
    }

    /// <summary>The Worker import graph: unadmitted and absolute references, sibling escapes, entry imports, cycles and runtime dependencies.</summary>
    private static void WorkerImportGraph(Context c)
    {
        var runtime = RuntimeDependencies(c);
        var edges = new Dictionary<string, List<string>>(StringComparer.Ordinal);
        foreach (var file in c.TypeScript)
        {
            var targets = new List<string>();
            foreach (var reference in file.References)
            {
                var specifier = reference.Specifier;
                if (specifier is null)
                {
                    c.Report(file.Release ? "banned-dynamic-code" : "layer-escape", file.Path, "Computed " + FormName(reference) + " specifier needs explicit admission");
                    continue;
                }

                if (specifier.StartsWith("@arcforges/", StringComparison.Ordinal) && !AdmittedPackages.Contains(specifier) && !specifier.StartsWith(PublicWirePackage + "/", StringComparison.Ordinal))
                {
                    c.Report("layer-product-reference", file.Path, "Unadmitted ArcForges import: " + specifier);
                }

                if (ExternalSpecifier.IsMatch(specifier))
                {
                    c.Report("layer-escape", file.Path, "External or absolute import: " + specifier);
                }

                if (specifier.StartsWith('.'))
                {
                    var (escaped, resolved) = ResolveLocal(file.Path, specifier, c.Sources);
                    if (escaped)
                    {
                        c.Report("layer-escape", file.Path, "Sibling or parent checkout import: " + specifier);
                    }
                    else if (resolved is null && !UnresolvedAllowed.IsMatch(specifier))
                    {
                        c.Report("layer-escape", file.Path, "Unresolved local import: " + specifier);
                    }
                    else if (resolved is not null)
                    {
                        targets.Add(resolved);
                        if (file.Release && !IsRelease(resolved))
                        {
                            c.Report("layer-escape", file.Path, "Worker source reaches " + resolved);
                        }

                        if (resolved == WorkerEntry && file.Path != WorkerEntry)
                        {
                            c.Report("layer-entry", file.Path, "Imports the Worker entry: " + specifier);
                        }
                    }

                    continue;
                }

                if (!file.Release) continue;
                if (specifier.StartsWith("node:", StringComparison.Ordinal))
                {
                    c.Report("layer-runtime-dependency", file.Path, "Node built-in in the Worker path: " + specifier);
                }
                else if (specifier.StartsWith("cloudflare:", StringComparison.Ordinal))
                {
                    continue;
                }
                else if (!runtime.Contains(PackageName(specifier)))
                {
                    c.Report("layer-runtime-dependency", file.Path, "Not a declared runtime dependency: " + PackageName(specifier));
                }
            }

            edges[file.Path] = targets;
        }

        // layer-cycle: the release files form an acyclic import graph.
        var visiting = new HashSet<string>(StringComparer.Ordinal);
        var done = new HashSet<string>(StringComparer.Ordinal);
        void Walk(string file, List<string> stack)
        {
            if (done.Contains(file)) return;
            if (visiting.Contains(file))
            {
                var start = stack.IndexOf(file);
                c.Report("layer-cycle", file, "Import cycle: " + string.Join(" -> ", stack.Skip(start).Append(file)));
                return;
            }

            visiting.Add(file);
            foreach (var next in edges.GetValueOrDefault(file) ?? [])
            {
                if (IsRelease(next)) Walk(next, [.. stack, file]);
            }

            visiting.Remove(file);
            done.Add(file);
        }

        foreach (var file in edges.Keys.Where(IsRelease).Order(StringComparer.Ordinal))
        {
            Walk(file, []);
        }
    }

    /// <summary>
    /// The Worker configuration: no workers.dev or preview exposure, no route that exposes an internal path, and no store binding reachable
    /// from an adapter. Each environment is checked as well as the top level, so an environment cannot re-enable exposure.
    /// </summary>
    private static void WorkerConfiguration(Context c)
    {
        var wrangler = Obj(ParseJson(c.Text("wrangler.json")));
        if (wrangler is null)
        {
            c.Report("layer-public-exposure", "wrangler.json", "Worker configuration is missing");
            return;
        }

        var environments = new List<(string Name, JsonObject Object)> { ("top", wrangler) };
        if (Obj(wrangler["env"]) is { } env)
        {
            environments.AddRange(env.Where(entry => Obj(entry.Value) is not null).Select(entry => ("env." + entry.Key, Obj(entry.Value)!)));
        }

        var storeBindings = new List<string>();
        foreach (var (name, element) in environments)
        {
            var prefix = name == "top" ? string.Empty : name + " ";
            if (!IsFalse(element["workers_dev"]) && (name == "top" || element.ContainsKey("workers_dev")))
            {
                c.Report("layer-public-exposure", "wrangler.json", prefix + "workers_dev must be false");
            }

            if (!IsFalse(element["preview_urls"]) && (name == "top" || element.ContainsKey("preview_urls")))
            {
                c.Report("layer-public-exposure", "wrangler.json", prefix + "preview_urls must be false");
            }

            foreach (var key in new[] { "routes", "route" })
            {
                foreach (var pattern in RoutePatterns(element[key]))
                {
                    if (ExposesInternalPath(pattern))
                    {
                        c.Report("layer-public-exposure", "wrangler.json", prefix + "route exposes an internal path: " + pattern);
                    }
                }
            }

            foreach (var kind in StoreKinds)
            {
                if (element[kind] is JsonArray list)
                {
                    storeBindings.AddRange(list.Select(item => Str(Obj(item)?["binding"])).OfType<string>());
                }
            }

            if (Obj(element["queues"]) is { } queues && queues["producers"] is JsonArray producers)
            {
                storeBindings.AddRange(producers.Select(item => Str(Obj(item)?["binding"])).OfType<string>());
            }
        }

        foreach (var file in c.TypeScript.Where(file => IsAdapter(file.Path)))
        {
            foreach (var binding in storeBindings.Distinct(StringComparer.Ordinal))
            {
                if (file.Tokens.Any(token => token.Kind == TokenKind.Word && token.Value == binding))
                {
                    c.Report("layer-business-authority", file.Path, "Adapter reaches store binding " + binding);
                }
            }
        }
    }

    private static IEnumerable<string> RoutePatterns(JsonNode? node) => node switch
    {
        JsonArray list => list.Select(item => Str(item) ?? Str(Obj(item)?["pattern"])).OfType<string>(),
        JsonValue => [Str(node)!],
        _ => [],
    };

    /// <summary>A route exposes an internal path when its path begins with /internal or is a catch-all that covers every path.</summary>
    private static bool ExposesInternalPath(string pattern)
    {
        var slash = pattern.IndexOf('/', StringComparison.Ordinal);
        if (slash < 0) return false;
        var path = pattern[slash..];
        return path.StartsWith("/internal", StringComparison.Ordinal) || path == "/*";
    }

    private static string FormName(ModuleReference reference) => reference.Form switch
    {
        ModuleForm.Dynamic => "dynamic",
        ModuleForm.Require => "require",
        ModuleForm.Export => "export",
        _ => "import",
    };

    /// <summary>The Worker adapter folders: the Workers AI adapter and the Harness wake handle.</summary>
    private static bool IsAdapter(string path) => path.StartsWith(AdapterFolder, StringComparison.Ordinal) || path.StartsWith(HarnessFolder, StringComparison.Ordinal);

    private static IEnumerable<string> ManifestPaths(Context c) =>
        c.Sources.Keys.Where(path => path == "package.json" || path.EndsWith("/package.json", StringComparison.Ordinal)).Order(StringComparer.Ordinal);

    // ---------------------------------------------------------------- WP-05.01 licence

    private static void LicenceRules(Context c)
    {
        ManifestLicences(c);
        ProjectLicences(c);
        LockLicences(c);
    }

    /// <summary>The manifests: an SPDX identifier, an enumerated boundary, the inventory, the Apache set and the cross-boundary references.</summary>
    private static void ManifestLicences(Context c)
    {
        var inventoryText = c.Text("eng/policy/licence-boundary.json");
        var inventory = Obj(ParseJson(inventoryText));
        var rows = (inventory?["projects"] as JsonArray)?.Select(row => Obj(row)).OfType<JsonObject>().ToList() ?? [];
        var manifests = ManifestPaths(c).ToList();
        var projectNames = new Dictionary<string, string>(StringComparer.Ordinal);
        var boundaries = new Dictionary<string, string>(StringComparer.Ordinal);
        foreach (var file in manifests)
        {
            var manifest = Obj(ParseJson(c.Text(file))) ?? new JsonObject();
            var boundary = Str(Obj(manifest["arcforges"])?["licenceBoundary"]);
            var license = Str(manifest["license"]);
            if (Str(manifest["name"]) is { } name) projectNames[name] = file;
            if (boundary is not null) boundaries[file] = boundary;
            if (license is null || !LicenceIdentifier.IsMatch(license)) c.Report("licence-declaration", file, "SPDX licence identifier is missing");
            if (boundary is not (AgplBoundary or ApacheBoundary)) c.Report("licence-declaration", file, "Licence boundary is missing or unknown");
            if (boundary == AgplBoundary && license != "AGPL-3.0-only") c.Report("licence-boundary-set", file, "AGPL boundary requires AGPL-3.0-only");
            if (boundary == ApacheBoundary && license != "Apache-2.0") c.Report("licence-boundary-set", file, "Apache boundary requires Apache-2.0");
        }

        var npmRows = rows.Where(row => Str(row["kind"]) == "npm").Select(row => Str(row["path"]) ?? string.Empty).Order(StringComparer.Ordinal).ToList();
        if (!npmRows.SequenceEqual(manifests, StringComparer.Ordinal) || inventory?["licenceBoundary"] is null)
        {
            c.Report("licence-declaration", "eng/policy/licence-boundary.json", "Project inventory drift");
        }

        foreach (var row in rows.Where(row => Str(row["kind"]) == "npm"))
        {
            var file = Str(row["path"]) ?? string.Empty;
            var manifest = Obj(ParseJson(c.Text(file)));
            if (manifest is not null && Str(manifest["license"]) != Str(inventory?["spdxLicense"]) && boundaries.GetValueOrDefault(file) == AgplBoundary)
            {
                c.Report("licence-declaration", file, "Manifest licence differs from the inventory");
            }
        }

        var apache = boundaries.Where(entry => entry.Value == ApacheBoundary).Select(entry => entry.Key).Order(StringComparer.Ordinal).ToList();
        if (!apache.SequenceEqual(ApacheBoundaryProjects.Order(StringComparer.Ordinal), StringComparer.Ordinal))
        {
            c.Report("licence-boundary-set", "package.json", "Apache-boundary projects differ from the enumerated list: " + (apache.Count == 0 ? "none" : string.Join(", ", apache)));
        }

        foreach (var file in apache)
        {
            var manifest = Obj(ParseJson(c.Text(file)));
            foreach (var section in ManifestSections)
            {
                foreach (var name in StringMap(manifest?[section]).Keys)
                {
                    if (projectNames.TryGetValue(name, out var target) && boundaries.GetValueOrDefault(target) != ApacheBoundary)
                    {
                        c.Report("licence-cross-boundary", file, "Apache project references AGPL project " + name);
                    }
                }
            }
        }
    }

    /// <summary>The C# projects: a boundary and an expression each, the Apache set, cross-boundary references and the allowlist.</summary>
    private static void ProjectLicences(Context c)
    {
        var declared = c.Projects.Values.Where(p => p.Path.StartsWith("src/", StringComparison.Ordinal) || p.Path.StartsWith("tests/", StringComparison.Ordinal)).ToList();
        foreach (var project in declared)
        {
            if (project.Boundary is null) c.Report("licence-declaration", project.Path, "Project declares no LicenceBoundary");
            if (project.Licence is null) c.Report("licence-declaration", project.Path, "Project declares no PackageLicenseExpression");
            if (project.Boundary == AgplBoundary && project.Licence is not null && project.Licence != "AGPL-3.0-only")
            {
                c.Report("licence-boundary-set", project.Path, "AGPL boundary requires AGPL-3.0-only: " + project.Licence);
            }

            if (project.Boundary == ApacheBoundary && project.Licence is not null && project.Licence != "Apache-2.0")
            {
                c.Report("licence-boundary-set", project.Path, "Apache boundary requires Apache-2.0: " + project.Licence);
            }
        }

        var inventoryText = c.Text("eng/policy/licence-boundary.json");
        var inventory = Obj(ParseJson(inventoryText));
        var msbuildRows = (inventory?["projects"] as JsonArray)?.Select(row => Obj(row)).OfType<JsonObject>()
            .Where(row => Str(row["kind"]) == "msbuild").Select(row => Str(row["path"]) ?? string.Empty).Order(StringComparer.Ordinal).ToList() ?? [];
        var csprojs = c.Projects.Keys.Order(StringComparer.Ordinal).ToList();
        if (!msbuildRows.SequenceEqual(csprojs, StringComparer.Ordinal))
        {
            c.Report("licence-declaration", "eng/policy/licence-boundary.json", "Project inventory drift: msbuild projects");
        }

        var apache = declared.Where(p => p.Boundary == ApacheBoundary).Select(p => p.Path).ToHashSet(StringComparer.Ordinal);
        foreach (var path in apache.Except(ApacheBoundaryProjects, StringComparer.Ordinal))
        {
            c.Report("licence-boundary-set", path, "Apache boundary is not enumerated");
        }

        foreach (var path in ApacheBoundaryProjects.Except(apache, StringComparer.Ordinal))
        {
            c.Report("licence-boundary-set", path, "Enumerated Apache boundary is not declared");
        }

        foreach (var project in declared.Where(p => p.Boundary == ApacheBoundary))
        {
            foreach (var reference in project.ProjectReferences.Where(r => r.Resolved is not null && c.Projects.ContainsKey(r.Resolved)))
            {
                if (c.Projects[reference.Resolved!].Boundary != ApacheBoundary)
                {
                    c.Report("licence-cross-boundary", project.Path, "Apache-boundary project references AGPL project: " + reference.Raw);
                }
            }
        }

        foreach (var project in declared.Where(p => p.Licence is not null))
        {
            var allowed = project.Boundary == ApacheBoundary ? AllowedApache : AllowedAgpl;
            if (project.Path.StartsWith("tests/", StringComparison.Ordinal))
            {
                allowed = new HashSet<string>(allowed.Concat(DevelopmentOnlyLgpl), StringComparer.Ordinal);
            }

            if (SpdxExpression.Allowed(project.Licence, allowed)) continue;
            var development = DevelopmentOnlyLgpl.Any(id => project.Licence!.Contains(id, StringComparison.Ordinal));
            c.Report("licence-allowlist", project.Path, (development && project.Path.StartsWith("src/", StringComparison.Ordinal)
                ? "LGPL is development-only and ships in source: "
                : "Licence is not allowed for the boundary: ") + project.Licence);
        }
    }

    /// <summary>The locked npm closure: every locked licence expression is allowed for the consuming boundary; LGPL only in development.</summary>
    private static void LockLicences(Context c)
    {
        var root = Obj(ParseJson(c.Text("package.json")));
        var apacheRoot = Str(Obj(root?["arcforges"])?["licenceBoundary"]) == ApacheBoundary;
        var lockFile = Obj(ParseJson(c.Text("package-lock.json")));
        if (Obj(lockFile?["packages"]) is not { } packages) return;
        foreach (var (key, value) in packages)
        {
            if (!key.Contains("node_modules/", StringComparison.Ordinal)) continue;
            var item = Obj(value);
            var expression = Str(item?["license"]);
            var developmentOnly = item?["dev"] is JsonValue dev && dev.TryGetValue(out bool devFlag) && devFlag
                || item?["devOptional"] is JsonValue devOptional && devOptional.TryGetValue(out bool devOptionalFlag) && devOptionalFlag;
            var consumer = apacheRoot ? AllowedApache : developmentOnly ? new HashSet<string>(AllowedAgpl.Concat(DevelopmentOnlyLgpl), StringComparer.Ordinal) : AllowedAgpl;
            if (!SpdxExpression.Allowed(expression, consumer))
            {
                c.Report("licence-allowlist", "package-lock.json", key.Split("node_modules/").Last() + ": " + (expression ?? "no licence"));
            }
        }
    }

    // ---------------------------------------------------------------- WP-05.02 naming

    private static void NamingRules(Context c)
    {
        // naming-identity: the candidate record is exactly the pinned NuGet identity, centrally pinned and locked as a build-only reference.
        const string candidateFile = "eng/policy/naming-candidate.json";
        var candidate = Obj(ParseJson(c.Text(candidateFile)));
        if (candidate is null)
        {
            c.Report("naming-identity", candidateFile, "The naming candidate record is missing or malformed");
        }
        else
        {
            var expectedKeys = new[] { "archiveSha512", "assets", "ecosystem", "package", "publication", "sourceCommit", "version" };
            if (!candidate.Select(entry => entry.Key).Order(StringComparer.Ordinal).SequenceEqual(expectedKeys, StringComparer.Ordinal))
            {
                c.Report("naming-identity", candidateFile, "Candidate record must have exactly package, ecosystem, version, sourceCommit, archiveSha512, publication and assets");
            }

            if (Str(candidate["package"]) != NamingCandidate.PackageId) c.Report("naming-identity", candidateFile, "Unexpected producer package");
            if (Str(candidate["ecosystem"]) != "nuget") c.Report("naming-identity", candidateFile, "The producer ecosystem is not NuGet");
            if (Str(candidate["version"]) != NamingCandidate.Version) c.Report("naming-identity", candidateFile, "The candidate is not the pinned version");
            if (Str(candidate["sourceCommit"]) is not { } commit || !CommitHex.IsMatch(commit) || commit != NamingCandidate.SourceCommit)
            {
                c.Report("naming-identity", candidateFile, "The producer source commit is not the pinned full SHA");
            }

            if (Str(candidate["archiveSha512"]) != NamingCandidate.ArchiveSha512) c.Report("naming-identity", candidateFile, "The archive SHA512 is not the pinned digest");
            if (Str(candidate["publication"]) is not { } publication || !NamingPublication.IsMatch(publication))
            {
                c.Report("naming-identity", candidateFile, "Publication receipt must be an ArcForges/Contracts workflow run");
            }

            var assets = Obj(candidate["assets"]);
            var assetKeys = assets?.Select(entry => entry.Key).Order(StringComparer.Ordinal).ToArray() ?? [];
            if (!assetKeys.SequenceEqual(new[] { NamingCandidate.ScannerPath, NamingCandidate.PolicyPath }, StringComparer.Ordinal))
            {
                c.Report("naming-identity", candidateFile, "Asset set must be exactly the published scanner and policy");
            }

            if (Str(assets?[NamingCandidate.ScannerPath]) != NamingCandidate.ScannerSha256 || Str(assets?[NamingCandidate.PolicyPath]) != NamingCandidate.PolicySha256)
            {
                c.Report("naming-identity", candidateFile, "The candidate asset digests are not the pinned SHA256 values");
            }
        }

        if (c.CentralPackages().GetValueOrDefault(NamingCandidate.PackageId) != NamingCandidate.Version)
        {
            c.Report("naming-identity", "Directory.Packages.props", "The naming candidate is not centrally pinned at the exact version");
        }

        var architecture = c.Projects.GetValueOrDefault("tests/ArchitectureTests/ArcForges.Cloud.ArchitectureTests.csproj");
        if (architecture is null || !architecture.PackageReferences.Any(p => p.Id == NamingCandidate.PackageId && p.PrivateAssets))
        {
            c.Report("naming-identity", "tests/ArchitectureTests/ArcForges.Cloud.ArchitectureTests.csproj", "The naming candidate is not a build-only reference of the architecture host");
        }

        // naming-scan: the checkout's scan report passed for Cloud under the pinned policy with zero findings.
        var reportText = c.Text(NamingReport);
        if (reportText is null)
        {
            c.Report("naming-scan", NamingReport, "The naming scan report is missing; run the policy gate first");
            return;
        }

        var report = Obj(ParseJson(reportText));
        var rows = (report?["repositories"] as JsonArray)?.Select(row => Obj(row)).OfType<JsonObject>().Where(row => Str(row["repository"]) == "Cloud").ToList() ?? [];
        if (rows.Count != 1 || Str(rows[0]["status"]) != "pass" || (rows[0]["findings"] as JsonArray)?.Count != 0)
        {
            c.Report("naming-scan", NamingReport, "The naming scan of Cloud did not pass with zero findings");
        }

        if (Str(report?["policySha256"]) != NamingCandidate.PolicySha256)
        {
            c.Report("naming-scan", NamingReport, "The scan ran under another policy");
        }
    }

    // ---------------------------------------------------------------- WP-05.03 wire

    private static void WireRules(Context c)
    {
        // wire-package: every runtime Contracts package shares one exact version (the naming tool is build-only and excluded).
        var contracts = c.CentralPackages().Where(p => p.Key.StartsWith("ArcForges.Contracts.", StringComparison.Ordinal) && p.Key != NamingCandidate.PackageId)
            .Select(p => p.Value).Distinct(StringComparer.Ordinal).ToList();
        if (contracts.Count > 1)
        {
            c.Report("wire-package", "Directory.Packages.props", "Contracts runtime packages come from more than one version");
        }

        WirePackagePin(c);

        // wire-import: a project compiles only its own files.
        foreach (var project in c.Projects.Values)
        {
            var folder = project.Path[..project.Path.LastIndexOf('/')] + "/";
            foreach (var include in project.CompileIncludes)
            {
                var target = Project.Normalize(project.Path, include);
                if (target is null || !target.StartsWith(folder, StringComparison.Ordinal))
                {
                    c.Report("wire-import", project.Path, "Compiles a file outside its project folder: " + include);
                }
            }
        }

        // wire-source: no copied generated source or schema file is authored in this repository; protoc output is not authored here.
        foreach (var path in c.Sources.Keys.Order(StringComparer.Ordinal))
        {
            if (ProtoSchemaFile.IsMatch(path))
            {
                c.Report("wire-source", path, "Authored schema or copied generated wire source");
            }

            if (IsCodeFile(path) && !DeclarationFile().IsMatch(path) && !path.StartsWith("tests/ArchitectureTests/", StringComparison.Ordinal)
                && !path.StartsWith("eng/policy/", StringComparison.Ordinal) && ProtocHeader.IsMatch(c.Sources[path]))
            {
                c.Report("wire-source", path, "Generated protocol buffer output authored in this repository");
            }
        }

        // wire-codec: no handwritten or alternative wire codec in production C#.
        foreach (var (file, tree) in c.ProductionCSharp)
        {
            foreach (var token in tree.GetRoot().DescendantTokens().Where(t => t.IsKind(SyntaxKind.IdentifierToken) && WireCodecNames.Contains(t.ValueText, StringComparer.Ordinal)))
            {
                c.Report("wire-codec", file, "Handwritten wire codec primitive: " + token.ValueText);
            }
        }

        // wire-schema: production C# does not implement the generated message contract itself.
        foreach (var (file, tree) in c.ProductionCSharp)
        {
            foreach (var declaration in tree.GetRoot().DescendantNodes().OfType<BaseTypeDeclarationSyntax>())
            {
                if (declaration.BaseList is { } list && list.Types.Any(t => t.ToString().Contains("IMessage", StringComparison.Ordinal)))
                {
                    c.Report("wire-schema", file, "Handwritten message implements the generated contract: " + declaration.Identifier.ValueText);
                }
            }
        }

        // wire-shadow: no production declaration sits in a generated Contracts namespace.
        foreach (var (file, tree) in c.ProductionCSharp)
        {
            foreach (var name in tree.GetRoot().DescendantNodes().OfType<BaseNamespaceDeclarationSyntax>().Select(n => n.Name.ToString()))
            {
                if (name == "ArcForges.Contracts" || name.StartsWith("ArcForges.Contracts.", StringComparison.Ordinal))
                {
                    c.Report("wire-shadow", file, "Declares a type in the generated namespace " + name);
                }
            }
        }
    }

    /// <summary>
    /// The wire package pin (CLOUD.84 S38(1)). If the root manifest declares the public wire package, in either section, the declaration is
    /// one exact, registry-locked candidate that the lock carries too. A release Worker file that imports it needs it as a runtime
    /// dependency; a build or test consumer may hold it as a development dependency. If the package is neither declared nor imported, the
    /// rule has nothing to pin and passes. Every declared or imported use stays refused unless it meets these conditions.
    /// </summary>
    private static void WirePackagePin(Context c)
    {
        var root = Obj(ParseJson(c.Text("package.json")));
        var lockFile = Obj(ParseJson(c.Text("package-lock.json")));
        var runtime = StringMap(root?["dependencies"]).GetValueOrDefault(PublicWirePackage);
        var pin = runtime ?? StringMap(root?["devDependencies"]).GetValueOrDefault(PublicWirePackage);
        var declared = runtime is not null || StringMap(root?["devDependencies"]).ContainsKey(PublicWirePackage);
        var imported = new List<string>();
        foreach (var file in c.TypeScript.Where(file => file.Release))
        {
            if (file.References.Any(reference => reference.Specifier is not null && (reference.Specifier == PublicWirePackage || reference.Specifier.StartsWith(PublicWirePackage + "/", StringComparison.Ordinal))))
                imported.Add(file.Path);
        }

        if (declared)
        {
            var entry = Obj(Obj(lockFile?["packages"])?["node_modules/" + PublicWirePackage]);
            var tarball = "https://registry.npmjs.org/" + PublicWirePackage + "/-/proto-" + pin + ".tgz";
            var lockRoot = Obj(Obj(lockFile?["packages"])?[""]);
            var lockedPin = StringMap(lockRoot?["dependencies"]).GetValueOrDefault(PublicWirePackage) ?? StringMap(lockRoot?["devDependencies"]).GetValueOrDefault(PublicWirePackage);
            var integrity = Str(entry?["integrity"]) ?? string.Empty;
            var integrityOk = integrity.StartsWith("sha512-", StringComparison.Ordinal) && Sha512Base64.IsMatch(integrity["sha512-".Length..]);
            if (pin is null || !ExactVersion.IsMatch(pin) || !pin.Contains("-ci.", StringComparison.Ordinal) || Str(entry?["version"]) != pin
                || Str(entry?["resolved"]) != tarball || !integrityOk || lockedPin != pin)
            {
                c.Report("wire-package", "package.json", "Exact registry-locked published candidate pin of the public wire package required");
            }
        }

        foreach (var path in imported)
        {
            if (runtime is null)
                c.Report("wire-package", path, "Worker imports the wire package without a runtime dependency");
        }
    }

    // ---------------------------------------------------------------- WP-05.04 banned and the Worker token rules

    private static void BannedRules(Context c)
    {
        foreach (var (file, tree) in c.ProductionCSharp)
        {
            var root = tree.GetRoot();

            // banned-reflection: no reflection emit, dynamic loading or reflective construction.
            foreach (var use in root.DescendantNodes().OfType<UsingDirectiveSyntax>().Where(u => u.Name?.ToString().StartsWith("System.Reflection.Emit", StringComparison.Ordinal) == true))
            {
                c.Report("banned-reflection", file, "Reflection emit namespace");
            }

            foreach (var invocation in root.DescendantNodes().OfType<InvocationExpressionSyntax>())
            {
                var text = invocation.Expression.ToString();
                if (ReflectionCall.IsMatch(text)) c.Report("banned-reflection", file, "Reflective call: " + text);
                if (text.EndsWith("Expression.Compile", StringComparison.Ordinal) || text.EndsWith("CSharpScript.EvaluateAsync", StringComparison.Ordinal))
                {
                    c.Report("banned-dynamic-code", file, "Runtime compilation: " + text);
                }

                // banned-blocking-wait: no sync-over-async wait or sync host call.
                if (text.EndsWith(".Wait", StringComparison.Ordinal) || text.EndsWith("GetAwaiter().GetResult", StringComparison.Ordinal) || text.EndsWith(".GetResult", StringComparison.Ordinal))
                {
                    c.Report("banned-blocking-wait", file, "Blocking wait: " + text);
                }

                // banned-secret-logging: no logging of a secret-bearing or content-bearing value.
                if (LoggingCall.IsMatch(text) && invocation.ArgumentList.DescendantTokens().Any(t => t.IsKind(SyntaxKind.IdentifierToken) && SensitiveName.IsMatch(t.ValueText)))
                {
                    c.Report("banned-secret-logging", file, "Logs a sensitive value through " + text);
                }

                // banned-raw-memory: no unmanaged memory helpers.
                if (text.Contains("Marshal.AllocHGlobal", StringComparison.Ordinal) || text.Contains("NativeMemory.", StringComparison.Ordinal))
                {
                    c.Report("banned-raw-memory", file, "Unmanaged memory: " + text);
                }
            }

            // A task result read is a blocking wait; a stored receipt named Result is not (a syntactic heuristic, a named limit).
            foreach (var member in root.DescendantNodes().OfType<MemberAccessExpressionSyntax>().Where(m => m.Name.Identifier.ValueText == "Result" && IsTaskLike(m.Expression)))
            {
                c.Report("banned-blocking-wait", file, "Blocking task result: " + member);
            }

            foreach (var identifier in root.DescendantTokens().Where(t => t.IsKind(SyntaxKind.IdentifierToken) && t.ValueText == "dynamic"))
            {
                c.Report("banned-dynamic-code", file, "Dynamic type at line " + (identifier.GetLocation().GetLineSpan().StartLinePosition.Line + 1));
            }

            // Pinned memory is raw memory; stackalloc yields a managed Span and is not raw memory.
            foreach (var node in root.DescendantNodes().Where(n => n.IsKind(SyntaxKind.FixedStatement)))
            {
                c.Report("banned-raw-memory", file, "Pinned memory: " + node.Kind());
            }

            foreach (var token in root.DescendantTokens().Where(t => t.IsKind(SyntaxKind.UnsafeKeyword)))
            {
                c.Report("banned-raw-memory", file, "Unsafe code at line " + (token.GetLocation().GetLineSpan().StartLinePosition.Line + 1));
            }

            foreach (var use in root.DescendantNodes().OfType<UsingDirectiveSyntax>().Where(u => ProviderNamespaces.Any(p => u.Name?.ToString().StartsWith(p, StringComparison.Ordinal) == true)))
            {
                c.Report("banned-provider-sdk", file, "Provider namespace: " + use.Name);
            }

            foreach (var literal in root.DescendantTokens().Where(t => t.IsKind(SyntaxKind.StringLiteralToken)).Where(t => ProviderHost.IsMatch(t.ValueText)))
            {
                c.Report("banned-provider-sdk", file, "Direct provider endpoint in source");
            }

            // banned-float-money: production C# declares money values in decimal only.
            foreach (var declaration in root.DescendantNodes().OfType<VariableDeclarationSyntax>().Where(d => IsFloating(d.Type)))
            {
                foreach (var variable in declaration.Variables.Where(v => IsMoney(v.Identifier.ValueText)))
                {
                    c.Report("banned-float-money", file, "Floating money value: " + variable.Identifier.ValueText);
                }
            }

            foreach (var parameter in root.DescendantNodes().OfType<ParameterSyntax>().Where(p => p.Type is not null && IsFloating(p.Type) && IsMoney(p.Identifier.ValueText)))
            {
                c.Report("banned-float-money", file, "Floating money parameter: " + parameter.Identifier.ValueText);
            }

            foreach (var property in root.DescendantNodes().OfType<PropertyDeclarationSyntax>().Where(p => IsFloating(p.Type) && IsMoney(p.Identifier.ValueText)))
            {
                c.Report("banned-float-money", file, "Floating money property: " + property.Identifier.ValueText);
            }
        }

        foreach (var project in c.Projects.Values.Where(p => p.Path.StartsWith("src/", StringComparison.Ordinal)))
        {
            foreach (var package in project.PackageReferences.Where(p => ProviderNuget.IsMatch(p.Id)))
            {
                c.Report("banned-provider-sdk", project.Path, "Provider SDK package: " + package.Id);
            }
        }
    }

    /// <summary>
    /// The Worker token rules: the AI policy's per-file rules over the lexer's tokens, applied to every TypeScript file. The banned-API rules
    /// (dynamic code, reflection, waits, raw memory, provider calls, logging and money) are release-only, as in the AI policy; the adapter
    /// store rule applies to the adapter folders.
    /// </summary>
    private static void TypeScriptTokenRules(Context c, HarnessAuditOptions options)
    {
        var generated = options.GeneratedTypeScriptNames ?? new HashSet<string>(StringComparer.Ordinal);
        foreach (var file in c.TypeScript)
        {
            var release = file.Release;
            var tokens = file.Tokens;
            var bound = new Dictionary<string, string>(StringComparer.Ordinal);
            foreach (var reference in file.References.Where(r => r.Specifier is not null))
            {
                foreach (var (local, _) in reference.Bindings) bound[local] = PackageName(reference.Specifier!);
                var specifier = reference.Specifier!;
                if (specifier.StartsWith(PublicWirePackage + "/", StringComparison.Ordinal) || NodeModulesWire().IsMatch(specifier))
                {
                    c.Report("wire-import", file.Path, "Generated types must come from the package root: " + specifier);
                }

                if (BuildOutputImport().IsMatch(specifier))
                {
                    c.Report("wire-import", file.Path, "Generated build output import: " + specifier);
                }

                if (WireCodecPackage.IsMatch(specifier)) c.Report("wire-codec", file.Path, "Handwritten or alternative wire codec: " + specifier);
                if (ProviderPackage.IsMatch(specifier)) c.Report("banned-provider-sdk", file.Path, "Provider SDK import: " + specifier);
            }

            var hex = new HashSet<string>(tokens.Where(t => t.Kind == TokenKind.Number).Select(t => t.Value.ToLowerInvariant().Replace("_", string.Empty, StringComparison.Ordinal)), StringComparer.Ordinal);
            var names = new HashSet<string>(tokens.Where(t => t.Kind == TokenKind.Word).Select(t => t.Value), StringComparer.Ordinal);
            // Build tooling may read the protobuf runtime's licence header; the codec rule concerns authored product and test code.
            if (!file.Path.StartsWith("eng/", StringComparison.Ordinal)
                && (new[] { "BinaryWriter", "BinaryReader", "varint" }.Any(names.Contains) || (hex.Contains("0x7f") && hex.Contains("0x80"))))
            {
                c.Report("wire-codec", file.Path, "Manual varint or binary reader/writer logic");
            }

            for (var index = 0; index < tokens.Count; index++)
            {
                var token = tokens[index];
                var next = Peek(tokens, index + 1);
                var before = Peek(tokens, index - 1);
                if (token.Kind is TokenKind.String or TokenKind.Template)
                {
                    if (release && ProviderHost.IsMatch(token.Value)) c.Report("banned-provider-sdk", file.Path, "Direct provider endpoint literal");
                    continue;
                }

                if (token.Kind != TokenKind.Word) continue;
                var afterDot = before?.Kind == TokenKind.Punct && before.Value is "." or "?.";
                if (generated.Contains(token.Value) && GeneratedSuffix.IsMatch(token.Value) && !afterDot && before?.Kind == TokenKind.Word
                    && before.Value is "interface" or "type" or "class" or "enum" or "const" or "let" or "var" or "function")
                {
                    c.Report("wire-shadow", file.Path, "Local declaration redefines generated type " + token.Value);
                }

                if (CodecFunctions.Contains(token.Value, StringComparer.Ordinal) && next?.Value == "(" && !afterDot)
                {
                    var first = Peek(tokens, index + 2);
                    if (bound.GetValueOrDefault(token.Value) == "@bufbuild/protobuf"
                        && (first?.Kind != TokenKind.Word || bound.GetValueOrDefault(first.Value) != PublicWirePackage))
                    {
                        c.Report("wire-schema", file.Path, token.Value + " must take a generated schema imported from " + PublicWirePackage);
                    }
                }

                if (!release) continue;
                var call = next?.Value == "(";
                if (token.Value == "Reflect" && next?.Value == ".") c.Report("banned-reflection", file.Path, "Reflect entry point");
                if (token.Value is "__proto__" or "setPrototypeOf") c.Report("banned-reflection", file.Path, token.Value);
                if (token.Value == "constructor" && next?.Value == "." && Peek(tokens, index + 2)?.Value == "constructor")
                {
                    c.Report("banned-reflection", file.Path, "constructor.constructor");
                }

                if (token.Value == "eval" && call && !afterDot) c.Report("banned-dynamic-code", file.Path, "eval");
                if (token.Value == "Function" && (call || before?.Value == "new") && !afterDot) c.Report("banned-dynamic-code", file.Path, "Function constructor");
                if (token.Value is "setTimeout" or "setInterval" && call && Peek(tokens, index + 2) is { Kind: TokenKind.String or TokenKind.Template })
                {
                    c.Report("banned-dynamic-code", file.Path, token.Value + " with a code string");
                }

                if (token.Value == "importScripts" && call) c.Report("banned-dynamic-code", file.Path, "importScripts");
                if (token.Value == "WebAssembly" && next?.Value == ".")
                {
                    var member = Peek(tokens, index + 2)?.Value ?? string.Empty;
                    if (member == "Memory") c.Report("banned-raw-memory", file.Path, "WebAssembly.Memory");
                    else c.Report("banned-dynamic-code", file.Path, "WebAssembly." + member);
                }

                if (token.Value == "SharedArrayBuffer") c.Report("banned-raw-memory", file.Path, "SharedArrayBuffer");
                if (token.Value == "Atomics" && next?.Value == ".")
                {
                    var member = Peek(tokens, index + 2)?.Value ?? string.Empty;
                    if (member == "wait") c.Report("banned-blocking-wait", file.Path, "Atomics.wait");
                    else c.Report("banned-raw-memory", file.Path, "Atomics." + member);
                }

                if (token.Value.EndsWith("Sync", StringComparison.Ordinal) && call && afterDot)
                {
                    c.Report("banned-blocking-wait", file.Path, "Synchronous host call " + token.Value);
                }

                if (token.Value == "while" && ClockBusyWait(tokens, index)) c.Report("banned-blocking-wait", file.Path, "Busy-wait on the clock");
                if (token.Value == "XMLHttpRequest") c.Report("banned-blocking-wait", file.Path, "XMLHttpRequest");

                if (IsAdapter(file.Path))
                {
                    if (AdapterStoreTypes.Contains(token.Value, StringComparer.Ordinal) && !afterDot)
                    {
                        c.Report("layer-business-authority", file.Path, "Cloud-owned business store type " + token.Value);
                    }

                    if (DurableObjectTypes.Contains(token.Value, StringComparer.Ordinal) && !afterDot && file.Path != AlarmFile)
                    {
                        c.Report("layer-business-authority", file.Path, "Durable Object lifecycle is held only by the run alarm");
                    }
                }

                if (token.Value == "AI" && afterDot && file.Path != WorkerEntry && !file.Path.StartsWith(AdapterFolder, StringComparison.Ordinal))
                {
                    c.Report("banned-provider-call", file.Path, "Inference binding referenced outside the entry/adapter");
                }

                if (token.Value == "run" && call && afterDot && before is not null && Peek(tokens, index - 2)?.Value is "ai" or "AI"
                    && !file.Path.StartsWith(AdapterFolder, StringComparison.Ordinal))
                {
                    c.Report("banned-provider-call", file.Path, "Inference binding called outside the model adapter");
                }

                if (token.Value == "console" && next?.Value == "." && Peek(tokens, index + 3)?.Value == "(")
                {
                    foreach (var argument in CallArguments(tokens, index + 3))
                    {
                        if (argument.Kind == TokenKind.Word && SensitiveName.IsMatch(argument.Value))
                        {
                            c.Report("banned-secret-logging", file.Path, "console." + (Peek(tokens, index + 2)?.Value ?? string.Empty) + " receives " + argument.Value);
                        }
                    }
                }

                if (IdentifierParts(token.Value).Any(part => MoneyParts.Contains(part, StringComparer.Ordinal)) && FloatingMoney(tokens, index))
                {
                    c.Report("banned-float-money", file.Path, "Floating-point handling near " + token.Value);
                }
            }
        }
    }

    [GeneratedRegex(@"(?:^|/)node_modules/@arcforges/", RegexOptions.CultureInvariant)]
    private static partial Regex NodeModulesWire();

    [GeneratedRegex(@"@arcforges/proto/dist|(?:^|/)dist/gen/", RegexOptions.CultureInvariant)]
    private static partial Regex BuildOutputImport();

    private static Token? Peek(IReadOnlyList<Token> tokens, int index) => index >= 0 && index < tokens.Count ? tokens[index] : null;

    /// <summary>The tokens of a call's argument list, from the opening parenthesis (exclusive) to its matching close.</summary>
    private static List<Token> CallArguments(IReadOnlyList<Token> tokens, int open)
    {
        var depth = 0;
        var found = new List<Token>();
        for (var index = open; index < tokens.Count; index++)
        {
            var token = tokens[index];
            if (token.Kind == TokenKind.Punct && token.Value is "(" or "[" or "{" or "${") depth++;
            else if (token.Kind == TokenKind.Punct && token.Value is ")" or "]" or "}")
            {
                depth--;
                if (depth == 0) break;
            }

            if (index > open) found.Add(token);
        }

        return found;
    }

    /// <summary>A while loop whose condition reads the clock within its first ten tokens: a busy-wait.</summary>
    private static bool ClockBusyWait(IReadOnlyList<Token> tokens, int index)
    {
        var limit = Math.Min(tokens.Count, index + 10);
        for (var position = index; position < limit; position++)
        {
            if (tokens[position].Value == "now" && position > index && tokens[position - 1].Value == ".") return true;
        }

        return false;
    }

    /// <summary>A money identifier whose following tokens (up to a statement end) hold a floating-point literal, an arithmetic helper or a number annotation.</summary>
    private static bool FloatingMoney(IReadOnlyList<Token> tokens, int index)
    {
        var window = new List<Token>();
        for (var cursor = index + 1; cursor < Math.Min(tokens.Count, index + 14); cursor++)
        {
            var item = tokens[cursor];
            if (item.Kind == TokenKind.Punct && item.Value is ";" or "}") break;
            window.Add(item);
        }

        var floating = window.Select((item, offset) => (item, offset)).Any(entry =>
        {
            var (item, offset) = entry;
            if (item.Kind == TokenKind.Number)
            {
                var decimalOrExponent = item.Value.Contains('.') || item.Value.Contains('e') || item.Value.Contains('E');
                return decimalOrExponent && !item.Value.StartsWith("0x", StringComparison.OrdinalIgnoreCase);
            }

            if (item.Kind == TokenKind.Word)
            {
                return item.Value is "parseFloat" or "toFixed" or "toPrecision" or "fround"
                    || (item.Value == "Math" && offset + 1 < window.Count && window[offset + 1].Value == ".");
            }

            return false;
        });
        var annotated = window.Count > 1 && window[0].Value == ":" && window[1].Value == "number";
        var conditional = window.Count > 2 && window[0].Value == "?" && window[1].Value == ":" && window[2].Value == "number";
        return floating || annotated || conditional;
    }

    /// <summary>The identifier parts of a camel or snake case name, lower case, as the AI policy splits them.</summary>
    private static string[] IdentifierParts(string name) =>
        IdentifierBoundary.Replace(name, "$1_$2").ToLowerInvariant().Split(['_', '$'], StringSplitOptions.RemoveEmptyEntries);

    private static bool IsFloating(TypeSyntax type) =>
        type.ToString() is "double" or "float" or "Double" or "Single" or "System.Double" or "System.Single";

    private static bool IsMoney(string identifier) => IdentifierParts(identifier).Any(part => MoneyParts.Contains(part, StringComparer.Ordinal));

    private static string ModuleFolder(string path) => path[..(path.LastIndexOf('/') + 1)];

    /// <summary>True for an expression that can name a task: a call, or a name ending in task.</summary>
    private static bool IsTaskLike(ExpressionSyntax expression) =>
        expression is InvocationExpressionSyntax || expression.ToString().EndsWith("task", StringComparison.OrdinalIgnoreCase);

    private static HashSet<string> RuntimeDependencies(Context c) => StringMap(Obj(ParseJson(c.Text("package.json")))?["dependencies"]).Keys.ToHashSet(StringComparer.Ordinal);

    /// <summary>Every cycle found by a depth-first walk, each as a closed list of nodes.</summary>
    private static List<List<string>> FindCycles(IReadOnlyDictionary<string, List<string>> graph)
    {
        var cycles = new List<List<string>>();
        var state = new Dictionary<string, int>(StringComparer.Ordinal);
        var stack = new List<string>();

        void Visit(string node)
        {
            state[node] = 1;
            stack.Add(node);
            foreach (var next in graph.GetValueOrDefault(node) ?? [])
            {
                if (!state.TryGetValue(next, out var seen))
                {
                    if (graph.ContainsKey(next)) Visit(next);
                }
                else if (seen == 1)
                {
                    var start = stack.IndexOf(next);
                    cycles.Add([.. stack.Skip(start), next]);
                }
            }

            stack.RemoveAt(stack.Count - 1);
            state[node] = 2;
        }

        foreach (var node in graph.Keys.OrderBy(k => k, StringComparer.Ordinal))
        {
            if (!state.ContainsKey(node)) Visit(node);
        }

        return cycles;
    }
}
