// SPDX-License-Identifier: AGPL-3.0-only
// GENERATED by tools/ArcForges.Cloud.Generation from the C# host registrations (HelloModule and PipelineProbe), the transport
// budgets and correlation guards in src/ArcForges.Cloud/Generation, the edge-guard constants of IngressPipeline and the readiness
// vocabulary in src/ArcForges.Cloud/Readiness. Do not edit by hand: run `npm run generate` and commit the result. `npm run
// check:generated` fails on any drift. The Worker applies these guards before it forwards a call and names the readiness
// vocabulary from here; nothing here grants anything and no readiness verdict is taken from it.

/** The kind of a method the Worker admits: one unary reply, or a server stream. */
export type RouteKind = "unary" | "serverStream";
/** anonymous: no credential is read or forwarded; session: bearer or origin-bound cookie, checked again by the host. */
export type RouteAuth = "anonymous" | "session";

export interface ApiRoute {
  /** The method path without the owned /api prefix: /package.Service/Method. */
  readonly path: string;
  readonly kind: RouteKind;
  readonly auth: RouteAuth;
  /** Bound of the whole request body, frame header included. Unary and server-streaming requests are one message. */
  readonly maxRequestBytes: number;
  /** Bound of one response frame. */
  readonly maxFrameBytes: number;
  /** Bound of a whole unary response (buffered); a stream has no total bound, only its lifetime. */
  readonly maxUnaryResponseBytes: number;
  /** Cap of the RPC deadline (unary) or of the stream's lifetime (server stream). */
  readonly maxDurationMs: number;
  /** The Container instance (Durable Object name) that serves the method. */
  readonly instance: string;
  /**
   * The request message starts with a RequestMeta (field 1, wire registry 04). Only then does the edge read the client's
   * correlation id from it; a method whose field 1 means something else (the Hello name) is never interpreted.
   */
  readonly requestMeta: boolean;
}

export const helloPath = "/api/arcforges.hello.v1.HelloService/SayHello";
export const healthPath = "/api/healthz";
/** The bound of a whole request body of a method that declares no larger one, frame header included. */
export const maxBodyBytes = 4096;
/** The Container may take at most this long to start before a stream's response headers arrive. */
export const coldStartBudgetMs = 15000;
/** A server stream's lifetime when the client states no shorter deadline: the annex 10 server close after five minutes plus slack. */
export const streamLifetimeMs = 310000;

/** The health route: a small plain reply that the pipeline answers itself. */
export const healthRoute: ApiRoute = {
  path: "/healthz",
  kind: "unary",
  auth: "anonymous",
  maxRequestBytes: 0,
  maxFrameBytes: 0,
  maxUnaryResponseBytes: 8192,
  maxDurationMs: 15000,
  instance: "hello",
  requestMeta: false,
};

/** The methods the production Worker serves. */
export const productionRoutes: readonly ApiRoute[] = [
  {
    path: "/arcforges.hello.v1.HelloService/SayHello",
    kind: "unary",
    auth: "anonymous",
    maxRequestBytes: 4096,
    maxFrameBytes: 8192,
    maxUnaryResponseBytes: 8192,
    maxDurationMs: 10000,
    instance: "hello",
    requestMeta: false,
  },
];

// Proof-only pipeline probe (the isolated proof environment, FOUNDATION_PROOF=enabled): an authenticated
// workspace-scoped unary call, a timed server stream and an observation of how the host saw its streams end.
export const proofRoutes: readonly ApiRoute[] = [
  {
    path: "/arcforges.proof.v1.PipelineProbe/Whoami",
    kind: "unary",
    auth: "session",
    maxRequestBytes: 4096,
    maxFrameBytes: 65536,
    maxUnaryResponseBytes: 8192,
    maxDurationMs: 10000,
    instance: "foundation",
    requestMeta: true,
  },
  {
    path: "/arcforges.proof.v1.PipelineProbe/Stream",
    kind: "serverStream",
    auth: "session",
    maxRequestBytes: 4096,
    maxFrameBytes: 65536,
    maxUnaryResponseBytes: 8192,
    maxDurationMs: 60000,
    instance: "foundation",
    requestMeta: true,
  },
  {
    path: "/arcforges.proof.v1.PipelineProbe/Observation",
    kind: "unary",
    auth: "session",
    maxRequestBytes: 4096,
    maxFrameBytes: 65536,
    maxUnaryResponseBytes: 8192,
    maxDurationMs: 10000,
    instance: "foundation",
    requestMeta: true,
  },
];

/** The session credential names the edge checks read; the header name is lowercase as the Worker forwards it. */
export const edgeGuard = {
  sessionCookieName: "__Host-af_session",
  csrfHeader: "x-af-csrf",
} as const;

/** The correlation guards (CR-01, CR-03): the identity shape, the fields that carry it and the traceparent form the Worker writes. */
export const correlationGuard = {
  uuidPattern: "^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$",
  nilUuid: "00000000-0000-0000-0000-000000000000",
  requestMetaField: 1,
  correlationIdField: 3,
  idValueField: 1,
  idByteLength: 16,
  traceparentVersion: "00",
  traceparentFlags: "01",
} as const;

/** The named-plan transport guards (Design D1 profile, section 3): deadline, clock tolerance and value bounds. Plan decisions stay in the generated plan tables. */
export const storageGuards = {
  maxDeadlineAheadMs: 10000,
  deadlineClockToleranceMs: 2000,
  guardConstraintName: "af_guard_failed",
  maxTextLength: 262144,
  maxBytesLength: 262144,
  int64Min: "-9223372036854775808",
  int64Max: "9223372036854775807",
  uint64Max: "18446744073709551615",
  maxDecimalSignificantDigits: 28,
  maxDecimalFractionDigits: 9,
} as const;

/** The report schema identifier; the report schema is stable (docs/cloud-readiness.md). */
export const readinessSchema = "cloud.readiness.v1";
/** Seconds a client is advised to wait before a retry after a transient refusal (Design D1 profile, section 3). */
export const retryAfterSeconds = 2;
/** The longest the readiness check waits for one component (Design D1 profile, section 3). */
export const readinessWaitMs = 8000;

/** The environments a binding may be declared in. */
export const readinessEnvironments = ["production", "proof"] as const;
export type ReadinessEnvironment = (typeof readinessEnvironments)[number];

/** The components of the readiness report, in report order. */
export const readinessComponentIds = [
  "ingress",
  "container",
  "d1",
  "durableObject",
  "r2",
  "queue",
] as const;
export type ComponentId = (typeof readinessComponentIds)[number];

/** The states one component can take. */
export const readinessStates = [
  "ready",
  "starting",
  "unavailable",
  "misconfigured",
  "unknown",
  "not_required",
] as const;
export type ComponentState = (typeof readinessStates)[number];

/** The states the whole can take. */
export const readinessStatuses = ["ready", "starting", "unavailable", "misconfigured"] as const;
export type ReadinessStatus = (typeof readinessStatuses)[number];

/** The statuses a retry can help: a transient failure only. */
export const readinessRetryableStatuses = ["starting", "unavailable"] as const;

/** How far a check went: a bounded read answered, or only a declared binding was checked. */
export const readinessEvidence = ["probed", "bound"] as const;
export type Evidence = (typeof readinessEvidence)[number];

/** The closed reason codes; a component that is not ready carries one. */
export const readinessReasons = [
  "binding_missing",
  "key_missing",
  "key_mismatch",
  "host_route_missing",
  "host_reply_invalid",
  "host_error",
  "no_instance_available",
  "start_failed",
  "rate_limited",
  "no_answer_in_wait",
  "unreachable",
  "container_not_ready",
  "plan_hash_mismatch",
  "schema_mismatch",
  "recovery_generation_mismatch",
  "d1_unavailable",
] as const;
export type Reason = (typeof readinessReasons)[number];

/** The bindings and secrets whose absence is a key problem. */
export const readinessKeyBindings = ["HMAC_W2C_KEY", "HMAC_C2W_KEY", "CSRF_SECRET"] as const;

/** The outcomes of one bounded Worker probe of a Durable Object or R2. */
export const readinessProbeOutcomes = ["ready", "no_answer_in_wait", "unreachable"] as const;

/** Every readiness term the Worker names, keyed by itself (CLOUD.84 S43). */
export const readinessTerms = {
  production: "production",
  proof: "proof",
  ingress: "ingress",
  container: "container",
  d1: "d1",
  durableObject: "durableObject",
  r2: "r2",
  queue: "queue",
  ready: "ready",
  starting: "starting",
  unavailable: "unavailable",
  misconfigured: "misconfigured",
  unknown: "unknown",
  not_required: "not_required",
  probed: "probed",
  bound: "bound",
  binding_missing: "binding_missing",
  key_missing: "key_missing",
  key_mismatch: "key_mismatch",
  host_route_missing: "host_route_missing",
  host_reply_invalid: "host_reply_invalid",
  host_error: "host_error",
  no_instance_available: "no_instance_available",
  start_failed: "start_failed",
  rate_limited: "rate_limited",
  no_answer_in_wait: "no_answer_in_wait",
  unreachable: "unreachable",
  container_not_ready: "container_not_ready",
  plan_hash_mismatch: "plan_hash_mismatch",
  schema_mismatch: "schema_mismatch",
  recovery_generation_mismatch: "recovery_generation_mismatch",
  d1_unavailable: "d1_unavailable",
} as const;

/** The declared bindings per component and environment. Only names are declared, never values. */
export const readinessBindings = [
  {
    component: "ingress",
    name: "SOURCE_REVISION",
    environments: ["production", "proof"],
  },
  {
    component: "ingress",
    name: "HELLO_RATE_LIMITER",
    environments: ["production", "proof"],
  },
  {
    component: "ingress",
    name: "ALLOWED_ORIGIN",
    environments: ["proof"],
  },
  {
    component: "container",
    name: "CLOUD_CONTAINER",
    environments: ["production", "proof"],
  },
  {
    component: "container",
    name: "HMAC_W2C_KEY",
    environments: ["proof"],
  },
  {
    component: "container",
    name: "CSRF_SECRET",
    environments: ["proof"],
  },
  {
    component: "d1",
    name: "DB",
    environments: ["proof"],
  },
  {
    component: "d1",
    name: "RECOVERY_GENERATION",
    environments: ["proof"],
  },
  {
    component: "d1",
    name: "HMAC_C2W_KEY",
    environments: ["proof"],
  },
  {
    component: "durableObject",
    name: "JOB_COORDINATOR",
    environments: ["proof"],
  },
  {
    component: "r2",
    name: "OBJECTS",
    environments: ["proof"],
  },
  {
    component: "r2",
    name: "REALM_ID",
    environments: ["proof"],
  },
  {
    component: "queue",
    name: "WAKE_QUEUE",
    environments: ["proof"],
  },
] as const;
export type ReadinessBindingName = (typeof readinessBindings)[number]["name"];
/** Limits and identifier shapes the Worker applies before it forwards a call (CLOUD.84 S34, S39(3) and S43(3)), declared in src/ArcForges.Cloud/Generation. */
export const bearerCredentialPattern = /^Bearer ([A-Za-z0-9._~+/=-]{16,4096})$/u;
export const bindingUint64TextPattern = /^(0|[1-9][0-9]{0,19})$/u;
export const bodyReadMilliseconds = 5000;
export const canonicalUuidPattern =
  /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/u;
export const classifiedPrefixBytes = 128;
export const containerSleepAfter = "60s";
export const deadlinePattern =
  /^(\d{4})-(\d{2})-(\d{2})T(\d{2}):(\d{2}):(\d{2})(?:\.(\d{1,7}))?Z$/u;
export const emptyBodyHash = "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855";
export const epochSecondsPattern = /^[1-9][0-9]{0,15}$/u;
export const grpcFrameHeaderBytes = 5;
export const hexBytesPattern = /^(?:[0-9a-f]{2})*$/u;
export const int64TextPattern = /^(?:0|-?[1-9][0-9]*)$/u;
export const keyIdPattern = /^[A-Za-z0-9][A-Za-z0-9._-]{0,63}$/u;
export const macBytes = 32;
export const maxElapsedMs = 60000;
export const maxPartBytes = 8388608;
export const maxReplyBytes = 65536;
export const maxRequestBytes = 16384;
export const maxRevisionLength = 80;
export const maxSchemaVersionLength = 8;
export const maxSkewSeconds = 60;
export const noncePattern = /^[A-Za-z0-9_-]{22}$/u;
export const nonceRandomBytes = 16;
export const objectsContentLengthPattern = /^[1-9][0-9]{0,8}$/u;
export const objectsRangePattern = /^bytes=(\d{1,12})-(\d{1,12})$/u;
export const operatorHeaderPattern =
  /^AF-Operator t=(\d{10}),n=([A-Za-z0-9_-]{22}),s=([A-Za-z0-9_-]{86})$/u;
export const operatorMaxSkewSeconds = 60;
export const operatorPublicKeyBytes = 32;
export const operatorSignatureBytes = 64;
export const proofMinimumTokenBytes = 32;
export const proofRetryDelaySeconds = 60;
export const realmPattern = /^[a-z0-9][a-z0-9-]{0,31}$/u;
export const routerBodyReadMilliseconds = 1000;
export const scopePattern = /^proof\/[A-Za-z0-9._/-]{1,200}$/u;
export const secretByteLength = 32;
export const sessionTokenPattern = /^[A-Za-z0-9_-]{43}$/u;
export const sha256HexPattern = /^[0-9a-f]{64}$/u;
export const spanIdByteLength = 8;
export const uint64TextPattern = /^(?:0|[1-9][0-9]*)$/u;
