// SPDX-License-Identifier: AGPL-3.0-only
// GENERATED by tools/ArcForges.Cloud.Generation from the C# host registrations (HelloModule and PipelineProbe), the transport
// budgets and correlation guards in src/ArcForges.Cloud/Generation and the edge-guard constants of IngressPipeline. Do not edit by hand: run
// `npm run generate` and commit the result. `npm run check:generated` fails on any drift. The Worker applies these guards
// before it forwards a call; nothing here grants anything.

/** The kind of a method the Worker admits: one unary reply, or a server stream. */
export type RouteKind = "unary" | "serverStream";
/** anonymous: no credential is read or forwarded; session: bearer or origin-bound cookie, checked again by the host. */
export type RouteAuth = "anonymous" | "session";

export interface ApiRoute {
  /** The method path without the owned /api prefix: /package.Service/Method. */
  readonly path: string;
  readonly kind: RouteKind;
  readonly auth: RouteAuth;
  /** Bound of the whole request body, frame header included. Unary and server-streaming requests are one message. */
  readonly maxRequestBytes: number;
  /** Bound of one response frame. */
  readonly maxFrameBytes: number;
  /** Bound of a whole unary response (buffered); a stream has no total bound, only its lifetime. */
  readonly maxUnaryResponseBytes: number;
  /** Cap of the RPC deadline (unary) or of the stream's lifetime (server stream). */
  readonly maxDurationMs: number;
  /** The Container instance (Durable Object name) that serves the method. */
  readonly instance: string;
  /**
   * The request message starts with a RequestMeta (field 1, wire registry 04). Only then does the edge read the client's
   * correlation id from it; a method whose field 1 means something else (the Hello name) is never interpreted.
   */
  readonly requestMeta: boolean;
}

export const helloPath = "/api/arcforges.hello.v1.HelloService/SayHello";
export const healthPath = "/api/healthz";
/** The bound of a whole request body of a method that declares no larger one, frame header included. */
export const maxBodyBytes = 4096;
/** The Container may take at most this long to start before a stream's response headers arrive. */
export const coldStartBudgetMs = 15000;
/** A server stream's lifetime when the client states no shorter deadline: the annex 10 server close after five minutes plus slack. */
export const streamLifetimeMs = 310000;

/** The health route: a small plain reply that the pipeline answers itself. */
export const healthRoute: ApiRoute = {
  path: "/healthz",
  kind: "unary",
  auth: "anonymous",
  maxRequestBytes: 0,
  maxFrameBytes: 0,
  maxUnaryResponseBytes: 8192,
  maxDurationMs: 15000,
  instance: "hello",
  requestMeta: false,
};

/** The methods the production Worker serves. */
export const productionRoutes: readonly ApiRoute[] = [
  {
    path: "/arcforges.hello.v1.HelloService/SayHello",
    kind: "unary",
    auth: "anonymous",
    maxRequestBytes: 4096,
    maxFrameBytes: 8192,
    maxUnaryResponseBytes: 8192,
    maxDurationMs: 10000,
    instance: "hello",
    requestMeta: false,
  },
];

// Proof-only pipeline probe (the isolated proof environment, FOUNDATION_PROOF=enabled): an authenticated
// workspace-scoped unary call, a timed server stream and an observation of how the host saw its streams end.
export const proofRoutes: readonly ApiRoute[] = [
  {
    path: "/arcforges.proof.v1.PipelineProbe/Whoami",
    kind: "unary",
    auth: "session",
    maxRequestBytes: 4096,
    maxFrameBytes: 65536,
    maxUnaryResponseBytes: 8192,
    maxDurationMs: 10000,
    instance: "foundation",
    requestMeta: true,
  },
  {
    path: "/arcforges.proof.v1.PipelineProbe/Stream",
    kind: "serverStream",
    auth: "session",
    maxRequestBytes: 4096,
    maxFrameBytes: 65536,
    maxUnaryResponseBytes: 8192,
    maxDurationMs: 60000,
    instance: "foundation",
    requestMeta: true,
  },
  {
    path: "/arcforges.proof.v1.PipelineProbe/Observation",
    kind: "unary",
    auth: "session",
    maxRequestBytes: 4096,
    maxFrameBytes: 65536,
    maxUnaryResponseBytes: 8192,
    maxDurationMs: 10000,
    instance: "foundation",
    requestMeta: true,
  },
];

/** The session credential names the edge checks read; the header name is lowercase as the Worker forwards it. */
export const edgeGuard = {
  sessionCookieName: "__Host-af_session",
  csrfHeader: "x-af-csrf",
} as const;

/** The correlation guards (CR-01, CR-03): the identity shape, the fields that carry it and the traceparent form the Worker writes. */
export const correlationGuard = {
  uuidPattern: "^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$",
  nilUuid: "00000000-0000-0000-0000-000000000000",
  requestMetaField: 1,
  correlationIdField: 3,
  idValueField: 1,
  idByteLength: 16,
  traceparentVersion: "00",
  traceparentFlags: "01",
} as const;
